### ISSUE TITLE
[BUG] E-Mail subject containing '&' not encoded correctly

### ISSUE THREAD

**Issue by githubUser123444** [derhansen/sf_event_mgt#1005]
I am using version 6.0.1 of the sf_event_mgt extension.

### Problem:
When i send e-mails using the extension, the subject seems to be encoded incorrectly when using a '&' character in the event title.

![image](https://user-images.githubusercontent.com/75419397/166933687-5aaa71d5-c6a3-4998-b6ec-4b5f31c2cee0.png)

The body of the mail is correctly encoded displaying '&' as intended:

![image](https://user-images.githubusercontent.com/75419397/166934972-b4151154-d865-4065-a553-cd71ee91197e.png)

### Steps to reproduce
1. Use an event title that contains a '&' symbol

### Server configuration
**TYPO3 version: 11.5.9

**PHP version: 7.4.6

Is this a bug or a misconfiguration?

Thanks for your reply in advance

**Comment by derhansen** [comment]
Thanks for your report. This is a bug, which I now fixed in the development branch.
