### ISSUE TITLE
Possible bug in documentation -> ViewHelpers

### ISSUE THREAD

**Issue by at-ac** [derhansen/sf_event_mgt#1009]
### Extension version
6.2.2

### Short problem description
Amount of events per category in list view category filter shows only '0', if using ViewHelper as described here:
https://docs.typo3.org/p/derhansen/sf_event_mgt/main/en-us/ForAdministrators/Templates/Viewhelpers/Index.html
or in CountViewHelper.php 'Example Usage'

### Steps to reproduce
1. Added 'xmlns:e="http://typo3.org/ns/DERHANSEN/SfEventMgt/ViewHelpers" in Templates/Event/List.html
2. Added ViewHelper <e:category.count categoryUid="{category.item.uid}" /> after {category.title} 
3. Configured Plugin to show category filter - filtering works

### Expected behaviour
Show amount of events per category

### Actual behaviour
Output was only '0' in each category

### Server configuration
**TYPO3 version:**
11.5.9

**PHP version:**
7.4.28

### Solution that works for me
use without 'item'
<e:category.count categoryUid="{category.uid}" />
instead of 
<e:category.count categoryUid="{category.item.uid}" />

**Comment by derhansen** [comment]
Thanks a lot for your report. I fixed the wrong example in the docs.
