### ISSUE TITLE
Make softrefs configurable

### ISSUE THREAD

**Issue by FLeudts** [derhansen/sf_event_mgt#1026]
### Extension version
6.2.2

### Short problem description
The issue #907 results in our installation in an awfully big logfile. From 16.05. until 07.07. 13578 entries of 16000 entries concern the missing softrefs rtehtmlarea_images and images. And as the loglevel for the missing softrefs is warning I wouldn't want to raise the log level. 

### Steps to reproduce
1. Have ext:sf_event_mgt installed
2. Don't have ext:rte_ckeditor_image installed

### Expected behaviour
Make the softref option configurable like the slugBehavior

### Server configuration
**TYPO3 version: v11.5.10**
**PHP Version: 8.1**

**Comment by derhansen** [comment]
Thanks for your report. This behavior is indeed unfortunate. I will fix this issue by only adding `rtehtmlarea_images` to `softref`, when ext:rte_ckeditor_image is installed.

**Comment by derhansen** [comment]
@FLeudts I pushed a patch and also removed the `images` property completely, since this is not used any more and ext:rte_ckeditor_image also unsets it when set.
