### ISSUE TITLE
[SUGGESTION] allow multiple locations for an event

### ISSUE THREAD

**Issue by medarob** [derhansen/sf_event_mgt#1032]
We have an event which takes place over 2 days with different locations each day.
In the location field of an event only 1 location can be used right now.

Perhaps it is possible to add several locations to an event?

The workaround right now is to create a new location with both location names as title and to add both addresses to the address field. This seems to be redundant because both locations exists already separately.

**Comment by derhansen** [comment]
Thanks for your suggestion. I will keep the current behavior and suggest, that you create a custom extension which changes the behavior (Extend TCA, modify repository queries if required, change attributes in DTO if required) of the main extension.
