### ISSUE TITLE
Weekday-names are missing in calendar-view

### ISSUE THREAD

**Issue by nebrot** [derhansen/sf_event_mgt#1035]
### Extension version
6.2.4

### Short problem description
In calendar-view the weekday-names are missing, probably because of wrong index.

### Steps to reproduce
1. Use Calendar view (sfeventmgt_pieventcalendar)
2. ul with class "event-calendar__weekdays" has no weekday-names ([/Templates/Event/Calendar.html](https://github.com/derhansen/sf_event_mgt/blob/main/Resources/Private/Templates/Event/Calendar.html#L57-L59))

### Expected behaviour
The weekday-names are shown.

### Actual behaviour
The weekday-names are not shown.

### Possible Fix
If i debug "{weeks}" there is no index "0", the first index is the current week "39".

[Change](https://github.com/derhansen/sf_event_mgt/blob/main/Resources/Private/Templates/Event/Calendar.html#L57-L59)
```
<f:for each="{weeks.0}" as="weekday">
	<li class="event-calendar__weekdays-weekday">{f:format.date(date: weekday.timestamp, format: '%a')}</li>
</f:for>
```

to

```
<f:for each="{weeks}" as="week" iteration="iterator">
	<f:if condition="{iterator.isFirst}">
		<f:for each="{week}" as="weekday">
			<li class="event-calendar__weekdays-weekday">{f:format.date(date: weekday.timestamp, format: '%a')}</li>
		</f:for>
	</f:if>
</f:for>
```

### Server configuration
**TYPO3 version:**
11.5.16

**PHP version:**
7.4

**Comment by derhansen** [comment]
Thanks a lot for your report. I fixed this as suggested in the default template of the extension.

**Comment by derhansen** [comment]
Closing issue. Fix will be included in the next release
