### ISSUE TITLE
Mails send by sf_event_mgt are marked as Spam

### ISSUE THREAD

**Issue by linawolf** [derhansen/sf_event_mgt#1036]
### Extension version
TYPO3 10.4.32 with sf_event:mgt 5.9.2, TYPO3 configured to send mails via SMTP

### Short problem description
The mails send by the extension are marked as Spam

### Expected behaviour
I suspect the extension is sending the Mails via Sendmail not SMTP as configured?

### Actual behaviour
Send mail via SMTP

### Server configuration
**TYPO3 version:** 10.4.32

**PHP version:**7.4

**Comment by derhansen** [comment]
The extension uses the TYPO3 email API, so all emails sent by the extension will follow the global configured email settings in TYPO3. Therefore I'm closing this ticket now.

Feel free to contact me on Slack with the complete header data of an email that has been marked as spam. Maybe I can help out or explain, why the email got tagged as spam.
