### ISSUE TITLE
Example Route Enhancers are not fully working

### ISSUE THREAD

**Issue by dennismetz** [derhansen/sf_event_mgt#1049]
### Extension version
6.3.0

### Short problem description
I have copied all route enahncers according to the instructions and entered them into the SiteConfig, but the RouteEnhancer for the register page does not work (only changed pageid).
I always get the message "This event is no longer available" - without Route Enhancer the registration is displayed.

https://docs.typo3.org/p/derhansen/sf_event_mgt/6.3/en-us/ForAdministrators/Configuration/RouteEnhancers/Index.html

### Steps to reproduce
1. Create event, fill in completely
2. Click on "register" in the list view

### Expected behaviour
I should be able to register

### Actual behaviour
On the Register page the following error message appears "This event is no longer available"

### Server configuration
**TYPO3 version:**
11.5.18

**PHP version:**
8.1

**Comment by derhansen** [comment]
I'm unable to reproduce the described problem. The RouteEnhancer configuration in the documentation is the one I'm using for local development.

Also, the described message `This event is no longer available` seems not to be part of the main extension. 

If route enhancers are configured wrong, most likely you will end up in a 404 error and not a message as described. Please check your `Registration.html` template for possible conditions that could result in the message descibed.

**Comment by amayer84** [comment]
Hello there :) I can reproduce this issue as well. After digging a little bit I noticed that the message "This event is no longer available" only appears if the **same** slug is used by a news item. I use the recommended routeEnhancers config from the docs (sf_event_mgt and news). 

I'll keep digging and in case I find a solution I'll post it here.

**Comment by amayer84** [comment]
The information in this thread helped me to solve the issue: https://forge.typo3.org/issues/95766
