### ISSUE TITLE
CSV Export title of event

### ISSUE THREAD

**Issue by zottelmann** [derhansen/sf_event_mgt#1052]
### Extension version
Tell me which version of sf_event_mgt you use
4.5.0

### Short problem description
Hello!

Is it possible to export the Event title and/or teaser to csv? When i put "title" or "teaser" into csvExport{fields =...}, i get an error that there is no such field property. When using "phone" (which is also a field in the backend) it exports it as expected.

I am not an expert in typo3, how can i get the the title into the csv export?

Regards,
Timo

### Server configuration
9.5.31

**PHP version:**
7.4

**Comment by derhansen** [comment]
The export actually exports registration record, so if you want to include event data to export event related data , you need to get the data from the event record which is available in the event records. The example below shows how to export both fields:

`fields = uid, gender, firstname, lastname, event.title, event.teaser`

**Comment by zottelmann** [comment]
Hello!

Thanks for the answer. if i put 
```` event.teaser or .title`
i get an error "Field ... is not a Property of Model Registration..."
I am not sure What that means but i am willing to learn :smile:

**Comment by derhansen** [comment]
OK, I just saw you use version 4.x of the extension, which supports TYPO3 8.7 and 9.5. For version 4.x, it is not supported to export event data as described. 

I highly recommend to update to a supported TYPO3 version and to use at least version 5.x or 6.x of the extension.

**Comment by zottelmann** [comment]
Hello!

Oh, then i shall do that. Thank you again. 

Cheers!
