### ISSUE TITLE
Redirect on slug change

### ISSUE THREAD

**Issue by ste101** [derhansen/sf_event_mgt#1085]
It would be great to have a automatic redirect creation on slug update like news_redirect_slug_change:
https://extensions.typo3.org/extension/news_redirect_slug_change

**Comment by derhansen** [comment]
Yes, would be a nice feature as an additional extension. Sure someone<sup>TM</sup> can easily create a similar extension which does the same as `news_redirect_slug_change`.

**Comment by derhansen** [comment]
Closing this ticket, since I will not implement this to the extension.
