### ISSUE TITLE
[Feature request] Possibility to display events either with or without end date

### ISSUE THREAD

**Issue by Hobokens** [derhansen/sf_event_mgt#1106]
### Extension version
6.3.1

### Short problem description
Sometimes we have open end events. Only in this case no end date should be shown in frontend.

### Wanted behaviour
It would be nice to have the possibility to display events either with or without end date. 
Idea for a solution: allow start date and end date to be the same. Then with a condition the end date could be easily hidden.

### Actual behaviour
Currently you are forced to set an enddate in the future

### Server configuration
**TYPO3 version: 11.5.25

**PHP version: 8.1.16

**Comment by derhansen** [comment]
It is actually already possible to create events, which do not have any end date. You just have to leave the end date field empty as shown below

![image](https://user-images.githubusercontent.com/2629896/234774338-b50187e7-286e-49c9-b028-1d3c668f9661.png)

In this case only the start date is shown (see screenshot)

![image](https://user-images.githubusercontent.com/2629896/234774153-1f59073a-9ae3-4e2f-8851-3a831b59f8ce.png)

**Comment by Hobokens** [comment]
Oh, I missed that point. Thanks for the great extension.
