### ISSUE TITLE
No clickable links generated in the notification e-mails

### ISSUE THREAD

**Issue by juergen1964** [derhansen/sf_event_mgt#1112]
### Extension version

Version: sf_event_mgt 6.3.1

### Short problem description
No clickable links generated in the notification e-mails

### Steps to reproduce
1. The extension works fine at all, exept for me in the notification mails there are no clickable links generated 
2. The routeEnhancers work fine - maybe there is some settings i need to adjust ? Or some settings in the .htaccess file?
3. The page is a subdomain, but i also tryed the functionality with a main domain with the same result

### Expected behaviour

I got a data string in the e-mails that work if i copy and paste them into the browser line. So the data is generated correct.
Unfortunately it generates no clickable link in my notification e-mails

### Actual behaviour

Is there some settings that i need to expand or adjust?

I know there could be a wide range of reasons for not working properly with generate the links. But maybe someone got a idea?

### Server configuration

TYPO3: 11.5.25
PHP: 8.0.28

Thx for the really great extension!!!!
Many greetings!

**Comment by juergen1964** [comment]
Update:
Now i found out that the link is generated if i check my e-mails with my smartphone -  so it seems to be a problem with the mail-software on my pc.

here i use the thunderbird - so it looks like with the sf_event_mgt extension everything is fine.

sorry for posting. Now i need to check my thunderbird software.

Thx and have a nice week

**Comment by derhansen** [comment]
The extension uses `f:uri.action` viewHelpers by default to create links to e.g. configuration page. Links created that way are not clickable by default and some email clients automatically render them als clickable links and others do not.

If you want to ensure, that users get a clickable link, you must configure the email templates to use `f:link.action` instead. 

**Before:**

```
<f:uri.action action="confirmRegistration" arguments="{reguid: '{registration.uid}', hmac: '{hmac}'}" absolute="TRUE" controller="Event" extensionName="sfeventmgt" pluginName="Pieventregistration" />
```

**After:**

```
<f:link.action action="confirmRegistration" arguments="{reguid: '{registration.uid}', hmac: '{hmac}'}" absolute="TRUE" controller="Event" extensionName="sfeventmgt" pluginName="Pieventregistration">
    Confirm registration
</f:link.action>
```

Note, that you must provide a link text, when using `f:link.action` as shown above.

**Comment by juergen1964** [comment]
Hi and thx a lot!
Works perfect!
