### ISSUE TITLE
Notification e-mails look like the system e-mails of TYPO3

### ISSUE THREAD

**Issue by juergen1964** [derhansen/sf_event_mgt#1117]
### Extension version
sf_event_mgt version: 6.3.1

### Short problem description
i wanted the notification e-mails look like the system e-mails of TYPO3. (and use the backend-login logo like system mails does)

### Steps to reproduce
By checking the default system e-mail template of TYPO3 there are variables in use like:
{typo3.systemConfiguration.backend.loginHighlightColor} 
{typo3.systemConfiguration.backend.loginLogo}
*img src="{normalizedParams.siteUrl}{f:uri.resource(extensionName: 'core', path: 'Images/typo3_black.svg')}" alt="TYPO3 Logo" height="41" width="150"

### Expected behaviour
I wanted the notification templates to use the image of the backend login like it is done by system emails of TYPO3 

### Actual behaviour
I reached my goal by using VHS viewhelper instead in my notification templates
I used this 2 viewhelpers: <v:site.url/> and <v:site.name/>

With the <v:site.url/> viewhelper i got dynamic links generated an i got my image working like this:

img src="<v:site.url/>{f:uri.resource(extensionName: 'myextname', path: 'Images/logo/mylogo.png')}" alt="<f:translate key="LLL:EXT:myextname/Extensions/FormCustom/Resources/Private/Language/locallang.xlf:email.logo.alt"/>" height="185" width="180"

This works but the image is not flexible like in the system mail of TYPO3. There is this condition working: 

`<f:if condition="{typo3.systemConfiguration.backend.loginLogo}">
<f:then>
<img src="{typo3.systemConfiguration.backend.loginLogo -> core:normalizedUrl()}" alt="TYPO3 Logo" height="41" width="150" />
</f:then>
<f:else if="{typo3.systemConfiguration.backend.loginHighlightColor}">
<img src="{normalizedParams.siteUrl}{f:uri.resource(extensionName: 'core', path: 'Images/typo3_black.svg')}" alt="TYPO3 Logo" height="41" width="150" />
</f:else>
<f:else>
<img src="{normalizedParams.siteUrl}{f:uri.resource(extensionName: 'core', path: 'Images/typo3_orange.svg')}" alt="TYPO3 Logo" height="41" width="150" />
</f:else>
</f:if>`

Unfortunately i am not able to make the needed variables available in my notification templates of the sf_event_mgt extension. 

Anyway, for the moment i am happy with my result.

Would it not be nice to have that feature to use the backend-login logo and highlight-color of the system mails implemented by default?
 I was looking for a solution to make the variables available - but no success. I even was unable to find out where the variables are comming from.
Probably from the sysext "backend"??

Is this maybe feasible task for someone with more knowledge? I guess it would be nice to have that implemented, what do you think? 

Thx a lot - and i love this extension more and more, great one!

TYPO3 version 11.5.25

PHP version: 8.0.28

**Comment by derhansen** [comment]
The usage of my own solution to send emails with fluid is actually by intention (see also #852). I still have no plans to change this currently.

**Comment by juergen1964** [comment]
Hi and thank You for quick response!

ok, i understand just thought it would be nice to have a option to turn on the "behave like system-mails" (e. g. in the constants) and got the variables available.

Anyway, i am using your templates with a little modification and my solution with usage of the VHS viewhelper works for me and after all i don`t mind. Sorry that i borderes You, i did not took notice of the already postet kind of simular question.

Have a nice weekend!

**Comment by derhansen** [comment]
No Problem. I'm always happy to help if possible. 

Have a nice weekend too!
