### ISSUE TITLE
Backend Module - No sender email address

### ISSUE THREAD

**Issue by ste101** [derhansen/sf_event_mgt#1132]
TYPO3 12.4.1
PHP 8.1
sf_event_mgt 7.1.2

I configured both module.tx_sfeventmgt.settings.notification and tx_sfeventmgt.settings.notification
senderEmail
senderName
senderSignature

I can see the settings in the typoscript browser but I'm still getting 'No sender email address' when I'm trying to notify participants.
Registration emails are sent.

**Comment by derhansen** [comment]
I'm unable to reproduce the problem and notifications through the backend module work as expected. The message is shown, when `settings.notification.senderEmail` is empty. I assume, this must somehow be a local configuration issue somewhere.

Please select the folder with your events and ensure, that TypoScript settings for the event module are applied to the folder as shown in the example below:

![image](https://github.com/derhansen/sf_event_mgt/assets/2629896/ad4567de-d29b-4051-9b20-b13f8a70c4cf)

**Comment by ste101** [comment]
Same here:
![grafik](https://github.com/derhansen/sf_event_mgt/assets/359959/47bed9e7-f4ea-4eff-b786-b959d4c93c0b)
I can give you access if you need.

**Comment by ste101** [comment]
It is working now. Don't know why. I didn't change anything and suddenly is worked.
Thank you for your support.
