### ISSUE TITLE
Class DisableLanguageMenuProcessor doesn't consider registration context

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [derhansen/sf_event_mgt#1138]
### Extension version
6.4.1

### Short problem description

On a multilanguage page (DE + EN) with registration plugin, the english language option is displayed in the language menu (generated by `TYPO3\CMS\Frontend\DataProcessing\LanguageMenuProcessor`), although there is no localised event.

### Steps to reproduce
1. Add registration plugin to a page
2. Create an event without translations for other languages
3. Show event on page from step 1
4. Look at the language menu

### Expected behaviour
In the language menu (fluid), the second language item (EN) should have `available = false` if there is no localised event.

### Actual behaviour
 `available = 1`

### Reason

Class `DisableLanguageMenuProcessor` uses `tx_sfeventmgt_pieventdetail` for getting the event ID, therefore the event ID is always 0 on registration pages, which means the process is stopped at this point:

https://github.com/derhansen/sf_event_mgt/blob/ec13aae52fef49360f453ee4a98597057ba6f6f1/Classes/DataProcessing/DisableLanguageMenuProcessor.php#L43

If you change `tx_sfeventmgt_pieventdetail` to `tx_sfeventmgt_pieventregistration`, it works on the registration page, but not on the detail page.

Note:s:

- Worked prior removal of switchable controller actions.
- Same code works in EXT:news because there is no registration context.

### Possible Solution

Add 2 more conditions that also consider `tx_sfeventmgt_pieventregistration` here:

https://github.com/derhansen/sf_event_mgt/blob/ec13aae52fef49360f453ee4a98597057ba6f6f1/Classes/DataProcessing/DisableLanguageMenuProcessor.php#L80

Also change wording in the following line. ;o)

https://github.com/derhansen/sf_event_mgt/blob/ec13aae52fef49360f453ee4a98597057ba6f6f1/Classes/DataProcessing/DisableLanguageMenuProcessor.php#L22

### Misc

Backport to 6.x would be very nice.

### Server configuration

TYPO3 11.5.28
PHP 7.4

**Comment by derhansen** [comment]
Will be included in 7.2.0 and 6.5.0

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Thanks alot! <3
