### ISSUE TITLE
[FEATURE] New PSR event after checkRegistrationSuccess

### ISSUE THREAD

**Issue by r3h6** [derhansen/sf_event_mgt#1151]
### Extension version
7.2.0
### Short problem description
Need to implement custom logic if it is posssible to register to an event

### Steps to reproduce
-

### Expected behaviour
A new PSR event to change the outcome of checkRegistrationSuccess [$success, $result]

### Actual behaviour
Only way to implement custom logic is xclass or patches

### Server configuration
**TYPO3 version:** 12.4

**PHP version:** 8.2

**Comment by derhansen** [comment]
Will add this to version 7.2.1

**Comment by derhansen** [comment]
Released https://github.com/derhansen/sf_event_mgt/releases/tag/7.3.0
