### ISSUE TITLE
[question] settings not available in event template

### ISSUE THREAD

**Issue by medarob** [derhansen/sf_event_mgt#1157]
My use case was to check for the current language in the fluid event templates.

I found this (https://docs.typo3.org/m/typo3/reference-typoscript/11.5/en-us/Conditions/Index.html#sitelanguage) approach which I wanted to try.

Typoscript

```
// set value to English-TEST
page.10.settings.currentLanguage = english-TEST

[siteLanguage("locale") == "en_GB.UTF-8"]
  page.10.settings.currentLanguage = english
[END]

[siteLanguage("locale") == "en_NZ.UTF-8"]
  page.10.settings.currentLanguage = englishNZ
[END]

// German
[siteLanguage("locale") == "de_DE.UTF-8"]
  page.10.settings.currentLanguage = deutsch
[END]
```

What I would have expected is that I can use `settings.currentLanguage` in the fluid event templates but it seems that `currentLanguage` is not available.

![grafik](https://github.com/derhansen/sf_event_mgt/assets/33951787/5e44dd06-da82-4ea1-82a4-08aba653428a)

The Typoscript Object browser shows me the following:

![grafik](https://github.com/derhansen/sf_event_mgt/assets/33951787/8da8d75b-f6a9-41fa-9af3-a49231147ab4)

Furthermore, the condition seems to be not working because the `siteLanguage("locale")` is `en_NZ.UTF-8` but the value for `currentLanguage` is still `english-TEST`. It should be `englishNZ` I would say.

After that I added the following Typoscript below the conditions:

```
plugin.tx_sfeventmgt.settings < page.10.settings
```

I thought maybe I can copy the values to the sf_eventmgt.settings array.

This seems to override/deletes some of the values. If I debug it it looks like this:

![grafik](https://github.com/derhansen/sf_event_mgt/assets/33951787/587d5d5a-5d5f-4519-993b-1da4735fe398)
Interesting: `currentLanguage = englishNZ` so the condition seems to work now

What worked is when I copy only the currentLanguage value to the event settings, like

```
plugin.tx_sfeventmgt.settings.currentLanguage < page.10.settings.currentLanguage
```

![grafik](https://github.com/derhansen/sf_event_mgt/assets/33951787/a4b1da4b-876f-46c2-b80c-4c8fbb0c0044)

That way other values don't get overridden and the correct value of currentLanguage (englishNZ) is available in the event fluid templates.

**Question:** Is that correct that own settings values are missing in sf_eventmgt.settings and do I have to copy them each on his own to the event settings?

**Comment by derhansen** [comment]
This is general Extbase behavior (not related to sf_event_mgt) and you should always add new individual keys to the settings array yourself.

**Comment by medarob** [comment]
Ok, thank you for the answer. :)
