### ISSUE TITLE
[BUG] Dates in notification subjects not localized

### ISSUE THREAD

**Issue by r3h6** [derhansen/sf_event_mgt#1159]
### Extension version
7.3.0

### Short problem description
Dates in notification subjects not localized via parseStringFluid.

Solution: standalone views must set the request object:
`$standaloneView->setRequest($GLOBALS['TYPO3_REQUEST']);`

### Steps to reproduce
1. Set plugin.tx_sfeventmgt.settings.notification.registrationConfirmed.adminSubject =  {event.title}, {event.startdate -> f:format.date(format: '%A %e. %B %Y')}
2. Register
3. Check subject

### Expected behaviour
%A is localized

### Actual behaviour
%A is always in English

### Server configuration
**TYPO3 version:** 12.4

**PHP version:** 8.2

**Comment by derhansen** [comment]
Thanks for your report. A fix will be included in version 7.3.2
