### ISSUE TITLE
[FEATURE] Add new argument to EventRepository::findDemanded

### ISSUE THREAD

**Issue by georgringer** [derhansen/sf_event_mgt#1163]
It is super helpful to have an event in `EventRepository::findDemanded` to modify the query but there are multiple calls to this method.

What about having an optional argument to this method or maybe a new property in the DTO which holds e.g. the current class/method and which is handed to the event to know by what it is called?

**Comment by derhansen** [comment]
Usually the PSR-14 event `ModifyEventQueryConstraintsEvent` is used when the DTO has been extended. What is the use case with the calling class/method?

**Comment by georgringer** [comment]
the list in the backend should be sorted by default `startdate desc`

it works fine for me as I do have a check like
```php
$demand = $eventListener->getEventDemand();
        if ($demand->getIgnoreEnableFields() && !$demand->getOrderField()) {
            $demand->setOrderField('startdate');
            $demand->setOrderDirection('desc');
        }
```

feel free to reject the issue if you don't wanna add kind of waste to the calling methods

**Comment by derhansen** [comment]
OK, I'll close the issue then.
