### ISSUE TITLE
[FEATURE] Add event in ExportService

### ISSUE THREAD

**Issue by georgringer** [derhansen/sf_event_mgt#1164]
It would be great to have an Event in `ExportService::downloadRegistrationsCsv` to modify the filename (plus a final way to modify the csv content)

**Comment by derhansen** [comment]
I usually overwrite the function by xclass or add a completely new one (e.g. if export format should be .xlsx), but  a new PSR-14 event here is no problem.

**Comment by georgringer** [comment]
I patch it myself as well but using Events is soo nice and easy that I prefer that ;)

**Comment by derhansen** [comment]
Will be included in version 7.3.2
