### ISSUE TITLE
[TASK] Change notification description

### ISSUE THREAD

**Issue by georgringer** [derhansen/sf_event_mgt#1165]
A client uses the backend module and saw the message

> Please select an email template that will be used to notify participants of the event. To add own email templates, please refer to the documentation.

and asked where the documentation is and I guess the client thinks he can add own email templates as well (those could be e.g. records or so) but this is the job of an integrator.

To improve the situation I got following ideas:

- Change the text and add an hint that this needs to be done by an integrator
- Drop the hint about own templates because there are multiple things which integrators need to do or maybe the editor just can't do because of permissions
- Drop the hint but add it for admins only (don't prefer that)

**Comment by derhansen** [comment]
I just dropped the hint about own templates.
