### ISSUE TITLE
[Feature] Allow configuration of backend module

### ISSUE THREAD

**Issue by Hobokens** [derhansen/sf_event_mgt#1169]
When opening the backend module, the events are sorted by start date, ascending. I would prefer a descending order by default. The background of my feature request: If you have a lot of past events, but you don't want to delete them, you always have to scroll to see the future events.

It would also be helpful if the number of displayed events could be changed. At the moment, a maximum of 10 events are displayed on one page.

TYPO3 12.4.6, PHP 8.1, sf_event_mgt 7.3.2

**Comment by derhansen** [comment]
The amount of events per page is already configurable in TypoScript configuration. With 6d2c900 it is now also possible to define defaults in TypoScript for `orderField` and `orderDirection`. The change will be included in version 7.4.0
