### ISSUE TITLE
[Feature] Attach Files to custom notifications

### ISSUE THREAD

**Issue by zottelmann** [derhansen/sf_event_mgt#1178]
Hello!

As discussed here: https://typo3.slack.com/archives/C83T6DEKY/p1701872964848549

It seems not to be possible to attach files to custom notifications. Please make it possible :)

Regards
Timo

**Comment by derhansen** [comment]
In current main development branch, I extended the `ModifyUserMessageAttachmentsEvent` PSR-14 event, so it can also be used for custom notifications.

Additionally I added a new feature, which enables support for attachments configured in TypoScript. It used the same configuration as the existing implementation.

Example: 

```
customNotifications {
    thanksForParticipation {
        title = Thank you message
        template = ThanksForParticipation.html
        subject = Thank you for participation in event "{event.title}"
        attachments {
          user {
            fromFiles {
              1 = fileadmin/test.pdf
            }
            fromEventProperty {
              1 = files
              2 = image
            }
            iCalFile = 1
          }
        }
    }
}
```

So basically you can add attachments from a directory, event properties, registration properties or the iCal file for the event.

Both changes will be included in the next version of the extension.

**Comment by zottelmann** [comment]
You are awesome :) Thanks!
