### ISSUE TITLE
[QUESTION] How to automatically send custom notifications

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [derhansen/sf_event_mgt#1182]
Hi Torben,

here is my problem: Some registrants don't click the confirmation-link within the given time (3 days in our case). Therefore, after the link expired (or maybe some days later) we want to automatically send a reminder-e-mail with a "renewed" link that is another 3 days valid.

My Questions:

- Is it in any way possible to send such custom notifications automatically? If not, could you please give a starting point how to achieve that with your extension? I'm thinking of the TYPO3 scheduler / cronjobs of course but don't know how to call the custom notifications via an external script or the like.
- Is it enough to just update the `confirmation_until` date to make confirmation links work again?

### Server configuration
**TYPO3 version: 11.5.33
**sf_event_mgt: 6.5.2
**PHP version: 7.4

**Comment by derhansen** [comment]
This is not archievable out of the box and I will not add a reminder functionality. When someone registers to an event and has to opt-in, a message is shown, so the user should know, that he/she has to confirm the registration.

There is no way to automatically send a reminder, except you code it all yourself. Should be doable and yes, updating `confirmation_until` is required, if you want to extend the validity of the confirmation link.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Surely users should know, but some simply ignore it. :) Thanks for quick reply. I will see how to handle this.
