### ISSUE TITLE
TypoScript setting plugin.tx_sfeventmgt.settings.singleEvent is overwritten by empty flexform settings

### ISSUE THREAD

**Issue by machwert** [derhansen/sf_event_mgt#1187]
### Extension version
7.3.3

### Short problem description
I try to predefine singleEvent by TypoScript using 
plugin.tx_sfeventmgt.settings.singleEvent

But it does not work, as this setting is overwritten by flexform setting of singleEvent.
So I only get empty settings for singleEvent.

Setting of disableOverrideDemand is not possible for detail view, but if I switch temporarily to list view and enable it and switch back it seems to be set, as it is shown in plugin preview. But it does not help and 
plugin.tx_sfeventmgt.settings.singleEvent stays empty.

### Steps to reproduce
1. SET plugin.tx_sfeventmgt.settings.singleEvent = 1 # for first event entry
2. In flexform for detail view make sure singleEvent is not set
3. Show detail view in frontend for e.g. singleEvent = 2. plugin.tx_sfeventmgt.settings.singleEvent is ignored.

### Actual behaviour
I think the actual behaviour is fine, but if you want to show the detail view and the registration view on the same page (by adding the registration view by TypoScript to include it nicely in the detail view fluid template)  it is not working that way.

### Wanted behaviour
It would be nice, if either 
settings.singleEvent can be overwritten by TypoScript also for detail views, or
settings.singleEvent will be set automatically for detail view, so it can be used to display the registration view of the same event.

### Server configuration
**TYPO3 version:**
12.4.5

**PHP version:**
8.1.13

**Comment by derhansen** [comment]
Basically `settings.singleEvent` is just missing in the DataHandler Hook, which removed empty Flexform settings. I can easily add this.

**But:** Why show detail and registration plugin on the same page. I had this discussion several times on different forums already and it always came out, that only event details should be shown on the registration page. Since the whole event record is available for the  `registrationActions`, it should be no problem to render all event details available in `detailAction` in the `Registration.html` template. What do you think?

**Comment by machwert** [comment]
Thank you very much for your fast reply!

I was not aware, that all flexform configuration from detail plugin is also available for registration plugin.
But there is still a caching issue.

The detail view can be cached, but the registration view not.
I would like to build it that way, that the registration view is added via Ajax to the detail view, so I can realize completely cached event detail pages.

Therefore it would be helpful if I could set settings.singleEvent by TypoScript.

**Comment by derhansen** [comment]
I now added `settings.singleEvent` to the dataHandler hook. Will be included in the next release for TYPO3 v11 and v12
