### ISSUE TITLE
[FEATURE] Make model classes extendable like in the extension news

### ISSUE THREAD

**Issue by machwert** [derhansen/sf_event_mgt#1188]
**Extension version**
7.3.3

### Short problem description
I try to change my extension which extends sf_event_mgt and want to remove all XClass implementations.

### Actual behaviour
So far I use in ext_localconf.php
```
$GLOBALS['TYPO3_CONF_VARS']['SYS']['Objects'][\DERHANSEN\SfEventMgt\Domain\Model\Event::class] = [
    'className' => \Machwert\SfEventMgtMultidates\Domain\Model\Event::class,
];
```

### Wanted behaviour
For the extension news it is possible to extend the model classes by
`$GLOBALS['TYPO3_CONF_VARS']['EXT']['news']['classes']['Domain/Model/News'][] = 'md_news_author';`

Could it be also possible to implement such behaviour for sf_event_mgt or are there already other possibilities?

**TYPO3 Version**
12.4.5

**PHP version:**
8.1.3

**Comment by derhansen** [comment]
I`m, sorry, but I will not implement the proxy class solution ext:news uses.

**Comment by machwert** [comment]
Anyway thanks for your fast reply.

So I stay with the XClass implementation.
