### ISSUE TITLE
[FEATURE] Add notification filter "waitinglist"

### ISSUE THREAD

**Issue by georgringer** [derhansen/sf_event_mgt#1204]
### Extension version
6.6.0

### Short problem description

See screenshot
<img width="665" alt="Bildschirmfoto 2024-03-04 um 15 37 02" src="https://github.com/derhansen/sf_event_mgt/assets/1905663/ae6048d5-ad69-447a-97b4-db506ccddfc6">

currently there is a filter  for confirmed/not confirmed but IMO far more important is to send different mails based on "waitinglist yes|no"

TBH I am unsure if confirmation must be required to avoid issues with GDPR?

**Comment by derhansen** [comment]
Will be included in upcoming 6.x and 7.x versions
