### ISSUE TITLE
Improved error handling

### ISSUE THREAD

**Issue by georgringer** [derhansen/sf_event_mgt#1210]
### Extension version
6.x

### Short problem description

if there is an error in the registration, it is not really clear how to differ between success + error

<img width="749" alt="Bildschirmfoto 2024-03-11 um 08 38 03" src="https://github.com/derhansen/sf_event_mgt/assets/1905663/6dd3c47e-688c-4a8f-90c1-f20a6f2f4c0f">

suggestion: 
- add to the view the variable `$result` (checking currently saveRegistrationResultAction)
- add also error=1 if one of the `RegistrationResult::REGISTRATION_FAILED` issues to the view

**Comment by derhansen** [comment]
Done. Will be included in v6 + v7
