### ISSUE TITLE
Document usage of e:uri.page VH

### ISSUE THREAD

**Issue by georgringer** [derhansen/sf_event_mgt#1212]
### Extension version
6.x
### Short problem description

sending mails with links to backend is not possible without using the custom VH but this VH is not really known.

2 suggestions

- improved example: as it is a uri VH the tag based variant doesn't look got when using inside an a-tag, therefore improve example, see below
- link to the VH also in the notification section of the docs as this is IMO the 1st page where people begin to read when dealing with notifications

```html
  <f:if condition="{event.enableCancel}">
      <p>
          <a href="{e:uri.page(
              pageUid: 123,
              additionalParams: '{tx_sfeventmgt_pieventregistration: {pluginName:\'Pieventregistration\',extensionName:\'sfeventmgt\',action:\'cancelRegistration\',controller:\'Event\',reguid: registration.uid, hmac: hmac}}',
              absolute: 1,
          )}" class="button">Remove registration</a>
      </p>
  </f:if>
```

**Comment by derhansen** [comment]
done
