### ISSUE TITLE
[BUG] Fields  'enable_waitlist_moveup'  and 'cancel_deadline' are shown, although 'registration' is not activated

### ISSUE THREAD

**Issue by Hobokens** [derhansen/sf_event_mgt#1220]
### Extension version
Tell me which version of sf_event_mgt you use
7.4.2

### Short problem description

I have set some presets:
```
TCAdefaults.tx_sfeventmgt_domain_model_event {
    enable_cancel = 1
    enable_waitlist = 1
    enable_waitlist_moveup = 1
}
```
Now the fields '`cancel_deadline`' and '`enable_waitlist_moveup`' are displayed in the backend under '`registration options`', even if  the registration option is not activated.

### Expected behaviour

The fields should not be shown

### Server configuration
**TYPO3 version:**
TYPO3 12.4.11

**PHP version:**
8.1.27

**Comment by derhansen** [comment]
Fixed in version 7.4.2 and 6.6.3
