### ISSUE TITLE
 Field 'multireg_no_email_field' is shown, although 'registration' is not activated

### ISSUE THREAD

**Issue by Hobokens** [derhansen/sf_event_mgt#1225]
### Extension version
Tell me which version of sf_event_mgt you use
7.4.3

### Short problem description
 Field `multireg_no_email_field` is shown, although '`registration`' is not activated

### Steps to reproduce
I have installed the extension '`sf_event_mgt_wuehochdrei`'

### Expected behaviour
The field should not be shown

### Server configuration
**TYPO3 version:**
12.4.14

**PHP version:**
8.2.16

**Comment by derhansen** [comment]
@Hobokens Please adapt TCA in you custom extension. See https://github.com/derhansen/sf_event_mgt/commit/66c80644814c9642b908c62bcf370fea9cff68d8 for details.
