### ISSUE TITLE
Disable admin/organiser emails only for new registrations

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [derhansen/sf_event_mgt#1234]
Hi,

we have a request to disable the admin/organiser emails only for new registrations (first mail when double opt in is enabled) but keep the emails for confirmed registrations. Reason: Information for new registrations is simply not important and floods the organisers mailboxes.

It seems this cannot be achieved, right? Tried the following but no luck:

`plugin.tx_sfeventmgt.settings.notification.registrationNew.adminSubject >`

Mails are nevertheless sent with an empty subject. 

It would be nice to have a "feature" to not send mails if the subject is empty. Powermail for example has a subject check and doesn't send emails if it's empty. This way you can even "switch" it on/off, depending on plugin configuration, which is ace. It wouldn't be breaking, as subjects were never empty until now.

In the meanwhile... What would be the easiest way to turn these mails off either generally or for specific events?

Thanks in advance!

### Extension version
6.6.2

### Server configuration
**TYPO3 version:11.5.36
**PHP version:7.4

**Comment by derhansen** [comment]
Adding new settings do disable individual emails would be too much configuration, so checking for an empty subject is most likely the best way to archive this. Next versions of the extension (v6.x and 7.x) will include the check.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Awesome speed. Thank you so much!

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Btw, this should be documented in the email config section and/or FAQs -> "How can I disable specific emails?".

**Comment by derhansen** [comment]
@h-e-l-l-o-w-o-r-l-d Would you mind creating a PR for the FAQ change?

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
No problem, will do so ASAP.
