### ISSUE TITLE
a few organisator

### ISSUE THREAD

**Issue by o-zinger** [derhansen/sf_event_mgt#1248]
### Extension version
Tell me which version of sf_event_mgt you use 
   sf_event_mgt v7.5

### Short problem description

I would like to add multiple organizers, is it possible to make a multiple list?

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell me what should happen

### Actual behaviour
Tell me what happens instead

### Server configuration
**TYPO3 version:** 12

**PHP version:**  8.2

**Comment by derhansen** [comment]
This is not possible and will not be added to the extension, so you have to extend the extension with your custom requirements (TCA, Model, MM Tables).
