### ISSUE TITLE
Payment process only possible for confirmed registrations

### ISSUE THREAD

**Issue by r3h6** [derhansen/sf_event_mgt#1256]
### Extension version
7.3
### Short problem description
It is not possible to start payment for an unconfirmed registration.

### Steps to reproduce
1. Setup the extension with a online payment provider

### Expected behaviour
It should be possible to change the auto confirmation behavior in a way, that the confirmation is done after the successfull payment.
A more simple solution could be, that it is possible to omit the confirmation by email and not do any auto confirmation before redirecting to the payment.

### Actual behaviour
At the moment it is not possible to go to the payment if the registration is not confirmed.
It is possible to unconfirm and confirm again through psr events, but it is a bit hacky.
Also a registration could end up confirmed which should not in case something went wrong during redirecting from saving the registration to the payment process.

### Server configuration
**TYPO3 version:** 12

**PHP version:** 8.2

**Comment by derhansen** [comment]
I'm sorry, but I will not change the current behavior and will not accept PRs to do so. 

Reasons: 

- Change is breaking for existing payment implementations
- Registration/Confirmation/Payment process will be more complex as it currently already is
- Extension will be harder for me to maintain

I'm open to add new PSR-14 event(s) (e.g. to. modify the Response Object returned by the `saveRegistrationAction`), so you can manually start the payment process and do a manual confirmation after payment is finished.

**Comment by derhansen** [comment]
I'm closing this issue, since no further feedback was provided.
