### ISSUE TITLE
No manual cancelation of registrations

### ISSUE THREAD

**Issue by infodry** [derhansen/sf_event_mgt#1265]
I have set 
`plugin.tx_sfeventmgt.settings.cancellation.additionalVerificationStep = 1` 
but it has no effect when I click the cancelation-link in the confermation mail. Cancelation happens immediately.

According to the manual I would expect that after clicking the link in the confirmation mail, I get a link on the website to finally cancel the registration. 

### Server configuration
sf_event_mgt 7.5.1
TYPO3 12.4.20
PHP 8.2

(I would sponsor the work on this issue.)

**Comment by derhansen** [comment]
It may be missing in the docs, but if the option is active, possible overwritten notification templates must be adapted. 

See https://github.com/derhansen/sf_event_mgt/blob/main/Resources/Private/Templates/Notification/User/RegistrationConfirmed.html#L11

Please verify, that the `action` for the `f:link.action` ViewHelper in your templates equal to `{cancelAction}`

**Comment by infodry** [comment]
Oh yes. That was the point I did not get. Work's perfect.
Thank you.
