### ISSUE TITLE
It is not possible to cancel a booking if event is booked up

### ISSUE THREAD

**Issue by mediaessenz** [derhansen/sf_event_mgt#1267]
### Extension version
7.5.1

### Short problem description
It is not possible to cancel a booking if the event is booked up.

### Steps to reproduce
1. Add an event with **1** Max. participants, enable cancellation and automatic confirmation of event registrations
2. Book this event
3. Open the confirmation mail and click on the cancelation link
4. An error appear: The event record is not available anymore.

### Expected behaviour
A working cancelation

### Actual behaviour
No cancelation happens. This means that people who are on a waiting list do not have the opportunity to move up.

### Server configuration
TYPO3 12.4.20
PHP 8.3.11

**Comment by derhansen** [comment]
I'm not able to reproduce the problem. The message is an indicator of, that either routing is configured wrong (e.g. `limitToPages` is not defined or too loose for pages, where detail and registration plugin is placed) or that our templates use outdated plugin names.

**Suggestions:**

* Disable all route enhancers
* Check, that target PIDs are properly configured in plugins
* Check, that configured target PIDs are reflected to templates
* Check, that you use the correct pluginnames (which changed with v6 of the extension)

But in general, everything with the extension works as expected.

**Comment by mediaessenz** [comment]
I double checked all settings. Also deactivated route enhancers. Still not work :-/

**Comment by mediaessenz** [comment]
Sorry my fault. Just realized that I override the RegistrationConfirmed Template which still used an outdated Plugin name.

Sorry for interrupting you!
