### ISSUE TITLE
Set an event to "enable_registration=1" and set it back doesn't work correctly in frontend

### ISSUE THREAD

**Issue by modellbahn-anlage** [derhansen/sf_event_mgt#1298]
### Extension version
7.6.0

### Short problem description
If I set an event to "enable_registration=1" and then set it back to "enable_registration=0" after saving, the option remains set. “`tx_sfeventmgt_domain_model_event` SET `max_participants`=0” should also be set in the database.

### Server configuration
12.4.22

**PHP version:**
8.2

**Comment by derhansen** [comment]
I'm sorry, but I really do not understand what you mean. What I understood: You have an event, enable registration and set max participants to e.g. 10. Then you disable registration again and expect max participants automatically to be set to 0.

In general, there is no "magic" happening when saving events in backend. If you create an event and set max participants to a value (either 0 or a value > 0), then this value stays in the database, no matter if you disable registration again. This is regular TYPO3 backend behavior and I will not add code to the extension to change this.

**Comment by derhansen** [comment]
Closing issue, since no feedback.
