### ISSUE TITLE
[FEATURE] Add seperate searchView

### ISSUE THREAD

**Issue by derhansen** [derhansen/sf_event_mgt#139]

**Comment by phathoang** [comment]
Did you start working on this?  We need a search view and can probably help with this.

**Comment by derhansen** [comment]
Sorry,I did'nt had the time to start with the feature yet. Search view should be an easy task, since the ```findDemanded``` method provides all needed functionality.

Sadly I don't know, when I have enough time to add the feature. Pull Requests are very welcome

**Comment by derhansen** [comment]
I'll plan to work on this task during christmas :-)
