### ISSUE TITLE
[feature] Add a scheduler reminder job

### ISSUE THREAD

**Issue by erredeco** [derhansen/sf_event_mgt#145]
A nice feature: add scheduler job that sends an email to registered users that reminds them about the incoming event 
- Related: checkbox in the registration form "Yes, remind me"
- Related: set the remind interval (1 hour/1day/1week before) globally via TS or in the BE plugin interface/flexform

**Comment by derhansen** [comment]
I'm closing this issue, because #242 will include the feature you requested.
