### ISSUE TITLE
Prefill fields company and title do not work

### ISSUE THREAD

**Issue by AdlerBH99** [derhansen/sf_event_mgt#151]
Prefill works except the fields company and title.

    # Prefilling fields from fe_users table
    settings.confirmation.prefillFields {
    	firstname = first_name
	lastname = last_name
	title = title
	company = company
	address = address
	zip = zip
	city = city
	country = country
	email = email
	phone = telephone
    }

**Comment by derhansen** [comment]
Which version of sf_event_mgt do you use? 

Does the following Settings assign the firstname to the company and title field?

```
settings.confirmation.prefillFields {
    firstname = first_name
    lastname = last_name
    title = first_name
    company = first_name
}
```

**Comment by AdlerBH99** [comment]
Version 0.5.3

No it does not assign the value to the fields.

Best Regards,
Herbert

**Comment by derhansen** [comment]
I've done some debugging and can't find a problem with the extension.

But after looking at the settings you posted I found out, that you are using the wrong TS path.

Instead of ```settings.confirmation.prefillFields``` you must use ```settings.registration.prefillFields```

**Comment by AdlerBH99** [comment]
Sorry for the stupid mistake ...
