### ISSUE TITLE
Link "back to detail view" on registration view

### ISSUE THREAD

**Issue by derralf** [derhansen/sf_event_mgt#153]
Hi derhansen,
first of all: nice extension!

On registration view I want to have an additional button/link "back to detail view", but i just can't get the detailPid in this view/template.
Maybe you have a hint for me?

Using f:debug on the settings shows that settings.detailPid is empty (and there is no field in the flexform to fill out this value when selecting registration view):
```<f:debug title="settings">{settings}</f:debug>```

It stays empty even when I set a value in TS like this: 
```plugin.tx_sfeventmgt.settings.detailPid = 143```

Thanks in advance,
Ralf

**Comment by derhansen** [comment]
This may be a missing feature. I will take care of it in the next release

**Comment by derhansen** [comment]
Added to development branch. Will be included in next release version 1.0.0
