### ISSUE TITLE
[TASK] Evaluate possibilities for spam-protection of registration form

### ISSUE THREAD

**Issue by derhansen** [derhansen/sf_event_mgt#170]
e.g. hidden field, own fields, captcha

**Comment by AlexPixelant** [comment]
Hi Torben,
What do you think about implementing antispam protection using SpamShield: http://typo3.org/extensions/repository/view/wt_spamshield

Is it possible? It supports antispam protection without captcha (captcha is not user friendly).

Kind regards,
Alex

**Comment by derhansen** [comment]
Hi Alex,
thanks for your suggestion. I've contacted the vendor of wt_spamshield to get some feedback about the implementation procedure and TYPO3 V7 compatibility.

Best regards
Torben

**Comment by derhansen** [comment]
Closed #264
