### ISSUE TITLE
How to avoid errors when Event ID is not set or Event is deleted

### ISSUE THREAD

**Issue by derralf** [derhansen/sf_event_mgt#172]
Hallo Torben,

i have a page (...../veranstaltungen/details/) where the detail view is placed.

When I call this page without the required url parameters (maybe via Google, Sitemap, etc) i get an error message:
```Required argument "event" is not set.```

When I call the page with the url param ?tx_sfeventmgt_pievent%5Bevent%5D=2 (this event is deleted or set to inactive) i get the error message:
```Exception while property mapping at property path "":Object with identity "2" not found.```

Is there a way (maybe in template or plugin settings) to avoid these error messages and replace them with something like "no event found / go back to list" (maybe even with 404 status code) or similar?

Thanks,
Ralf

**Comment by derhansen** [comment]
Thanks for your feedback!

Actually there is no way to avoid this, but I'll handle the problem with the missing argument in a future version of the extension. I'll also try to take care of the problem with the deleted/hidden event.

**Comment by derhansen** [comment]
I could handle the first problem, but the second one seems to be out of my control, as this is a problem with the property mapper https://forge.typo3.org/issues/55861

**Comment by saneinsane** [comment]
Since a missing valid event argument actually is an error it should be handled accordingly (404). I solved this this way:

```php
/**
	 * @param RequestInterface $request
	 * @param ResponseInterface $response
	 * @throws \Exception
	 */
	public function processRequest(RequestInterface $request, ResponseInterface $response) {
		try {
			parent::processRequest($request, $response);
		} catch (RequiredArgumentMissingException $exception) {
			/** @var \TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController $tsfe */
			$tsfe = $GLOBALS['TSFE'];
			$tsfe->pageNotFoundAndExit('Veranstaltung wurde nicht gefunden.');
		}
	}
```
