### ISSUE TITLE
Check conditions in registration action

### ISSUE THREAD

**Issue by saneinsane** [derhansen/sf_event_mgt#177]
When the registration action is called it should validate the given event. If a user bookmark the registration form and comes back after registration deadline there should be shown an error message (reason of invalidity) instead of the form.

**Comment by derhansen** [comment]
Each event has the property {event.registrationPossible}, which returns TRUE or FALSE. I've added a Fluid condition to the default registration form, which shows an appropriate message, if the registration form should not be shown.
