### ISSUE TITLE
Default currency in TS

### ISSUE THREAD

**Issue by saneinsane** [derhansen/sf_event_mgt#178]
Add a TS setting "default currency".

**Comment by derhansen** [comment]
Could you explain, where this should be used? In the template (e.g. settings.event.defaultCurrency) which will be shown, i event.currency is empty?

**Comment by saneinsane** [comment]
I assume that in most cases the currency will be the same for all events within one installation.
Come to think about it, this should better be done through TCA configuration so it is set and visible when entering the price:
```php
$GLOBALS['TCA']['tx_sfeventmgt_domain_model_event']['columns']['currency']['config']['default'] = '€';
```
This should be no problem for the users of your extension, maybe this could be mentioned in the documentation (which is really very complete - very good job!).

**Comment by derhansen** [comment]
As the extension is also in countries, where € is not the default currency, I did'nt add a default value in TCA. I updated the FAQ section of the FAQ, which shows how to use TCAdefaults to set a default currency.
