### ISSUE TITLE
[TASK] Add documentation hints

### ISSUE THREAD

**Issue by saneinsane** [derhansen/sf_event_mgt#184]
Two hints might be helpful:
- to export CSV files, the user has to habe access to fileadmin/_temp_/
- extending the language files is possible with a ext_localconf-entry:

```$GLOBALS['TYPO3_CONF_VARS']['SYS']['locallangXMLOverride']['de']['EXT:sf_event_mgt/Resources/Private/Language/locallang_db.xlf'][] = 'EXT:my_event_mgt/Resources/Private/Language/de.locallang_db.xlf';

$GLOBALS['TYPO3_CONF_VARS']['SYS']['locallangXMLOverride']['de']['EXT:sf_event_mgt/Resources/Private/Language/locallang.xlf'][] = 'EXT:my_event_mgt/Resources/Private/Language/de.locallang.xlf';```

**Comment by saneinsane** [comment]
One more thing:
- to override email template settings you need to set 
```plugin.tx_sfeventmgt.view.templateRootPath```
This is because the class StandaloneView (used to render the mail templates) doesn’t know about templateRootPaths (this was changed in 7.3, see https://forge.typo3.org/issues/66709)

**Comment by derhansen** [comment]
Thanks! Documentation for the next version has been updated.
