### ISSUE TITLE
[BUG] Email notification texts do not respect templateRootPaths override

### ISSUE THREAD

**Issue by Jpsy** [derhansen/sf_event_mgt#202]
To customize the email notification texts (Templates/Notifications/User  and   Templates/Notifications/Admin)  we have to set the file paths using the old style technique with view.templateRootPath (singular). The new override technique view.templateRootPaths (plural) does not work.

**Comment by derhansen** [comment]
This is a missing feature in TYPO3 6.2 - the StandaloneView does not support templateRootPaths (plural). This will be fixed in TYPO3 7.3 https://forge.typo3.org/issues/66709

I will update the documentation within the next release as @saneinsane requested in #184

**Comment by Jpsy** [comment]
Aah, good to know. Thanks for the update.
