### ISSUE TITLE
Registration not possible with max participents 0

### ISSUE THREAD

**Issue by mdamen** [derhansen/sf_event_mgt#220]
When the maximum participents is 0, I get the error that there are not enough free places left to register, after filling out the forms. This is due to this check:

elseif ($event->getFreePlaces() < $registration->getAmountOfRegistrations())

in the checkRegistrationSuccess function in the EventController file. This fails for maxparticipents and thus the free places = 0. An extra check should probably be added.

**Comment by derhansen** [comment]
Thanks for your report.

When you change the affected line of code to 

<pre>
elseif ($event->getFreePlaces() < $registration->getAmountOfRegistrations() && $event->getMaxParticipants() > 0)
</pre>

Does this solve your problem?

**Comment by mdamen** [comment]
Yes it does! Thank you :)

**Comment by derhansen** [comment]
Bugfix will be included in the next release
