### ISSUE TITLE
RealURL: event category

### ISSUE THREAD

**Issue by anfuet** [derhansen/sf_event_mgt#232]
I have this code: 

```
eventCategoryConfiguration' => array(
                array(
                    'GETvar' => 'tx_sfeventmgt_pievent[overwriteDemand][category]',
                    'lookUpTable' => array(
                        'table' => 'tx_sfeventmgt_domain_model_category',
                        'id_field' => 'uid',
                        'alias_field' => 'title',
                        'addWhereClause' => ' AND NOT deleted',
                        'useUniqueCache' => 1,
                        'useUniqueCache_conf' => array(
                            'strtolower' => 1,
                            'spaceCharacter' => '-'
                        ),
                        'languageGetVar' => 'L',
                        'languageExceptionUids' => '',
                        'languageField' => 'sys_language_uid',
                        'transOrigPointerField' => 'l10n_parent',
                        'autoUpdate' => 1,
                        'expireDays' => 180,
                    )
                )
            ),
            '51' => 'eventCategoryConfiguration',
```
My problem is that the URL for categories remains cryptic.
The rule for detail works fine.

All caches were cleared.

**Comment by derhansen** [comment]
Could you add the link that is being generated (without the domain part)?

**Comment by anfuet** [comment]
event.html?tx_sfeventmgt_pievent[category]=4&cHash=a89602aa18000baf1b11d09989778b7b

**Comment by derhansen** [comment]
OK, got the problem.

In version 1.1.0, I introduced a breaking change for the category parameter (https://github.com/derhansen/sf_event_mgt/releases/tag/1.1.0)

You need to update the template, where the category links are generated. You can look in the default template how links should be generated: https://github.com/derhansen/sf_event_mgt/blob/master/Resources/Private/Templates/Event/List.html#L14 

Important is, that you pass the parameter ```arguments="{overwriteDemand:{category: category}}"``` in the ```f:link.action``` viewHelper.

Hope this solves your problem.

**Comment by anfuet** [comment]
It works! Thank you very much!

**Comment by derhansen** [comment]
You're welcome!
