### ISSUE TITLE
detailPid error

### ISSUE THREAD

**Issue by newsdesigner** [derhansen/sf_event_mgt#238]
I use Typo3 6.2.13 and the newest version of your extension. I've a problem with the detail view. The link in an item on the list page show the url of listpage. 

plugin.tx_sfeventmgt {
	settings {
		detailPid = UID of DetailPageID
	}
}

Is there a possibility to group the items per day?

**Comment by derhansen** [comment]
I'm sorry but I can't reproduce the problem.

<pre>
plugin.tx_sfeventmgt {
  settings {
    detailPid = 12
  }
}
</pre>

The TS above sets the detail PID in the list view for links to the detail page to uid 12.

You could try to debug ```<f:debug>settings</f:debug>```in your list view template to see, which values are set in the settings.

Also it is not possible to group the items per day.

**Comment by newsdesigner** [comment]
Thanks a lot for your help. I have found that the detailPid will be blank.

**TS**
plugin.tx_sfeventmgt {
	settings {
		detailPid = 10
		listPid = 11
		displayMode = future
		orderField = startdate
		orderDirection = asc
		storagePage = 13,14,15
	}
}


**Extbase Variable Dump**
array(50 items)
   clearCacheUids => '' (0 chars)
   detailPid => '' (0 chars)
   listPid => '' (0 chars)
   displayMode => 'future' (6 chars)
   orderField => 'startdate' (9 chars)
   orderDirection => 'asc' (3 chars)
   storagePage => '13,14,15' (8 chars)
   ...

**Comment by derhansen** [comment]
I still can't reproduce the problem. I've setup a blank TYPO3 installation, installed the sf_event_mgt extension from TER and as soon as I set the TS settings for detail pid, the link to the detail page is set as it should - even when I not include any other TS settings (e.g. Static TS from extension).

Please try to remove the plugin from the list page and then insert it again. Does this solve your problem?

**Comment by derhansen** [comment]
No feedback, closed
