### ISSUE TITLE
RealURL and paginate

### ISSUE THREAD

**Issue by anfuet** [derhansen/sf_event_mgt#240]
Hello,

I have a problem with my realURL configuration. I get double slash in my url with this code:

```
'page' => array(
                    array(
                        'GETvar' => 'tx_sfeventmgt_pievent[@widget_0][currentPage]',
                    ),
                ),
```

e.g.: http://www.mydomain.com/events//page/2.html

**Comment by derhansen** [comment]
Sorry, but I can't help you with this problem. I think the problem is related to your RealURL configuration.
