### ISSUE TITLE
[FEATURE]Add Time to Event

### ISSUE THREAD

**Issue by Kirika1986** [derhansen/sf_event_mgt#250]
Hi

I need a field to add the starttime and endtime. Actually I can only add startdate with time and enddate with time. I have some courses which takes place three days for only two hours (eg. Monday to Thursday from 10:00am to 12:30pm). It's possible to add these fields?

Thanks Miriam

**Comment by derhansen** [comment]
Hi Miriam,

I suggest you create an extension for sf_event_mgt which adds the needed fields.

You can find an example extension here: https://github.com/derhansen/sf_event_mgt_extend_demo

Best regards
Torben
