### ISSUE TITLE
[BUG] Events Module in Backend returns an empty page

### ISSUE THREAD

**Issue by kludikovsky** [derhansen/sf_event_mgt#274]
When It try to use the event Modaule in the backend it first displays the list of event. 
But when I select an event, a blank page is returned.
(video can be seen here: https://dl.dropboxusercontent.com/u/73439228/sfEventMgmt/SFEventMgmt.mp4)

This must not necessarily be an error, it might also be a misconfigurration from myself, but I haven't found any reports yet and have not idea where fo check. Especially as the first parst of the module works.

**Comment by derhansen** [comment]
Thanks for your feedback. I can confirm the bug using TYPO3 7.6

**Comment by derhansen** [comment]
The same applies for the "New event" button in the backend module.
