### ISSUE TITLE
[BUG] Registration returns error when "Enable unique e-mail check for registration" specified

### ISSUE THREAD

**Issue by kludikovsky** [derhansen/sf_event_mgt#275]
When I specify the 
**Enable unique e-mail check for registration**
the registration form returns a duplicate email error even when the email is not used in th whole system.

See
[Registration](https://dl.dropboxusercontent.com/u/73439228/sfEventMgmt/SFEventMgmt3a.mp4)
[Email Search](https://dl.dropboxusercontent.com/u/73439228/sfEventMgmt/SFEventMgmt4.mp4)

**Comment by derhansen** [comment]
Thanks for your feedback. I'll investigate this in the next days.

**Comment by derhansen** [comment]
Fixed in dev-branch
