### ISSUE TITLE
[BUG] Registration form Gender wrongly associated

### ISSUE THREAD

**Issue by kludikovsky** [derhansen/sf_event_mgt#276]
In the Registration form (Event/Registration.html) the gender has been wrongly associated. (Male <-> Female)

`<f:translate key="tx_sfeventmgt_domain_model_registration.gender.female" /><f:form.radio name="gender" property="gender" value="m" />
<f:translate key="tx_sfeventmgt_domain_model_registration.gender.male" /><f:form.radio name="gender" property="gender" value="f" />`

**Comment by derhansen** [comment]
Fixed in dev-branch
