### ISSUE TITLE
[TASK] Payment options

### ISSUE THREAD

**Issue by AdlerBH99** [derhansen/sf_event_mgt#278]
The extension is getting very professional! Great work!

For future releases it would be cool to have the possibility to add payment options and list them in the frontend. 

When people register, they can choose the preferred payment option. This is also saved in the registration.

**Comment by derhansen** [comment]
Thanks for your feedback. I was thinking about a payment option too and will check, if I can add a configurable/flexible option in future versions

**Comment by AdlerBH99** [comment]
Thank you! Looking forward to this feature. 

Maybe a simple Paypal Button could be a useful integration: https://developer.paypal.com/docs/integration/web/

Would enable people to create an easy online payment on their sites without complicated credit card, or online banking implementation.

**Comment by derhansen** [comment]
Feature completed. Version 1.6.0 will include payment options
