### ISSUE TITLE
[BUG] event.simultaneousRegistrations shows negative values

### ISSUE THREAD

**Issue by kludikovsky** [derhansen/sf_event_mgt#291]
In the registration form (Registration .html -Template) the 
  `                    <f:if condition="{event.maxRegistrationsPerUser} > 1">
                        <div class="event-registration-row">
                            <label for="amountOfRegistrations"><f:translate key="tx_sfeventmgt_domain_model_registration.amountOfRegistrations" /></label>
                            <f:form.select id="amountOfRegistrations" property="amountOfRegistrations" options="{e:event.simultaneousRegistrations(event: '{event}')}" />
                        </div>
                    </f:if>
`
displays negative values.
I had (accidently) the number of participants set to 0.
So it seems that there is no check on 'underflow'.

![_screen_shot_2016-02-11_170956](https://cloud.githubusercontent.com/assets/6077916/12981868/d8352870-d0e2-11e5-9f66-610e97365e44.jpg)
![_screen_shot_2016-02-11_171014](https://cloud.githubusercontent.com/assets/6077916/12981872/dce1ce46-d0e2-11e5-8d6f-83465bbf0844.jpg)

**Comment by derhansen** [comment]
Fixed in next version
