### ISSUE TITLE
requiredFields - where do entries come from

### ISSUE THREAD

**Issue by kludikovsky** [derhansen/sf_event_mgt#292]
_This might be a mistake from myself, but I have not used several hours to find it, but could not identify the cause._

For the registration I want besides the firstname, lastname and email also the gender to be mandatory. So I set this in the TS.

![_screen_shot_2016-02-11_221446](https://cloud.githubusercontent.com/assets/6077916/12991550/ea3a99a6-d10f-11e5-8b05-aa6576dc334b.jpg)

But when I debug the output page I get not only gender but also city and accepttc as mandatory. 

![_screen_shot_2016-02-11_221225](https://cloud.githubusercontent.com/assets/6077916/12991646/57a3549c-d110-11e5-9a72-aafd9f47a875.jpg)

accepttc is OK, but I don't want city. I grep'ed already through the files, but could not find anything.

Where could this come from ?

**Comment by derhansen** [comment]
Are those settings maybe set directly from the Plugin on the page?

**Comment by kludikovsky** [comment]
You are right.

I don't know why I havent seen this, even as I check it several times.

SOLVED.

Thnks.
