### ISSUE TITLE
[Feature] Locations: Link to map ("Anreise") [and picture]

### ISSUE THREAD

**Issue by kludikovsky** [derhansen/sf_event_mgt#293]
It would be nice if there would be a possibility to display the how-to-come-there for the locations.
That could .e.g be 
* as simple as to have a link on the location which cen be set to the locations homepage or a Google map, 
* or more complex to have an additional option (to above) to render the map in to the location information.

Maybe also a possibility to show a picture from the location, but this is an additional thing.

**Comment by derhansen** [comment]
I will add a link field to the location, so you can set an URL or link to a Google map.

Since the location record already contains longitude and latitude fields, it should be possible to display a location map with Javascript

**Comment by kludikovsky** [comment]
The link will be top, because it's earies for most of the people to usem than a javascriipt.

Tnx
