### ISSUE TITLE
[FEATURE] Add pagenavigation in FE list

### ISSUE THREAD

**Issue by kellemann31** [derhansen/sf_event_mgt#296]
Hi there,

I'm using your extension and it works great so far, thanks for the work :)

The only problem I'm facing is the missing pagenavigation in the frontend list.
I have about 150 events and would love to have 15 events per page and a basic page-navigation beneath these 15 events.
Is there a option which enables this feature or is it missing?

kellemann

**Comment by derhansen** [comment]
The feature exists, but not in the extension itself. TYPO3 Fluid has a pagination widget, which creates the pagination for you. Documentation can be found [here](https://fluidtypo3.org/viewhelpers/fluid/master/Widget/PaginateViewHelper.html).

You can modify your List.html template as shown below:

```
<f:widget.paginate objects="{events}" as="paginatedEvents" configuration="{itemsPerPage: 5, insertAbove: 1, insertBelow: 1, maximumNumberOfLinks: 10}">
	<f:for each="{paginatedEvents}" as="event">
		<f:render partial="Event/ListItem" arguments="{_all}"/>
	</f:for>
</f:widget.paginate>
```

I'll update the extension FAQ to include the example from above. Please don't close the issue.

**Comment by kellemann31** [comment]
Thanks for the quick response, thats exactly what I was looking for.

My first project with Typo3 Fluid, I will take a better look at the documentation you linked.

I'll leave the issue open.
