### ISSUE TITLE
iCal File template error

### ISSUE THREAD

**Issue by angeloprevitali** [derhansen/sf_event_mgt#298]
Version sf_event_mgt_1.4.0

Hi.
By calling up the frontend the iCal file gets the following error:

Template could not be found at "Event/ICalendar.txt"

TYPO3 Version 6.2.19
PHP 5.6
$TYPO3_CONF_VARS['FE']['compressionLevel'] = 0

Best regards,
Angelo

**Comment by derhansen** [comment]
Thanks fort your report. I'm pretty sure this is a regression and I'll fix it asap.

**Comment by angeloprevitali** [comment]
Thanks. That would be very cool.

**Comment by angeloprevitali** [comment]
By the way: congratulations for this very cool extension.

**Comment by derhansen** [comment]
Hi, I created a bugfix. You can test it with the current Development Branch of the extension.

**Comment by angeloprevitali** [comment]
Hi 
{back from holidays}

i just tested the fixed iCal version you wrote: There is still an error. I just saw, taht there is another EXT called fal_gallery that prevents from being displayed correctly, too. If i uninstall the the EXT:fal_gallery there comes an error anyway. 

Can you check out if you can find out something?

file1: with fixed iCal version and fixed code [BUG] Fixed iCal download error on TYPO3 6.2 - refs #298
file2: without EXT:fal_gallery

[file2.txt](https://github.com/derhansen/sf_event_mgt/files/172311/file2.txt)
[file1.txt](https://github.com/derhansen/sf_event_mgt/files/172310/file1.txt)

**Comment by derhansen** [comment]
I'm sorry, but I can't reproduce the problem on any of my test sites. Did you try the fixed version in another TYPO3 installation?

**Comment by angeloprevitali** [comment]
Try to install the EXT:fal_gallery too and you should get this error. I don't know if the error comes from your extension or from the EXT:fal_gallery. Can you trythis?

**Comment by derhansen** [comment]
I installed the extension fal_gallery and believe, that the error results because of the signal slot implementation for the "postFileCreate" slot. The function signature expects a fileInterface, which is not provided when a new file is created. I would suggest to contact the author of the extension.

Anyway, does the bugfix #298 work for you without the fa_gallery installed?

**Comment by angeloprevitali** [comment]
Thanks for checking it. I will write to the owner of the EXT:fal_gallery for debugging this issue. The bugfix #298 works fine without the EXT:fal_gallery. You can leave this as it is.
