### ISSUE TITLE
[QUESTION] RealURL Event "title-uid"

### ISSUE THREAD

**Issue by kellemann31** [derhansen/sf_event_mgt#299]
Hi again,

I'm using Typo3 7.6.4 with your extension and I have a small problem with the Event URLs.

I use RealURL with your sample code and it works fine on the default list view, but there is a problem with multiple use of the same event title, which is pretty common in our current project.
For example an event with the title "Churchday". If there is more than one event with this title the URL will be like this:

/churchday-1
/churchday-2
/churchday-3

I can't find the code, where this URL is generated and I would like to change the number after the <title> to the UID from the tx_sfeventmgt_domain_model_event table.
Is this possible?
A small hint where to look would be pretty nice.

greetings
kellemann

**Comment by derhansen** [comment]
Hi Kellemann,

this should be possible by using the following in your RealURL config:

Instead of ```'alias_field' => 'title',``` you can use ```'alias_field' => 'CONCAT('title', '-', uid)'```

You may find more info in the RealURL manual: https://github.com/dmitryd/typo3-realurl/wiki/Configuration-reference

Hope this helps.

Best regards
Torben

**Comment by kellemann31** [comment]
Hi Torben,

thanks for your answer. I tried a similiar thing before, but I think there was a cache problem.
I tried your solution and it worked.

Best regards
Alex
