### ISSUE TITLE
allow_url_fopen = 0 

### ISSUE THREAD

**Issue by angeloprevitali** [derhansen/sf_event_mgt#300]
simpleaddress_1.5.1
TYPO3 CMS Version 6.2.19
PHP 5.6

By using Version 1.5.1 with allow_url_open = 0 (disabled due to security) there is an error that TYPO3 with curl=1 (enabled).

Could you fix that bug that you could use this with curl=1 only?

Thanks.

Best Regards,
Angelo

**Comment by derhansen** [comment]
Hi Angelo,

is your issue related to sf_event_mgt? There is no version 1.5.1 of the extension.

Best regards
Torben

**Comment by angeloprevitali** [comment]
Hi Torben
i am really sorry. I wrote into the wrong GITHUB. 
Sorry again.
Best regards,
Angelo
