### ISSUE TITLE
Different Layouts not working

### ISSUE THREAD

**Issue by angeloprevitali** [derhansen/sf_event_mgt#301]
sf_event_mgt Version 1.4.0
TYPO3 CMS 6.2.19
PHP 5.6

By appling the different Templates for list view nothing happens as described in manual on page
https://docs.typo3.org/typo3cms/extensions/sf_event_mgt/Templates/Layouts/Index.html

It always takes the default layout in any case. You cannot switch layout as in the tx_news.

Page TS setup
# --------------
tx_sfeventmgt.templateLayouts {
  1 = Layout one
  2 = Layout two
}

```
<f:if condition="{settings.templateLayout} == 1">
  <f:render partial="List/LayoutOne" arguments="{eventItem: event, settings:settings}"/>
</f:if>

<f:if condition="{settings.templateLayout} == 2">
  <f:render partial="List/LayoutTwo" arguments="{eventItem: event, settings:settings}"/>
</f:if>
```
is this a bug?

Best regards,
Angelo

**Comment by derhansen** [comment]
I tested the templateLayouts setting in my TYPO3 6.2 test environment but could'nt reproduce the problem.

As soon as I select a template in the plugin, the List-View will contains ```settings.templateLayout``` with the selected ID.

You could try to use ```<f:debug>{settings}</f:debug>``` in your list template to see if the variable is available

**Comment by derhansen** [comment]
No feedback for 30+ days. Closing issue
