### ISSUE TITLE
[QUESTION] reCaptcha alternative

### ISSUE THREAD

**Issue by kellemann31** [derhansen/sf_event_mgt#302]
Hi again,

sorry to bother you again with my question, but there is one small thing left.

I would like to use something different than Googles reCaptcha.
I tried using
https://typo3.org/extensions/repository/view/sr_freecap
the documentation is pretty clear, I adjusted Classes/Domain/Model/Registration.php with the get and set codes and implemented the other Codes in the template.

The captcha is displayed, but the validation doesn't work, when I check the registraion form the next page will just show this error code "Oops, an error occurred! Code: 201603041809536d538c71".

is there an alternative captcha you offer for this extension or is the regestration.php the wrong domain model file?

If you have another hint for me I would be very thankful.

greetings
Kellemann / Alex

**Comment by derhansen** [comment]
Hi Alex,

sorry, but actually no other Captcha than Google reCaptcha is supported by the extension.

Best regards
Torben
