### ISSUE TITLE
[BUG] e-mail subject not changeable

### ISSUE THREAD

**Issue by kellemann31** [derhansen/sf_event_mgt#303]
Hi,

I have another small problem with the mails which are delivered after registration.

I can't change the mail subject. I tried the following parts from the Typoscript reference in the constant editor:
plugin.tx_sfeventmgt.settings.notification.registrationConfirmed.userSubject 
plugin.tx_sfeventmgt.settings.notification.registrationConfirmed.adminSubject

But they don't effect the confirmation mails. Do you know something about that or is this a bug in my installation?
Another question related to this topic, is it possible to add registration variabels (name, event, for example) to the mail subject?

greetings
kellemann / Alex

**Comment by angeloprevitali** [comment]
I can confirm this bug: The subjects can not be cahngeable. Is there already a solution?

**Comment by derhansen** [comment]
Actually it was not intended to change the subjects by constants. I implemented this feature with the commit 2c5849f
