### ISSUE TITLE
Warnings/error message in the event store from dev log

### ISSUE THREAD

**Issue by kludikovsky** [derhansen/sf_event_mgt#307]
### Extension version
1.4.1-dev

### Short problem description
**_This might not be an error(warning) of sf_event_mgt but as the error log is on the eventmgmt page, I post it here as a starting point to move it to the correct location. I could not find anything on the web so far about this issue._**

Error log entry on the event store page (event store is the location where the event related entries are stored).. See screenshot.
![_screen_shot_2016-04-03_120054](https://cloud.githubusercontent.com/assets/6077916/14231965/1bc3a2f6-f997-11e5-893c-e5ed6b4eccda.jpg)

There are similar entries in the other devlogs
![_screen_shot_2016-04-03_122605](https://cloud.githubusercontent.com/assets/6077916/14231971/842c5e96-f997-11e5-9ae6-17b9701e80ac.jpg)

### Steps to reproduce
1.enable dev log (dm_developerlog)
2.
3.

### Expected behaviour
no messages/warnings

### Actual behaviour
error/warning message in the log

### Server configuration
**7.6.4:**

PHP
**5.6.15**

**Comment by derhansen** [comment]
Closing the issue, since the described messages are releated to FluidTYPO3 extensions.
