### ISSUE TITLE
[SUGGESTION] German translation of gender

### ISSUE THREAD

**Issue by kludikovsky** [derhansen/sf_event_mgt#309]
### Extension version
1.4.1-dev

### Suggestion
Change the german translation for 

>    gender, male, female

to

>    Anrede, Herr, Frau

I think this sounds more approriate in that context.

**Comment by derhansen** [comment]
You can override the german locales with TypoScript.

**Comment by kludikovsky** [comment]
I solved this with deh LFEditor extension, just as comment for someone who has a similar issue.
