### ISSUE TITLE
[TASK] Add maxRegistrationsPerUser to documentation

### ISSUE THREAD

**Issue by Jpsy** [derhansen/sf_event_mgt#315]
### Extension version
1.4.1

### Short problem description
maxRegistrationsPerUser has been introduced in 1.0.0 but not been documented

### Details
I searched for an option to allow the registration of multiple participants in a single registration process. This option exists, but I only found it by chance through a hint in the changelog of v1.0.0.
I had to searched the code for the details and found the exisiting solution which works very well when activated.

### Solution
Add to documentation:
Configuration –> TypoScript Reference –> module.tx_sfeventmgt –>
* settings.maxRegistrationsPerUser
* Integer
* Allow to register multiple participant per registration. Set to a value greater than 1 an additional dropdown box will appear in the registration dialog to select the number of participants to register. The dropdown box will contain options 1 to maxRegistrationsPerUser, but will be limited by the number of remaining places for the event. See section FAQ for further details.
* Empty

### Additional task
The documentation's FAQ text "How does the simultaneous registration process work?" contains hints towards the above functionality, but with wrong TS properties ("Max. simultaneous registrations per user") that do not exist. This text should be corrected/updated too.

**Comment by derhansen** [comment]
Hi,

actually the manual contains documentation for the field in the "User Manual" section - see: https://docs.typo3.org/typo3cms/extensions/sf_event_mgt/User/Events/Index.html#registration-options

There is no TypoScript setting necessary to make use of the functionality, since it is controlled by the setting for each event individually.

Best regards
Torben
