### ISSUE TITLE
[BUG] Label for mail subjects are equal in Plugin

### ISSUE THREAD

**Issue by kimchristiansen** [derhansen/sf_event_mgt#328]
### Extension version
Extension Version 1.5.1

**Comment by derhansen** [comment]
Can't reproduce this one (checked german/english translation).

![image](https://cloud.githubusercontent.com/assets/2629896/16334764/2b48841a-3a03-11e6-9345-17b0a1cf0f11.png)

Lets check this next time we meet in person.

**Comment by kimchristiansen** [comment]
Maybe it's only wrong in the german version. Your screenshot is from the english version.
Your also have a writing error. Besätigt instead of bestätigt.

![bildschirmfoto-2016-07-20-um-10 48 27](https://cloud.githubusercontent.com/assets/1137499/16980810/18315c70-4e68-11e6-9d5c-3a2d7577bdb3.png)

**Comment by derhansen** [comment]
Thanks, I've fixed the typo and updated translations (cancel-subjects were wrong)
