### ISSUE TITLE
[Feature] Listing of Participants in Detail View

### ISSUE THREAD

**Issue by dasMurmeltier** [derhansen/sf_event_mgt#355]
Would be nice to get a listing of all participants of a event in the detail view in the frontend.

**Comment by derhansen** [comment]
This is already possible. You can use `{event.registration}` in the detail view, to get all registrations and use `<f:for each="{event.registration}" as="registration">` to iterate through all reservations.

Hope this helps

**Comment by dasMurmeltier** [comment]
Thank you, it helps! I was already writing my own viewhelper, but that solution is much easier.

**Comment by legomio** [comment]
Nice Extension. Thx!

Hi Torben, I've work with Typo3 in the past but did not used it for a while and started again with Typo3 7.6 and installed with introduction package on my local machine. I was able to make two events running and List/registration/cancellation is working as well, incl. FE user registration. I am trying exactly to create a page that shows all participants for an event, but I can't figure out how to do this :-(
Please help and provide step by step instructions to do it.

Thank you very much.

**Comment by derhansen** [comment]
In the detail-view template `Detail.html` you just have to add the following:

```
<f:for each="{event.registration}" as="registration">
{registration.firstname} {registration.lastname}
</f:for>
```

You can also use `<f:debug>{event}</f:debug>` to check all available properties of the event object.

Hope this helps

**Comment by legomio** [comment]
This is working great, THANK YOU!
