### ISSUE TITLE
Oooppss error upon registration submit

### ISSUE THREAD

**Issue by kludikovsky** [derhansen/sf_event_mgt#356]
### Extension version
1.6.1

### Short problem description
I get the following OOOPS -error when I try to send a registration input.
I have upgradedTYPO§ Base to 7.6.10, and since this happens.

I have also activated realurl, but used the described settings for the autoconfig file.

The showing of the event and skiping to the registration works fine, but as soon as I click the submit button i get this error.

### Steps to reproduce
1. Go to the events detail page
2. click the register button
3. fill in the form 
4. click the submitt button (clicking the submitt button an having the form incomplete shows the errors

### Expected behaviour
Registration

### Actual behaviour
![image](https://cloud.githubusercontent.com/assets/6077916/18281332/c8e4b4f8-745c-11e6-8218-903d48136208.png)

### Server configuration
7.6.10

**PHP version:**
5.6.23

**EDIT:**

Just found the Error Message:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1298012500: Required argument "event" is not set for DERHANSEN\SfEventMgt\Controller\EventController->registration. | TYPO3\CMS\Extbase\Mvc\Controller\Exception\RequiredArgumentMissingException thrown in file /var/www/vhosts/mydom.tld/httpdocs/typo3_src-7.6.10/typo3/sysext/extbase/Classes/Mvc/Controller/AbstractController.php in line 430. Requested URL: http://mydom.tld/1/veranstaltungen/anmeldung/`

As well as this one:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1289386765: Could not analyse class: "FluidTYPO3\Vhs\ViewHelpers\SwitchViewHelper" maybe not loaded or no autoloader? Class FluidTYPO3\Vhs\ViewHelpers\SwitchViewHelper does not exist | TYPO3\CMS\Extbase\Object\Container\Exception\UnknownObjectException thrown in file /var/www/vhosts/mydom.tld/httpdocs/typo3_src-7.6.10/typo3/sysext/extbase/Classes/Object/Container/ClassInfoFactory.php in line 37. Requested URL: http://mydom.tld/veranstaltungen/anmeldung/registration-confirm/result/60/528602ec40afb0e18f312efe05949c7a8c01a749/`

Can this relate to realurl (settings)? **EDIT** not has not, I disabled realurl an got the same error

**Comment by derhansen** [comment]
The error message states, that there is a problem with FluidTYPO3 VHS extension, which not seems to be loaded / included properly. If you use the switch-viewhelper from VHS, make sure to add the namespace to your templates.

**Comment by kludikovsky** [comment]
You are most probably right as the registration itself is done, so you are most probably right.

This is the way I have done it, and here it's the only place where I used it. 
Am I missing something here?
[RegistrationNew.txt](https://github.com/derhansen/sf_event_mgt/files/459155/RegistrationNew.txt)

**Comment by kludikovsky** [comment]
Accidentally Closed

**Comment by kludikovsky** [comment]
Solution found here:
https://github.com/FluidTYPO3/vhs/pull/1003

But this might be just partially the truth.
In my case I was using the `vhs` `case` and `switch` functions.
As those where depreciated I followed the above instructions and switched to the base function, thereby removing the need for the `vhs ViewHelpers.`

What's still unclear to me is how to properly defined the `vhs`-Namespace.
But at least my system is working again.

So for me it's closed now.
