### ISSUE TITLE
[DOC] Realurl documentation update for categories

### ISSUE THREAD

**Issue by pascaldaniela** [derhansen/sf_event_mgt#364]
### Extension version
Tell me which version of sf_event_mgt you use
1.6.1
### Short problem description

The realurl configuration in the documentation has still a table lookup to the extinct table 'tx_sfeventmgt_domain_model_category'. 
 
### Steps to reproduce
1. Check the documentation

### Expected behaviour

Maybe it works by simply replacing 'tx_sfeventmgt_domain_model_category' with 'sys_category' in the realurl config?

### Actual behaviour

I have some seamingly random issues with css not working anymore in listview and iCal download instead of detail view on event click, but this might be related to the last security update of t3 core and realurl configuration. 

### Server configuration
**TYPO3 version:**
6.2.27
**PHP version:**
5.6.26

**Comment by derhansen** [comment]
Thanks for your report. The issue is updated in development branch. Release on TER will follow soon

**Comment by TFaehrmann** [comment]
I have the same problem.
By clicking on an event in the list view the iCal download get started instead of access the detail view.

The fix above is also in my realurl conf.

Typo3 Version: 8.7.4 
sf_event_mgt Version: 2.0.0

**Comment by derhansen** [comment]
@TFaehrmann Please check, that your RealURL configuration is like in the manual - see https://github.com/derhansen/sf_event_mgt/blob/development/Documentation/ForAdministrators/Configuration/RealUrl/Index.rst

This kind of problem is always related to RealURL config.

**Comment by TFaehrmann** [comment]
Yeah problem was that some lines were missing in the init array on my RealURL configuration.
Thanks 👍

**Comment by derhansen** [comment]
You`re welcome :-)
