### ISSUE TITLE
Mail validation failed but you dont know why

### ISSUE THREAD

**Issue by schrob3000** [derhansen/sf_event_mgt#379]
### Extension version

1.6.1
### Short problem description

The registration form shows an error if mail has space at the end like "test@example.com ".
### Steps to reproduce
1. Enter mail with space at the end ("test@example.com ")
2. Submit the registration
3. You get the validation error but you dont know why
### Expected behaviour

The inputs could be trimmed and everything worked.
### Actual behaviour

You get the validation error but you dont know why.
### Server configuration

**TYPO3 version:**
7.6.11
**PHP version:**
5.6.26

**Comment by derhansen** [comment]
Possible solution: http://stackoverflow.com/questions/33657431/typo3-extbase-how-to-trim-values-before-validation-saving-objects

**Comment by OlafDoering** [comment]
Yes, a simple trim() in /Classes/Domain/Model/Registration.php in function setEmail fixed that problem.
