### ISSUE TITLE
Oops an error occured!

### ISSUE THREAD

**Issue by cfreak** [derhansen/sf_event_mgt#383]
### Extension version
Tell me which version of sf_event_mgt you use
1.7.0
### Short problem description
Wed, 02 Nov 2016 17:06:51 +0100 [ALERT] request="8da17e2b89e7b" component="TYPO3.CMS.Frontend.ContentObject.Exception.ProductionExceptionHandler": Oops, an error occurred! Code: 201611021706518aafab13 - {"exception":"ReflectionException: Class W52\\SfEventMgtCustom\\ViewHelpers\\Form\\UploadViewHelper does not exist in \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/extbase\/Classes\/Object\/Container\/ClassInfoFactory.php:35\nStack trace:\n#0 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/extbase\/Classes\/Object\/Container\/ClassInfoFactory.php(35): ReflectionClass->__construct('W52\\\\SfEventMgtC...')\n#1 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/extbase\/Classes\/Object\/Container\/Container.php(349): TYPO3\\CMS\\Extbase\\Object\\Container\\ClassInfoFactory->buildClassInfoFromClassName('W52\\\\SfEventMgtC...')\n#2 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/extbase\/Classes\/Object\/Container\/Container.php(173): TYPO3\\CMS\\Extbase\\Object\\Container\\Container->getClassInfo('W52\\\\SfEventMgtC...')\n#3 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/extbase\/Classes\/Object\/Container\/Container.php(126): TYPO3\\CMS\\Extbase\\Object\\Container\\Container->getInstanceInternal('W52\\\\SfEventMgtC...', Array)\n#4 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/extbase\/Classes\/Object\/ObjectManager.php(99): TYPO3\\CMS\\Extbase\\Object\\Container\\Container->getInstance('W52\\\\SfEventMgtC...', Array)\n#5 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/fluid\/Classes\/Core\/Parser\/TemplateParser.php(560): TYPO3\\CMS\\Extbase\\Object\\ObjectManager->get('W52\\\\SfEventMgtC...')\n#6 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/fluid\/Classes\/Core\/Parser\/TemplateParser.php(536): TYPO3\\CMS\\Fluid\\Core\\Parser\\TemplateParser->initializeViewHelperAndAddItToStack(Object(TYPO3\\CMS\\Fluid\\Core\\Parser\\ParsingState), 'event', 'form.upload', Array)\n#7 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/fluid\/Classes\/Core\/Parser\/TemplateParser.php(509): TYPO3\\CMS\\Fluid\\Core\\Parser\\TemplateParser->openingViewHelperTagHandler(Object(TYPO3\\CMS\\Fluid\\Core\\Parser\\ParsingState), 'event', 'form.upload', ' property=\"lebe...', false)\n#8 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/fluid\/Classes\/Core\/Parser\/TemplateParser.php(357): TYPO3\\CMS\\Fluid\\Core\\Parser\\TemplateParser->buildObjectTree(Array, 2)\n#9 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/fluid\/Classes\/View\/AbstractTemplateView.php(171): TYPO3\\CMS\\Fluid\\Core\\Parser\\TemplateParser->parse('\\n\\n<f:layout nam...')\n#10 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/extbase\/Classes\/Mvc\/Controller\/ActionController.php(312): TYPO3\\CMS\\Fluid\\View\\AbstractTemplateView->render()\n#11 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/extbase\/Classes\/Mvc\/Controller\/ActionController.php(176): TYPO3\\CMS\\Extbase\\Mvc\\Controller\\ActionController->callActionMethod()\n#12 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/extbase\/Classes\/Mvc\/Dispatcher.php(86): TYPO3\\CMS\\Extbase\\Mvc\\Controller\\ActionController->processRequest(Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Request), Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Response))\n#13 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/extbase\/Classes\/Mvc\/Web\/FrontendRequestHandler.php(69): TYPO3\\CMS\\Extbase\\Mvc\\Dispatcher->dispatch(Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Request), Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Response))\n#14 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/extbase\/Classes\/Core\/Bootstrap.php(206): TYPO3\\CMS\\Extbase\\Mvc\\Web\\FrontendRequestHandler->handleRequest()\n#15 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/extbase\/Classes\/Core\/Bootstrap.php(193): TYPO3\\CMS\\Extbase\\Core\\Bootstrap->handleRequest()\n#16 [internal function]: TYPO3\\CMS\\Extbase\\Core\\Bootstrap->run('', Array)\n#17 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(7310): call_user_func_array(Array, Array)\n#18 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/frontend\/Classes\/ContentObject\/UserContentObject.php(40): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->callUserFunction('TYPO3\\\\CMS\\\\Extba...', Array, '')\n#19 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(943): TYPO3\\CMS\\Frontend\\ContentObject\\UserContentObject->render(Array)\n#20 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(859): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\UserContentObject), Array)\n#21 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/frontend\/Classes\/Controller\/TypoScriptFrontendController.php(3575): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('USER', Array)\n#22 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/frontend\/Classes\/Controller\/TypoScriptFrontendController.php(3520): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->INTincScript_process(Array)\n#23 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/frontend\/Classes\/Controller\/TypoScriptFrontendController.php(3486): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->recursivelyReplaceIntPlaceholdersInContent()\n#24 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/frontend\/Classes\/Http\/RequestHandler.php(232): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->INTincScript()\n#25 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/core\/Classes\/Core\/Bootstrap.php(302): TYPO3\\CMS\\Frontend\\Http\\RequestHandler->handleRequest(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#26 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/frontend\/Classes\/Http\/Application.php(78): TYPO3\\CMS\\Core\\Core\\Bootstrap->handleRequest(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#27 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/www\/index.php(33): TYPO3\\CMS\\Frontend\\Http\\Application->run()\n#28 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/www\/index.php(34): {closure}()\n#29 {main}\n\nNext TYPO3\\CMS\\Extbase\\Object\\Container\\Exception\\UnknownObjectException: Could not analyse class: \"W52\\SfEventMgtCustom\\ViewHelpers\\Form\\UploadViewHelper\" maybe not loaded or no autoloader? Class W52\\SfEventMgtCustom\\ViewHelpers\\Form\\UploadViewHelper does not exist in \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/extbase\/Classes\/Object\/Container\/ClassInfoFactory.php:37\nStack trace:\n#0 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/extbase\/Classes\/Object\/Container\/Container.php(349): TYPO3\\CMS\\Extbase\\Object\\Container\\ClassInfoFactory->buildClassInfoFromClassName('W52\\\\SfEventMgtC...')\n#1 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/extbase\/Classes\/Object\/Container\/Container.php(173): TYPO3\\CMS\\Extbase\\Object\\Container\\Container->getClassInfo('W52\\\\SfEventMgtC...')\n#2 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/extbase\/Classes\/Object\/Container\/Container.php(126): TYPO3\\CMS\\Extbase\\Object\\Container\\Container->getInstanceInternal('W52\\\\SfEventMgtC...', Array)\n#3 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/extbase\/Classes\/Object\/ObjectManager.php(99): TYPO3\\CMS\\Extbase\\Object\\Container\\Container->getInstance('W52\\\\SfEventMgtC...', Array)\n#4 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/fluid\/Classes\/Core\/Parser\/TemplateParser.php(560): TYPO3\\CMS\\Extbase\\Object\\ObjectManager->get('W52\\\\SfEventMgtC...')\n#5 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/fluid\/Classes\/Core\/Parser\/TemplateParser.php(536): TYPO3\\CMS\\Fluid\\Core\\Parser\\TemplateParser->initializeViewHelperAndAddItToStack(Object(TYPO3\\CMS\\Fluid\\Core\\Parser\\ParsingState), 'event', 'form.upload', Array)\n#6 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/fluid\/Classes\/Core\/Parser\/TemplateParser.php(509): TYPO3\\CMS\\Fluid\\Core\\Parser\\TemplateParser->openingViewHelperTagHandler(Object(TYPO3\\CMS\\Fluid\\Core\\Parser\\ParsingState), 'event', 'form.upload', ' property=\"lebe...', false)\n#7 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/fluid\/Classes\/Core\/Parser\/TemplateParser.php(357): TYPO3\\CMS\\Fluid\\Core\\Parser\\TemplateParser->buildObjectTree(Array, 2)\n#8 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/fluid\/Classes\/View\/AbstractTemplateView.php(171): TYPO3\\CMS\\Fluid\\Core\\Parser\\TemplateParser->parse('\\n\\n<f:layout nam...')\n#9 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/extbase\/Classes\/Mvc\/Controller\/ActionController.php(312): TYPO3\\CMS\\Fluid\\View\\AbstractTemplateView->render()\n#10 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/extbase\/Classes\/Mvc\/Controller\/ActionController.php(176): TYPO3\\CMS\\Extbase\\Mvc\\Controller\\ActionController->callActionMethod()\n#11 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/extbase\/Classes\/Mvc\/Dispatcher.php(86): TYPO3\\CMS\\Extbase\\Mvc\\Controller\\ActionController->processRequest(Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Request), Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Response))\n#12 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/extbase\/Classes\/Mvc\/Web\/FrontendRequestHandler.php(69): TYPO3\\CMS\\Extbase\\Mvc\\Dispatcher->dispatch(Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Request), Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Response))\n#13 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/extbase\/Classes\/Core\/Bootstrap.php(206): TYPO3\\CMS\\Extbase\\Mvc\\Web\\FrontendRequestHandler->handleRequest()\n#14 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/extbase\/Classes\/Core\/Bootstrap.php(193): TYPO3\\CMS\\Extbase\\Core\\Bootstrap->handleRequest()\n#15 [internal function]: TYPO3\\CMS\\Extbase\\Core\\Bootstrap->run('', Array)\n#16 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(7310): call_user_func_array(Array, Array)\n#17 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/frontend\/Classes\/ContentObject\/UserContentObject.php(40): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->callUserFunction('TYPO3\\\\CMS\\\\Extba...', Array, '')\n#18 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(943): TYPO3\\CMS\\Frontend\\ContentObject\\UserContentObject->render(Array)\n#19 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(859): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\UserContentObject), Array)\n#20 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/frontend\/Classes\/Controller\/TypoScriptFrontendController.php(3575): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('USER', Array)\n#21 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/frontend\/Classes\/Controller\/TypoScriptFrontendController.php(3520): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->INTincScript_process(Array)\n#22 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/frontend\/Classes\/Controller\/TypoScriptFrontendController.php(3486): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->recursivelyReplaceIntPlaceholdersInContent()\n#23 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/frontend\/Classes\/Http\/RequestHandler.php(232): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->INTincScript()\n#24 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/core\/Classes\/Core\/Bootstrap.php(302): TYPO3\\CMS\\Frontend\\Http\\RequestHandler->handleRequest(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#25 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/typo3_src-7.6.12\/typo3\/sysext\/frontend\/Classes\/Http\/Application.php(78): TYPO3\\CMS\\Core\\Core\\Bootstrap->handleRequest(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#26 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/www\/index.php(33): TYPO3\\CMS\\Frontend\\Http\\Application->run()\n#27 \/kunden\/361491_81673\/rp-hosting\/1535\/39\/bikestore-ob.de\/www\/index.php(34): {closure}()\n#28 {main}"}

### Steps to reproduce
1. I'm trying to add the registration form on the frontend
2.
3.

### Expected behaviour
Tell me what should happen
- It should show the registration form

### Actual behaviour
Tell me what happens instead
- Oops, an error occurred! Code: 201611021706518aafab13
### Server configuration
**TYPO3 version:**
7.6.12
**PHP version:**
7.0.6

**Comment by Hativ3** [comment]
Same issue here.

Solution: Take a look at #376 and make the changes yourself.

**Comment by derhansen** [comment]
New version 1.7.1 released today. Sorry for the long delay.
