### ISSUE TITLE
[BUG] SQL error in ext_tables.sql

### ISSUE THREAD

**Issue by MartinRaitza** [derhansen/sf_event_mgt#384]
### Extension version
Tell me which version of sf_event_mgt you use 
1.7.1

### Short problem description
You have an error in your SQL syntax. 
There is a comma at at the end in CREATE TABLE tx_sfeventmgt_domain_model_customnotificationlog in your  ext_tables.sql file.

### Steps to reproduce
1. execute  ext_tables.sql in a database query

### Expected behaviour
no SQL error

### Actual behaviour
SQL error occurs

### Server configuration
**TYPO3 version:**
6.2

**PHP version:**
5.7

**Comment by derhansen** [comment]
Thanks for your report. I've fixed the error in the development branch and the next release will include the bugfix
