### ISSUE TITLE
Page tree icon will not work

### ISSUE THREAD

**Issue by cosmonoid** [derhansen/sf_event_mgt#385]
### Version 
1.7.1 

### Short problem description
Icon in the page tree is not displayed
### Steps to reproduce
1. Choose Contains plugin: Events in the behaviour tab of a pages property page and save

### Expected behaviour
The icon events-folder.png should displayed in the page tree

### Actual behaviour
The default folder icon is displayed.

### My solution 
Replacing  the deprecated SpriteManager::addTcaTypeIcon() function in ext_tables.php with:
```
/** @var \TYPO3\CMS\Core\Imaging\IconRegistry $iconRegistry */

    $iconRegistry = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Core\Imaging\IconRegistry::class);

    $iconRegistry->registerIcon(
    		'apps-pagetree-folder-contains-events',
    		\TYPO3\CMS\Core\Imaging\IconProvider\BitmapIconProvider::class,
    		[
    		'source' => 'EXT:sf_event_mgt/Resources/Public/Icons/events.gif'
    		]
    );   
    $GLOBALS['TCA']['pages']['ctrl']['typeicon_classes']['contains-events'] = 'apps-pagetree-folder-contains-events'; 
```

### Server configuration
**TYPO3 version: 7.6.11**

**PHP version: 7.0.10**

**Comment by derhansen** [comment]
You're right, the `SpriteManager::addTcaTypeIcon` is deprecated in TYPO3 7.6 but should still work (see screenshot from my TYPO3 7.6 site)

![image](https://cloud.githubusercontent.com/assets/2629896/20722220/068b2c4c-b666-11e6-8e8d-ae68452c6e16.png)

As soon as TYPO3 6.2 is deprecated, I will remove the usage of `SpriteManager::addTcaTypeIcon`

Can you try to clear all caches? This should work in TYPO3 7.6

**Comment by cosmonoid** [comment]
Unfortunatly it isn't working for me with Typo3 7.6.14, just tried with your new release:
![bildschirmfoto 2017-01-10 um 12 30 29](https://cloud.githubusercontent.com/assets/3930345/21804761/ebdfacc4-d730-11e6-9448-83feaa1bfbca.png)

Removed typo3temp/* folder, cleared all caches and even logged out and in again.

**Comment by derhansen** [comment]
The TYPO3 8.7 compatible version of the extension will use the iconRegistry - Refs #411
