### ISSUE TITLE
Registration for multiple events

### ISSUE THREAD

**Issue by tyranni** [derhansen/sf_event_mgt#389]
Hi Torben,
first of all, THANK YOU!!!! Thank you so much for this extension! Great work! :)

Nevertheless I have a question concerning the registration process. Right now it is possible to register for one event after another. I'd like to allow users to collect multiple events and register for them at once. Do you have any suggestions how I could achieve this?

Thanks again and best wishes!

**Comment by derhansen** [comment]
Hello,

thanks! Actually there is no possibility to collect registration like in a shopping cart and then register to them all at once.

Best regards
Torben

**Comment by tyranni** [comment]
Thank you, Torben!
I'll try to find a possibility to combine it with the extension "cart". Should be possible ;).
Thank you an best regards,
kerstin
