### ISSUE TITLE
RSS Feed link renders an a-tag

### ISSUE THREAD

**Issue by kimchristiansen** [derhansen/sf_event_mgt#390]
I am using version 1.8.0 with the great rss feature.

The list.xml templates renders the link as an a-tag, but it only has to render the link
`<link><f:format.htmlentities><f:link.action action="detail" arguments="{event : event}" pageUid="{settings.detailPid}">{event.title}</f:link.action></f:format.htmlentities></link>`

I changed the template to
`<link><f:uri.action action="detail" arguments="{event : event}" pageUid="{settings.detailPid}" absolute="true">{event.title}</f:uri.action></link>`

Now it works.
I also added absolute="true" because i do not use BaseUrl.

**Comment by derhansen** [comment]
Please note, that you have to use `<f:format.htmlentities>` for the URI created, so it is encoded properly. See 1fad3f0
