### ISSUE TITLE
Feature: Number of registrations

### ISSUE THREAD

**Issue by kludikovsky** [derhansen/sf_event_mgt#391]
Just s simple feature:
Display at the header of the registrations the **number of attendees**.
e.g. next to 'attendees'

PS: 
I can' mark the entry as feature suggestion/request (either intentionally or accidently)

**Comment by derhansen** [comment]
Where exactly should the label be shown? Could you paste a screenshot?

**Comment by kludikovsky** [comment]
Just aprpoximately. 

I just recognized that the request is somewhat unclear: I am talking about the Backend !
The screenshot should clarify this.

![_screen_shot_2016-12-22_113853](https://cloud.githubusercontent.com/assets/6077916/21423209/02b02cf2-c83c-11e6-9669-1ae6d6e3568d.jpg)

**Comment by derhansen** [comment]
I will use a `label_userFunc` for the label "Registrations" to add the amount of registrations (e.g. "Registrations (120)"

**Comment by kludikovsky** [comment]
Sounds good for me.

**Comment by derhansen** [comment]
I was totally wrong with `label_userFunc`. I think this one is a not easy to archive and I'll guess it will only be possible with TYPO3 7.6+

Note to myself: http://stackoverflow.com/questions/41396072/typo3-field-helpers-hints-tips/41396444

**Comment by kludikovsky** [comment]
7.6.+ sounds ok for me. I am on 7.6

Nevertheless, while writing this reply, I saw, that we don't see the wood for the trees!

The number is available at the event-overview page anyhow.

To have it on that page again would be nice, expecially when I have to enter registrations manually.

![_screen_shot_2016-12-30_200940](https://cloud.githubusercontent.com/assets/6077916/21571125/52005750-cecc-11e6-8a81-e2a88f98f667.jpg)

**Comment by derhansen** [comment]
I'm closing this issue, since the `label_userFunc` solution did'nt work as I expected and the amount of attendees is available in the admin module.

If you believe this issue should be reopened, feel free to contact me.
