### ISSUE TITLE
category and location filter

### ISSUE THREAD

**Issue by csguevara** [derhansen/sf_event_mgt#392]
### Extension version
Tell me which version of sf_event_mgt you use
1.8.0

### Short problem description
Hi, we need a Filter with AND / OR category + location. Category-Filter works fine, and in our template we can filter locations but not category and locations.

Is there a solution in in fluid template or typoscript?

Thank you!
Chris

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell me what should happen

### Actual behaviour
Tell me what happens instead

### Server configuration
**TYPO3 version:**
7.6.14

**PHP version:**
7

**Comment by derhansen** [comment]
In the list view (cached action), you can overwrite the demand object (e.g. `{overwriteDemand:{category: category, location: location}}`. 

In the search view (uncached action), you could use the `$overwriteDemand` array to filter by one or multiple criteria of your choice.

**Comment by csguevara** [comment]
Thanks a lot! It works great!

Chris
