### ISSUE TITLE
in_array() expects parameter 2 to be array, null given

### ISSUE THREAD

**Issue by Hativ3** [derhansen/sf_event_mgt#395]
### Extension version
1.8.0

### Short problem description
I'm trying to integrate my own payment method. I've created it, have set `$enableRedirect = true` and have conntected to redirectActionBeforeRedirectSaferpay signal (but the function is currently empty).

### Steps to reproduce
1. Register to event with own payment method selected
2. Open url from registration email to confirm registration
3. Browser get's redirected from confirmRegistration action to redirect action

Url is: 
> http://example.com/member-area/events/payment/?tx_sfeventmgt_pipayment%5Bregistration%5D=3&tx_sfeventmgt_pipayment%5Bhmac%5D=b63041964e6f292424343b7bc76352a309af1712&tx_sfeventmgt_pipayment%5Baction%5D=redirect&tx_sfeventmgt_pipayment%5Bcontroller%5D=Payment

### Expected behaviour
It shouldn't occur an error, own redirectActionBeforeRedirectMypaymentmethod signal should be executed (e.g. with test output in own function).

### Actual behaviour
I get the following two errors:

1.

> #1: PHP Warning: in_array() expects parameter 2 to be array, null given in /var/www/vhosts/sfl-services.live2.visiopro.eu/httpdocs/typo3_src-7.6.15/typo3/sysext/extbase/Classes/Mvc/Web/RequestBuilder.php line 243 (More information)
> 
> TYPO3\CMS\Core\Error\Exception thrown in file
> /var/www/vhosts/sfl-services.live2.visiopro.eu/httpdocs/typo3_src-7.6.15/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 111.

The line is: `if (!in_array($actionName, $allowedActionNames)) {`

Delivered arguments are: `in_array("redirect", NULL)`

It looks like `$allowedActionNames` is not set..

2.
> #1289386765: Could not analyse class: "DERHANSEN\SfEventMgt\Controller\Controller" maybe not loaded or no autoloader? Class DERHANSEN\SfEventMgt\Controller\Controller does not exist (More information)
> 
> TYPO3\CMS\Extbase\Object\Container\Exception\UnknownObjectException thrown in file
> /var/www/vhosts/sfl-services.live2.visiopro.eu/httpdocs/typo3_src-7.6.15/typo3/sysext/extbase/Classes/Object/Container/ClassInfoFactory.php in line 37.

The line is: `$classInfo = $this->getClassInfoFactory()->buildClassInfoFromClassName($className);`

### Server configuration
**TYPO3 version:** 7.6.15

**PHP version:** 7.0.10

**Comment by derhansen** [comment]
This line `DERHANSEN\SfEventMgt\Controller\Controller` looks very strange to me. 

As a first help, please check your `$signalSlotDispatcher->connect()` calls, if the first parameter always is `DERHANSEN\\SfEventMgt\\Controller\\PaymentController`.

**Comment by Hativ3** [comment]
Looks strange to me, too.

My signal connect is:
```
$signalSlotDispatcher = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('TYPO3\\CMS\\Extbase\\SignalSlot\\Dispatcher');
$signalSlotDispatcher->connect(
    'DERHANSEN\\SfEventMgt\\Controller\\PaymentController',
    'redirectActionBeforeRedirectSaferpay',
    'MyVendorPrefix\\SfEventMgtPayment\\Payment\\Saferpay',
    'getPaymentRedirectLink',
    false
);
```

My Extension is named sf_event_mgt_payment and the payment method is Saferpay.

If it helps I could send you the whole extension by mail.

**Comment by derhansen** [comment]
Yes, please send it to my email at derhansen@gmail.com

**Comment by WebsiteDeveloper** [comment]
@derhansen is there any info you can share what caused this error?

**Comment by derhansen** [comment]
I think this will not really help you, but according to all emails sent regarding this issue, reinstallation of the extension `sf_event_mgt` resolved the problem in this particular case.

**Comment by jwittorf** [comment]
Hi @derhansen, I'm basically having the same issue with TYPO3 10.4 when creating my own payment extension.

I've already tried installing the demo extension https://github.com/derhansen/sf_event_mgt_payment_demo - same result when using your Demoprovider. 

I'm using sf_event_mgt 5.9 and TYPO3 10.4, exception:

`PHP Warning: in_array() expects parameter 2 to be array, null given in /mnt/l/htdocs/t3.example/web/typo3/sysext/extbase/Classes/Mvc/Web/RequestBuilder.php` around line line 321, the `if (!in_array($actionName, $allowedActionNames))` failes because `$allowedActionNames` and `$controllerClassName` are `null`.

When debugging through the `RequestBuilder` and checking `loadDefaultValues()` I've found that the line `$configuration = $this->configurationManager->getConfiguration(ConfigurationManagerInterface::CONFIGURATION_TYPE_FRAMEWORK);` has an empty array for the `controllerConfiguration` key.

Could you please check your payment demo and the current docs for TYPO3 10.4? Thanks a lot!

**Comment by derhansen** [comment]
@jwittorf The payment demo extension is TYPO3 v11.5 only. I basically have no idea why you run into this problem and as long as you do not provide a reproducible scenario, I will not do any further analysis on the report. 

When extension sf_event_mgt, ensure to always add dependencies (`composer.json` and `ext_emconf.php`) to the main extension in your custom extension. Also make sure, that you always include the main extensions TypoScript.
