### ISSUE TITLE
[Whish] Backend: Input of registrations

### ISSUE THREAD

**Issue by kludikovsky** [derhansen/sf_event_mgt#396]
_This is actualy a minor issue, therefore not even called a feature._ 

### Extension version
1.6.1

### Short problem description
When entering registrations in the backend, the input section is at the bottom of the list, while the page is reset to the top. This makes it un-handy to enter multiple registrations.
With along list, this means that 

1. it is somtimes not clear if the add-button on top worked 
2. one has to scroll down to the bottom to be able to enter a new registration
 

### Steps to reproduce
1. take an event with several registrations
2. add a registration in the backend

### Expected behaviour
Either 
  Move the entry form for a new registration to the top of the BE-form
Or
  Position the cursor to the input form

### Actual behaviour
When entering registrations in the backend, the input section is at the bottom of the list. In addition the page is returned to the top of the registrationlist.

### Server configuration
7.6.11

**PHP version:**
5.5.6

**Comment by derhansen** [comment]
Due to restrictions in the TYPO3 core, it is not possible to move the new entry to the top.

I therefore moved the "Create new" button at the bottom (see screenshot)

![image](https://cloud.githubusercontent.com/assets/2629896/25080165/a9f3d1c4-2342-11e7-959f-a482fe3d2852.png)
