### ISSUE TITLE
[FEATURE] CSV Export of registration in UTF-8 without BOM

### ISSUE THREAD

**Issue by kludikovsky** [derhansen/sf_event_mgt#397]
### Extension version
1.6.1
### Short problem description
CSV export of registration is delievered as UTF-8 wihtout BOM
This delivers unprintable characters in Excel etc.

### Steps to reproduce
1. Export registration to csv
2.check the file format (e.g. in Notepad++)
3.

### Expected behaviour
Export file should be in UTF-8

### Actual behaviour
File is in UTF-9 without BOM

### Server configuration
**7.6.11**

**PHP version:**
5.5.6
![_screen_shot_2017-01-12_145540](https://cloud.githubusercontent.com/assets/6077916/21892476/5e706452-d8d7-11e6-8ef9-3feb75ee8176.jpg)

**Comment by derhansen** [comment]
The extension just creates a simple textfile by using TYPO3 Core functionality. I've tested several exports (locally on Mac and remote on Linux servers) and can't reproduce the problem. 

So the problem is either related to the server setup or to excel.

**Comment by kludikovsky** [comment]
OK, Das Problem ist offensichtlioch, die unterschiedliche Interpretation des BOM in den verschiedenen Anwendungen. Browser haben nach meinen Recherchen offensichtlich ein Problem damit, Excel braucht es wieder.
Eine der vielen Meldungen und Erklärungen
http://stackoverflow.com/questions/5601904/encoding-a-string-as-utf-8-with-bom-in-php

**Idee/Vorschlag**
Aus dem obigen Bericht entnehme ich, dass es nur die 3 Zeichen am Anfang der Datei braucht um alles in die entsprechenden Bahnen zu lenken. Das Statement dazu 
`$utf8_with_bom = chr(239) . chr(187) . chr(191) . $utf8_string;`

Was ist wenn dies über einen Switch, den man per TS setzen kann im Code aktiviert wird oder nicht?
Dann kann man das per Seite oder Installation ein oder ausschalten, je nachdem welche Hauptanwendung man dahinter hat.

**Comment by derhansen** [comment]
Implemented in Development Branch. Will be included in version 3.0
