### ISSUE TITLE
Page Title and Meta Description

### ISSUE THREAD

**Issue by csguevara** [derhansen/sf_event_mgt#399]
Hi Torben,
I try to change the title and the description in the detail view.

I try this typoscript for page title, but... :

[globalVar = TSFE:id = {singleviewid}]
temp.eventTitle = RECORDS
temp.eventTitle {
  source = {GP:tx_sfeventmgt_pievent|sf_event_mgt}
  source.insertData = 1
  tables = tx_sfeventmgt_domain_model_event
  conf {
    tx_sfeventmgt_domain_model_event >
    tx_sfeventmgt_domain_model_event = TEXT
    tx_sfeventmgt_domain_model_event {
      field = title
      noTrimWrap = |||
    }
  }
}

page.headerData {
10 >
10 = COA
10 < temp.eventTitle
}
[global]

Thank you for  your help!
Chris

**Comment by derhansen** [comment]
Could you try to change the condition beginning as following

```
[globalVar = TSFE:id = {$singleviewid}]
```

It seems you forgot the`$` for the constant

**Comment by csguevara** [comment]
Hi Torben,
oh yes... in the Example forgot them, but i try it with

[globalVar = TSFE:id = 35]
35 = ID where the Single Plugin

No result! 

Thx

**Comment by derhansen** [comment]
Your TypoScript also seems to contain some problems

Please try the following (untested)

```
source.data = GP:tx_sfeventmgt_pievent|event
source.intval = 1
tables = tx_sfeventmgt_domain_model_event
```

**Comment by csguevara** [comment]
Thank you Torben! It works!

**Comment by derhansen** [comment]
Glad I could help :-)

I will add a page title viewHelper in the next release of the extension and also add examples in the documentation about how to output custom tags (e.g. Meta tags) for event details
