### ISSUE TITLE
Ooopps message with Invalid Enumeration 

### ISSUE THREAD

**Issue by kludikovsky** [derhansen/sf_event_mgt#405]
### Extension version
1.8.0

### Short problem description
Oooppps error, with enumeration

I am just getting the following error: when trying to submitt a registration to sf_event_mgmt.

```
Invalid value "" for enumeration 
"TYPO3\CMS\Core\DataHandling\TableColumnType"
```
The Error log shows

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1381512761: Invalid value "" for enumeration "TYPO3\CMS\Core\DataHandling\TableColumnType" | TYPO3\CMS\Core\Type\Exception\InvalidEnumerationValueException thrown in file /var/www/vhosts/mydom.tld/httpdocs/typo3_src-7.6.16/typo3/sysext/core/Classes/Type/Enumeration.php in line 53. Requested URL: http://mydom.tld/de/veranstaltungen/anmeldung/?tx_sfeventmgt_pievent%5Bevent%5D=10&tx_sfeventmgt_pievent%5Baction%5D=saveRegistration&tx_sfeventmgt_pievent%5Bcontroller%5D=Event&cHash=af9c310b3e62ecd19cb1444e47be5a95`
Any idea what this can be and how to overcome/solve.

### Steps to reproduce
1. call the event registriation
2. enter the data and submit 
3. fail message 

The data for the registration is stored  in the backend !

### Expected behaviour
Success message and mails.

### Actual behaviour
 Oooppps message
```
Invalid value "" for enumeration 
"TYPO3\CMS\Core\DataHandling\TableColumnType"
```

### Server configuration
**TYPO3 version:** T3: 7.6.16

**PHP version:** 5,6.x

**Comment by derhansen** [comment]
I can't reproduce the problem. It works as it should on a blank TYPO3 7.6.16 installation without any further dependencies.

Please try to clear all caches. Do you have any TCA additions or do you have extended the sf_event_mgt with own fields?

**Comment by kludikovsky** [comment]
Here is a devlog from the error.

[TYPO3 Exception.pdf](https://github.com/derhansen/sf_event_mgt/files/814138/TYPO3.Exception.pdf)

**Comment by kludikovsky** [comment]
It worked alread in the past. But this was pre-update.

So far I believe that there is also an issue with realurl, therefore I removed realurl temporarely, which solve another issue with news. (also recreated before the realurl_config.

**Comment by derhansen** [comment]
I can't find any errors and sadly the devlog dump does not help. Must be some kind of configuration problem or a problem with another extension or TYPO3 setting.

All my tests are fine (both Unit/Functional and also manual testing registration with and without FE users).

Does switching back to a previous version solve the problem?

**Comment by kludikovsky** [comment]
Found a potential candidate.
Have a look.

Who can handle this?

[TYPO3 Exception.pdf](https://github.com/derhansen/sf_event_mgt/files/814212/TYPO3.Exception.pdf)

**Comment by derhansen** [comment]
There must be something wrong with your TCA. Have you extended sf_event_mgt with another extension to add own fields? If yes, check if you have overwritten TCA for feUser field.

**Comment by kludikovsky** [comment]
Not that I am aware of.       But who knows.
Have a look. I searched all feuser and fe_user

[tca [TYPO3 CMS 7.6.16].pdf](https://github.com/derhansen/sf_event_mgt/files/814827/tca.TYPO3.CMS.7.6.16.pdf)

**Comment by derhansen** [comment]
Could'nt see any problems in your TCA dump. It seems there will be some manual debugging required in this case.

**Comment by kludikovsky** [comment]
OK, I'm already trying to figure that out.
I have used the report-extension. This does not show any significatn changes to the TER. just some littel em_conf (abasically the new array notation.

Please have a look in the backtrace, and correct me if I'm wrong:

- at 38 there is the trial to create the map for an 'FrontendUser'
  - so there is nothing passed from sf_event_mgmt 
    - => is niot originated from there
 - at 39 there is an array passed
  - where does tihis come from ?


Now i have checked another thing:
I have installed the FE-Manager
Whe I call them in the backend, I get the same error.

**Comment by kludikovsky** [comment]
Problem solved!

It's been the extentsion **sav_library_example8**.

I dumped the variables at the location where the empty value arose with
`highlight_string("<?php\n\$data =\n" . var_export($tcaColumnsDefinition, true) . ";\n?>");`
and found the 'offender'

Many thanks for your help.
