### ISSUE TITLE
[TASK] Add email validation for email field in registration record

### ISSUE THREAD

**Issue by tmotyl** [derhansen/sf_event_mgt#424]
The email field in the registration record in the backend has no validation.
It should accept only correct email addresses.

**Comment by derhansen** [comment]
Added the email evaluation. TYPO3 backend shows the expected validation error (see screenshot), but saves the record anyway.

![image](https://cloud.githubusercontent.com/assets/2629896/25187582/ba932e20-2523-11e7-9715-dbd85761519d.png)
