### ISSUE TITLE
TypoScript settings missing

### ISSUE THREAD

**Issue by StefanVilbrandt** [derhansen/sf_event_mgt#432]
### Extension version
2.0.0

### Short problem description
Cannot open settings. I do not understand what static TypoScript to include.

### Steps to reproduce
1. install plugin
2. open menu "Events" in backend
3. see error message

### Expected behaviour
A menu with settings should open.

### Actual behaviour
Unable to find TypoScript settings for module. Please make sure, you have included the static TypoScript for the extension. 

### Server configuration
**TYPO3 version:**
8.7.1

**PHP version:**
7.1.1

**Comment by derhansen** [comment]
Make sure, that you have included the Static TypoScript from the extension also for the folder/subtree, where the events are stored. This message may appear, when the sysfolder with events is outside pagetree, where you have included the Static TypoScript from the extension.

Hope this helps

**Comment by StefanVilbrandt** [comment]
Like i wrote first, i don´t understand what static TypoScript i have to include. Perhaps i should add the info that i am new with Typo3.
Anyways, thanks for fast feedback.

**Comment by derhansen** [comment]
Please see attached screenshot

![image](https://cloud.githubusercontent.com/assets/2629896/25948066/55fc5550-3652-11e7-864f-e998de32e38d.png)

You find this view by opening the "Templates" module form the TYPO3 menu on the left side.

**Comment by StefanVilbrandt** [comment]
Ah, that and creating a new template finally did the trick! Before i included only sf_event_mgt itself, but not the styling. Also, it seems the template had a misconfiguration.

Thank for the help!
