### ISSUE TITLE
rte doesn't load in event description

### ISSUE THREAD

**Issue by csguevara** [derhansen/sf_event_mgt#434]
sf_event_mgt 2.0.0

Hi Torben,
after update to version 2.0.0 the rtehtmlarea doesn't load in the description field. After disable my extension (sf_event_mgt_extend) for sf_event_mgt the rte load. Before updated everything works.

The demo sf_event_mgt_extend_demo works, but after take another field inside the extension a error alert appear.

Thank you for your help,
Christian

[sf_event_mgt_extend_1.0.0_201705241906.zip](https://github.com/derhansen/sf_event_mgt/files/1026380/sf_event_mgt_extend_1.0.0_201705241906.zip)

TYPO3 7.6.18
PHP 7.0 or 7.1

**Comment by derhansen** [comment]
I can reproduce the problem, but have no idea why this happens. I have used the techniques from the sf_event_mgt_extend_demo on many sites without any problems, so I suggest to have a deeper look into sf_event_mgt_extend_demo.

**Comment by csguevara** [comment]
When i downgrade to 1.8.1 everythings works. RTE load in Description and Program Field.

**Comment by derhansen** [comment]
I added a patch in the development branch, which brings back the RTE fields in TYPO3 7.6, when the extension is extended using Single Table Inheritance. 

Please note, that this option is [deprecated](https://forge.typo3.org/projects/typo3cms-core/repository/revisions/00677ce4cc5731d6adb621d011caca7fcbd34274/entry/typo3/sysext/core/Documentation/Changelog/master/Deprecation-79341-TCARichtextConfigurationInDefaultExtrasDropped.rst) in TYPO3 V8 and will be removed in TYPO3 V9.

Using `columnsOverrides` to enable RTE fields in V7 and V8 should be the way to go, so I guess there may be a problem with `columnsOverrides` using ExtBase subclassing.

Please leave this ticket open, so I can create a scenario with 2 demo extensions to test, if this is a TYPO3 core problem.

**Comment by csguevara** [comment]
Thank you, Torben! It works!
