### ISSUE TITLE
Editor can't export CSV

### ISSUE THREAD

**Issue by webundso** [derhansen/sf_event_mgt#444]
Hi

I'm running in an error when an **editor tries to export a CSV** list. 
Message: "You are not allowed to access the given folder: "_temp_"".

The Syslog registers the following error: Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1375955684: You are not allowed to access the given folder: "_temp_" | TYPO3\CMS\Core\Resource\Exception\InsufficientFolderAccessPermissionsException thrown in file /XXX/typo3/typo3_src-7.6.19/typo3/sysext/core/Classes/Resource/ResourceStorage.php in line 760. Requested URL: http://XXX/typo3/index.php?M=web_SfEventMgtTxSfeventmgtM1&moduleToken=b0b45d615891db251523013bf30f6d42450da556&tx_sfeventmgt_web_sfeventmgttxsfeventmgtm1%5BeventUid%5D=2&tx_sfeventmgt_web_sfeventmgttxsfeventmgtm1%5Baction%5D=export&tx_sfeventmgt_web_sfeventmgttxsfeventmgtm1%5Bcontroller%5D=Administration

We **can export** the CSV as an administrator.

We are using the actual version of  sf_event_mgt. 
TYPO3: 7.6.19
PHP: 7.0

We cleared alle caches and also the cache folders and checked permission to the folders.

Thanks for your help.

Best regards

Noël Girstmair

**Comment by derhansen** [comment]
Hi,

did you check this: https://docs.typo3.org/typo3cms/extensions/sf_event_mgt/ForEditors/BackendModule/Index.html#csv-export

Best regards
Torben

**Comment by webundso** [comment]
Hi Torben,

Thanks for your reply. I did check (again) and gave the editor explicit rights for the temp-folder and now it works perfect.

Thanks again,

kind regards, Noël
