### ISSUE TITLE
Oops, an error occurred! Code: 20170626162611da567c54

### ISSUE THREAD

**Issue by alexd0001** [derhansen/sf_event_mgt#445]
Hey,

i use 2.0.0

### Short problem description

on same site with tx_news it gives sometime an error in FE - but not when i clear all caches. But later, i cant say why, it will give the -  Oops, an error occurred! Code: 20170626162611da567c54

### Steps to reproduce
1. Place tx_news list modul on same site
2. where a list-modul of sf_event_mgt
3.

### Expected behaviour
show list of tx_news and sf_event_mgt

### Actual behaviour
In Frontend  - Oops, an error occurred! Code: 20170626162611da567c54

### Server configuration
**TYPO3 version:**
8.6.x

**PHP version:**
7.1.x or so

Do you know what i mean?

best regards - alex

**Comment by derhansen** [comment]
Can you please provide logging information from the Logfile in `typo3temp/var/logs`. There should be a Logfile with the stacktrace of the exception.

**Comment by alexd0001** [comment]
Hi, this is the ceil with the stacktrace:

Tue, 27 Jun 2017 09:04:59 +0200 [ALERT] request="45e0df308cd43" component="TYPO3.CMS.Frontend.ContentObject.Exception.ProductionExceptionHandler": Oops, an error occurred! Code: 2017062709045879d83d0c - {"exception":"TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Exception\\RepositoryException: Unsupported or non-existing property name \"category\" used in relation matching. in \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/extbase\/Classes\/Persistence\/Generic\/Storage\/Typo3DbQueryParser.php:371\nStack trace:\n#0 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/extbase\/Classes\/Persistence\/Generic\/Storage\/Typo3DbQueryParser.php(220): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Storage\\Typo3DbQueryParser->parseComparison(Object(TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Qom\\Comparison), Object(TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Qom\\Selector))\n#1 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/extbase\/Classes\/Persistence\/Generic\/Storage\/Typo3DbQueryParser.php(199): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Storage\\Typo3DbQueryParser->parseConstraint(Object(TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Qom\\Comparison), Object(TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Qom\\Selector))\n#2 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/extbase\/Classes\/Persistence\/Generic\/Storage\/Typo3DbQueryParser.php(129): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Storage\\Typo3DbQueryParser->parseConstraint(Object(TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Qom\\LogicalAnd), Object(TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Qom\\Selector))\n#3 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/extbase\/Classes\/Persistence\/Generic\/Storage\/Typo3DbBackend.php(336): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Storage\\Typo3DbQueryParser->convertQueryToDoctrineQueryBuilder(Object(TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Query))\n#4 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/extbase\/Classes\/Persistence\/Generic\/Backend.php(226): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Storage\\Typo3DbBackend->getObjectDataByQuery(Object(TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Query))\n#5 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/extbase\/Classes\/Persistence\/Generic\/PersistenceManager.php(126): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Backend->getObjectDataByQuery(Object(TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Query))\n#6 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/extbase\/Classes\/Persistence\/Generic\/QueryResult.php(84): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\PersistenceManager->getObjectDataByQuery(Object(TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Query))\n#7 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/extbase\/Classes\/Persistence\/Generic\/QueryResult.php(236): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\QueryResult->initialize()\n#8 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/ViewHelpers\/ForViewHelper.php(121): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\QueryResult->rewind()\n#9 \/html\/typo3-8\/typo3temp\/var\/Cache\/Code\/fluid_template\/Event_action_list_c81bc8febe00de1f41b2d6b61a33ad4d24e5f0ff.php(494): TYPO3Fluid\\Fluid\\ViewHelpers\\ForViewHelper::renderStatic(Array, Object(Closure), Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#10 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/View\/AbstractTemplateView.php(245): Event_action_list_c81bc8febe00de1f41b2d6b61a33ad4d24e5f0ff->section_b28b7af69320201d1cf206ebf28373980add1451(Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#11 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/ViewHelpers\/RenderViewHelper.php(139): TYPO3Fluid\\Fluid\\View\\AbstractTemplateView->renderSection('main', Array, false)\n#12 [internal function]: TYPO3Fluid\\Fluid\\ViewHelpers\\RenderViewHelper->render()\n#13 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/Core\/ViewHelper\/AbstractViewHelper.php(256): call_user_func(Array)\n#14 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/Core\/ViewHelper\/AbstractViewHelper.php(245): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->callRenderMethod()\n#15 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/Core\/ViewHelper\/ViewHelperInvoker.php(78): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->initializeArgumentsAndRender()\n#16 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/Core\/ViewHelper\/AbstractViewHelper.php(501): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\ViewHelperInvoker->invoke('TYPO3Fluid\\\\Flui...', Array, Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext), Object(Closure))\n#17 \/html\/typo3-8\/typo3temp\/var\/Cache\/Code\/fluid_template\/layout_Default_a2b2fbd6fdde2fcb5838eafac2443b0271222601.php(54): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper::renderStatic(Array, Object(Closure), Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#18 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/View\/AbstractTemplateView.php(200): layout_Default_a2b2fbd6fdde2fcb5838eafac2443b0271222601->render(Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#19 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/extbase\/Classes\/Mvc\/Controller\/ActionController.php(345): TYPO3Fluid\\Fluid\\View\\AbstractTemplateView->render()\n#20 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/extbase\/Classes\/Mvc\/Controller\/ActionController.php(176): TYPO3\\CMS\\Extbase\\Mvc\\Controller\\ActionController->callActionMethod()\n#21 \/html\/typo3-8\/typo3conf\/ext\/sf_event_mgt\/Classes\/Controller\/EventController.php(222): TYPO3\\CMS\\Extbase\\Mvc\\Controller\\ActionController->processRequest(Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Request), Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Response))\n#22 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/extbase\/Classes\/Mvc\/Dispatcher.php(85): DERHANSEN\\SfEventMgt\\Controller\\EventController->processRequest(Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Request), Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Response))\n#23 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/extbase\/Classes\/Mvc\/Web\/FrontendRequestHandler.php(91): TYPO3\\CMS\\Extbase\\Mvc\\Dispatcher->dispatch(Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Request), Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Response))\n#24 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/extbase\/Classes\/Core\/Bootstrap.php(199): TYPO3\\CMS\\Extbase\\Mvc\\Web\\FrontendRequestHandler->handleRequest()\n#25 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/extbase\/Classes\/Core\/Bootstrap.php(186): TYPO3\\CMS\\Extbase\\Core\\Bootstrap->handleRequest()\n#26 [internal function]: TYPO3\\CMS\\Extbase\\Core\\Bootstrap->run('', Array)\n#27 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(6244): call_user_func_array(Array, Array)\n#28 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Classes\/ContentObject\/UserContentObject.php(41): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->callUserFunction('TYPO3\\\\CMS\\\\Extba...', Array, '')\n#29 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(820): TYPO3\\CMS\\Frontend\\ContentObject\\UserContentObject->render(Array)\n#30 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(736): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\UserContentObject), Array)\n#31 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/fluid\/Classes\/ViewHelpers\/CObjectViewHelper.php(154): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('USER', Array)\n#32 [internal function]: TYPO3\\CMS\\Fluid\\ViewHelpers\\CObjectViewHelper->render()\n#33 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/fluid\/Classes\/Core\/ViewHelper\/AbstractViewHelper.php(93): call_user_func_array(Array, Array)\n#34 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/Core\/ViewHelper\/AbstractViewHelper.php(245): TYPO3\\CMS\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->callRenderMethod()\n#35 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/Core\/ViewHelper\/ViewHelperInvoker.php(78): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->initializeArgumentsAndRender()\n#36 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/Core\/ViewHelper\/AbstractViewHelper.php(501): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\ViewHelperInvoker->invoke('TYPO3\\\\CMS\\\\Fluid...', Array, Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext), Object(Closure))\n#37 \/html\/typo3-8\/typo3temp\/var\/Cache\/Code\/fluid_template\/Standard_action_List_450490e17785ef9b39405a62b9b4a8eb1401b2e5.php(59): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper::renderStatic(Array, Object(Closure), Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#38 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/View\/AbstractTemplateView.php(245): Standard_action_List_450490e17785ef9b39405a62b9b4a8eb1401b2e5->section_62bce9422ff2d14f69ab80a154510232fc8a9afd(Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#39 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/ViewHelpers\/RenderViewHelper.php(139): TYPO3Fluid\\Fluid\\View\\AbstractTemplateView->renderSection('Main', Array, true)\n#40 [internal function]: TYPO3Fluid\\Fluid\\ViewHelpers\\RenderViewHelper->render()\n#41 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/Core\/ViewHelper\/AbstractViewHelper.php(256): call_user_func(Array)\n#42 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/Core\/ViewHelper\/AbstractViewHelper.php(245): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->callRenderMethod()\n#43 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/Core\/ViewHelper\/ViewHelperInvoker.php(78): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->initializeArgumentsAndRender()\n#44 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/Core\/ViewHelper\/AbstractViewHelper.php(501): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\ViewHelperInvoker->invoke('TYPO3Fluid\\\\Flui...', Array, Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext), Object(Closure))\n#45 \/html\/typo3-8\/typo3temp\/var\/Cache\/Code\/fluid_template\/layout_Default_91de16de6b812fb38475e2f541035c320708e96b.php(1107): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper::renderStatic(Array, Object(Closure), Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#46 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/Core\/ViewHelper\/AbstractConditionViewHelper.php(85): layout_Default_91de16de6b812fb38475e2f541035c320708e96b->{closure}()\n#47 \/html\/typo3-8\/typo3temp\/var\/Cache\/Code\/fluid_template\/layout_Default_91de16de6b812fb38475e2f541035c320708e96b.php(1603): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractConditionViewHelper::renderStatic(Array, Object(Closure), Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#48 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/ViewHelpers\/SpacelessViewHelper.php(54): layout_Default_91de16de6b812fb38475e2f541035c320708e96b->{closure}()\n#49 \/html\/typo3-8\/typo3temp\/var\/Cache\/Code\/fluid_template\/layout_Default_91de16de6b812fb38475e2f541035c320708e96b.php(1611): TYPO3Fluid\\Fluid\\ViewHelpers\\SpacelessViewHelper::renderStatic(Array, Object(Closure), Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#50 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/View\/AbstractTemplateView.php(200): layout_Default_91de16de6b812fb38475e2f541035c320708e96b->render(Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#51 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Classes\/ContentObject\/FluidTemplateContentObject.php(340): TYPO3Fluid\\Fluid\\View\\AbstractTemplateView->render()\n#52 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Classes\/ContentObject\/FluidTemplateContentObject.php(106): TYPO3\\CMS\\Frontend\\ContentObject\\FluidTemplateContentObject->renderFluidView()\n#53 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(820): TYPO3\\CMS\\Frontend\\ContentObject\\FluidTemplateContentObject->render(Array)\n#54 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(736): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\FluidTemplateContentObject), Array)\n#55 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(718): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('FLUIDTEMPLATE', Array, 'lib.contentElem...')\n#56 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Classes\/ContentObject\/CaseContentObject.php(44): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('FLUIDTEMPLATE', Array, 'list')\n#57 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(820): TYPO3\\CMS\\Frontend\\ContentObject\\CaseContentObject->render(Array)\n#58 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(736): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\CaseContentObject), Array)\n#59 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(718): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('CASE', Array, 'tt_content')\n#60 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentContentObject.php(96): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('CASE', Array, '')\n#61 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(820): TYPO3\\CMS\\Frontend\\ContentObject\\ContentContentObject->render(Array)\n#62 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(736): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\ContentContentObject), Array)\n#63 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(682): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('CONTENT', Array, '20')\n#64 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectArrayContentObject.php(41): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGet(Array)\n#65 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(820): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectArrayContentObject->render(Array)\n#66 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(736): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectArrayContentObject), Array)\n#67 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/fluid\/Classes\/ViewHelpers\/CObjectViewHelper.php(154): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('COA', Array)\n#68 [internal function]: TYPO3\\CMS\\Fluid\\ViewHelpers\\CObjectViewHelper->render()\n#69 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/fluid\/Classes\/Core\/ViewHelper\/AbstractViewHelper.php(93): call_user_func_array(Array, Array)\n#70 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/Core\/ViewHelper\/AbstractViewHelper.php(245): TYPO3\\CMS\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->callRenderMethod()\n#71 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/Core\/ViewHelper\/ViewHelperInvoker.php(78): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->initializeArgumentsAndRender()\n#72 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/Core\/ViewHelper\/AbstractViewHelper.php(501): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\ViewHelperInvoker->invoke('TYPO3\\\\CMS\\\\Fluid...', Array, Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext), Object(Closure))\n#73 \/html\/typo3-8\/typo3temp\/var\/Cache\/Code\/fluid_template\/Standard_action_DefaultSubNavRight_f41cef1eb009ae9e1bfdfdf7157c47ea46410d2f.php(1445): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper::renderStatic(Array, Object(Closure), Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#74 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/View\/AbstractTemplateView.php(245): Standard_action_DefaultSubNavRight_f41cef1eb009ae9e1bfdfdf7157c47ea46410d2f->section_62bce9422ff2d14f69ab80a154510232fc8a9afd(Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#75 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/ViewHelpers\/RenderViewHelper.php(139): TYPO3Fluid\\Fluid\\View\\AbstractTemplateView->renderSection('Main', Array, false)\n#76 [internal function]: TYPO3Fluid\\Fluid\\ViewHelpers\\RenderViewHelper->render()\n#77 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/Core\/ViewHelper\/AbstractViewHelper.php(256): call_user_func(Array)\n#78 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/Core\/ViewHelper\/AbstractViewHelper.php(245): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->callRenderMethod()\n#79 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/Core\/ViewHelper\/ViewHelperInvoker.php(78): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->initializeArgumentsAndRender()\n#80 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/Core\/ViewHelper\/AbstractViewHelper.php(501): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\ViewHelperInvoker->invoke('TYPO3Fluid\\\\Flui...', Array, Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext), Object(Closure))\n#81 \/html\/typo3-8\/typo3temp\/var\/Cache\/Code\/fluid_template\/layout_Default_09a939a0b5bece3e63d421ffd620c6d3c502fbd2.php(136): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper::renderStatic(Array, Object(Closure), Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#82 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/ViewHelpers\/SpacelessViewHelper.php(54): layout_Default_09a939a0b5bece3e63d421ffd620c6d3c502fbd2->{closure}()\n#83 \/html\/typo3-8\/typo3temp\/var\/Cache\/Code\/fluid_template\/layout_Default_09a939a0b5bece3e63d421ffd620c6d3c502fbd2.php(189): TYPO3Fluid\\Fluid\\ViewHelpers\\SpacelessViewHelper::renderStatic(Array, Object(Closure), Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#84 \/html\/typo3-8\/typo3_src-8.7.1\/vendor\/typo3fluid\/fluid\/src\/View\/AbstractTemplateView.php(200): layout_Default_09a939a0b5bece3e63d421ffd620c6d3c502fbd2->render(Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#85 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Classes\/ContentObject\/FluidTemplateContentObject.php(340): TYPO3Fluid\\Fluid\\View\\AbstractTemplateView->render()\n#86 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Classes\/ContentObject\/FluidTemplateContentObject.php(106): TYPO3\\CMS\\Frontend\\ContentObject\\FluidTemplateContentObject->renderFluidView()\n#87 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(820): TYPO3\\CMS\\Frontend\\ContentObject\\FluidTemplateContentObject->render(Array)\n#88 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(736): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\FluidTemplateContentObject), Array)\n#89 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(682): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('FLUIDTEMPLATE', Array, '10')\n#90 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Classes\/Page\/PageGenerator.php(194): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGet(Array)\n#91 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Classes\/Http\/RequestHandler.php(210): TYPO3\\CMS\\Frontend\\Page\\PageGenerator::renderContent()\n#92 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/core\/Classes\/Core\/Bootstrap.php(310): 


TYPO3\\CMS\\Frontend\\Http\\RequestHandler->handleRequest(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#93 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Classes\/Http\/Application.php(79): TYPO3\\CMS\\Core\\Core\\Bootstrap->handleRequest(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#94 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Resources\/Private\/Php\/frontend.php(23): TYPO3\\CMS\\Frontend\\Http\\Application->run()\n#95 \/html\/typo3-8\/typo3_src-8.7.1\/typo3\/sysext\/frontend\/Resources\/Private\/Php\/frontend.php(24): {closure}()\n#96 \/html\/typo3-8\/typo3_src-8.7.1\/index.php(3): require('\/html\/typo3-8\/t...')\n#97 {main}"}

**Comment by derhansen** [comment]
Thanks, this is a known error, which will be fixed within the next version.

You can use the development branch of the extension or apply the [patch](https://github.com/derhansen/sf_event_mgt/commit/89f83e5765ebfdf771ee439966d4bf5402ee05e9) manually in the meantime

**Comment by alexd0001** [comment]
Hey, when comes the next version?

thx for any answer! - thx

**Comment by derhansen** [comment]
Actually I'm still working on some bugfixes and features, so it may take some days or even weeks
