### ISSUE TITLE
[FEATURE] Check if email already registered to event

### ISSUE THREAD

**Issue by derhansen** [derhansen/sf_event_mgt#45]
For new registrations check if the given e-mail is already registered for the event. This check should be optional

**Comment by erredeco** [comment]
+1 This feature is essential. IMHO It could be more generic: it should be possible to mark every field as "unique in DB" (email = 1 by default) (I could want to add a custom field like "coupon code" and could want to check if it wasn't been used already) 
[suggestion]: the Typoscript syntax could be something like (I know, I took it from femanager ;) ):
```
 plugin.tx_sfeventmgt.registration{
  fields{
  firstname{
    required=1
    uniqueInDb = 1
    prefill = fe_users.first_name
  }   
 }
}
```

**Comment by Jpsy** [comment]
+1

**Comment by derhansen** [comment]
I decided to make this option configurable for each event directly within the event options. Only the e-mail address is checked for uniqueness for the individual event.

@erredeco I will provide a signal slot in future versions of the extension so advanced checking of additional fields can be achieved (see #215)
