### ISSUE TITLE
Add pagination in the event list template

### ISSUE THREAD

**Issue by tmotyl** [derhansen/sf_event_mgt#452]
### Extension version
development branch

### Short problem description
Event list misses pagination

**Comment by derhansen** [comment]
I decided not to include the pagination to the default list view but added a FAQ entry to the extension FAQ section: see https://docs.typo3.org/typo3cms/extensions/sf_event_mgt/Faq/Index.html#how-can-i-add-pagination-to-the-listview

**Comment by tmotyl** [comment]
I see. Can you share why?

**Comment by derhansen** [comment]
Generally so the user can decide, if pagination is needed or not and also to keep the configuration options lower (no pagination settings in TS or Flexform).
