### ISSUE TITLE
Duplicated registrations possible

### ISSUE THREAD

**Issue by tmotyl** [derhansen/sf_event_mgt#455]
### Extension version
development branch

### Short problem description
Currently user can register multiple times to the same event.
At last a check for unique emails should be provided.

**Comment by derhansen** [comment]
There is an option in the registration settings for each event (see screenshot)

![image](https://user-images.githubusercontent.com/2629896/28302225-65f48616-6b8c-11e7-8e96-8820f6f3cbdb.png)

The setting must be activated for each event individually. If this is required on a global basis, I would recommend to set a default value for the field using `TCEFORM`

**Comment by tmotyl** [comment]
right, I somehow missed the checkbox, thanks for help
