### ISSUE TITLE
[FEATURE] Add additional Fields for Geo-Coordinates

### ISSUE THREAD

**Issue by WebsiteDeveloper** [derhansen/sf_event_mgt#458]
Would be nice to have geo-coordinates as a core feature.

**Comment by derhansen** [comment]
Could you tell me, where exactly? Did you notice, that longitude and latitude are available for event locations?

**Comment by WebsiteDeveloper** [comment]
Well i didn't notice that that would be all i want :)

Another thing i noticed:
It seems like you cant add a new Location on the fly when you want to edit/create an event
![image](https://user-images.githubusercontent.com/2150814/28361747-05a0c56a-6c7a-11e7-8add-155ada8bca74.png)

**Comment by WebsiteDeveloper** [comment]
Would that be possible?

**Comment by tmotyl** [comment]
@WebsiteDeveloper you can easily change the location field type to inline
just put a file in with my_extension/Configuration/TCA/Overrides/tx_sfeventmgt_domain_model_event.php

```
<?php
defined('TYPO3_MODE') or die();

$GLOBALS['TCA']['tx_sfeventmgt_domain_model_event']['columns']['location'] = [
    'exclude' => 0,
    'label' => 'LLL:EXT:sf_event_mgt/Resources/Private/Language/locallang_db.xlf:tx_sfeventmgt_domain_model_event.location',
    'config' => [
        'type' => 'inline',
        'foreign_table' => 'tx_sfeventmgt_domain_model_location',
        'size' => 1,
        'minitems' => 0,
        'maxitems' => 1,
        'default' => 0,
    ],
];
```

**Comment by WebsiteDeveloper** [comment]
@tmotyl thanks that worked.
But now the user always has to create a new record and isn't able to use a previously added location.
Anyway that is possible?

I'm still a bit new to typo3 :)
