### ISSUE TITLE
[FEATURE] Record Review

### ISSUE THREAD

**Issue by WebsiteDeveloper** [derhansen/sf_event_mgt#460]
One Feature i need is to have Events marked for review
and stay locked (eg. not showing in frontend lists etc.) until the get reviewed and unlocked
by an admin (preferably the usergroup with the permissions to unlock would be configurable)

**Comment by tmotyl** [comment]
You can use the built in "hidden" field for that. 
And adjust configuration in the way that:
- record is hidden by default
- only certain user group has access to change this field

**Comment by derhansen** [comment]
Closing issue, please follow the suggestion by @tmotyl
