### ISSUE TITLE
error on getting organisator email address

### ISSUE THREAD

**Issue by matin73** [derhansen/sf_event_mgt#466]
typo3 7.6 
ext. version  1.4.1 
i get an error if  i activate checkbox for sending email to organistor on registration:

Fatal error: Call to undefined method TYPO3\CMS\Extbase\Persistence\ObjectStorage::getEmail()  in typo3conf/ext/sf_event_mgt/Classes/Service/NotificationService.php on line 250 

martin

**Comment by derhansen** [comment]
Extension version 1.4.1 is pretty old. Please update to the latest version 2.0.0 and check, if the error still occurs.

**Comment by derhansen** [comment]
I'm closing this issue. Feel free to contact me, if you have any additional problems/questions
