### ISSUE TITLE
[BUG] Pagination in Backend not working properly after search

### ISSUE THREAD

**Issue by derhansen** [derhansen/sf_event_mgt#485]

**Comment by philippmaurer** [comment]
We encountered this bug in our event backend view, where the search is not kept upon switiching the page.
To reproduce the bug it is necessary to trigger a search, that results multiple pages of content, like seen on thre first screenshot.

![grafik](https://user-images.githubusercontent.com/10925094/32830681-5182fab4-c9f6-11e7-9229-350c7f29c3f3.png)

After the page is loaded, load the next page (»)[Or any other button that triggers a reload. Even the refresh button]. On that page, neither the search query is kept, nor is the result filtered. This can be seen on the second screenshot, in which a result from the first page appears again (blue underlined on both screenshots).

![grafik](https://user-images.githubusercontent.com/10925094/32831346-4a97a504-c9f8-11e7-8b0b-8988eba9d870.png)

**Comment by derhansen** [comment]
`f:be.widget.paginate` does not support additional GET/POST parameters. Backend module need to be refactored, so filter data is stored in BE user session.
