### ISSUE TITLE
Enable possibility to set event title and/or user name to mail notification title

### ISSUE THREAD

**Issue by Hobokens** [derhansen/sf_event_mgt#488]
If you have a conference with many course offers it would be nice for user and organizer to receive notification mails with titles as informative as possible.
Regards
Hobokens
PS: Thanks for the really great extension.

**Comment by derhansen** [comment]
Duplicate to #403

**Comment by derhansen** [comment]
Implemented in development branch

Both the `{event}` and the `{registration}` object is available, so you can set the event title and all data from the registration (e.g. firstname and lastname)

**Comment by Hobokens** [comment]
thanks for the enhancement.
