### ISSUE TITLE
[FEATURE] Price-Options to chose

### ISSUE THREAD

**Issue by ULinn** [derhansen/sf_event_mgt#492]
Option to have several prices to chose, i.e. reduced price for students, special price for members, etc.
Each option needs a Titel and a Price and should be selectabel in the registration form.
Only one option can be used (radio-button) and each option contains the complete price, so nothing has to be calculated.

**Comment by derhansen** [comment]
Did you see, that it is already possible to create one or multiple price options for each event? There are several Getters (e.g. `getActivePriceOptions` or `getCurrentPrice`)  in the event model, which can be used to retrieve the configured price options or the event price in Fluid. 

The only thing that is missing is the possibility to add a title to the price option. Would adding a title field suit your requirements?

**Comment by derhansen** [comment]
No feedback for over 30 days, so I'm closing this issue. If you think that this is the wrong decision, feel free to create a new issue with relation to this one.
