### ISSUE TITLE
[FEATURE] title of event in title tag and indexed_search

### ISSUE THREAD

**Issue by SylviaMoschner** [derhansen/sf_event_mgt#499]
### Extension version
2.1.0

### Short problem description
The title of the event is not automatically set in the title-Tag and the indexed_search-Title

### Steps to reproduce
1. Open detail view of any event. Check title tag.
2. Add events to indexed_search.
3. Search for event.

### Expected behaviour
For SEO reasons the title of the event should be included in the title tag. The search would be much user friendly if the title of the event would be the actual title of the result.

### Actual behaviour
Title is the standard title of detail page. Result title is the standard title of the page.

### Server configuration
**TYPO3 version:**
8.7.8
**PHP version:**
7.0.22

### Solution
Add something like the following 2 lines to the function of the detail action:
$GLOBALS['TSFE']->page['title'] = "Here the title to display in the title tag";
$GLOBALS['TSFE']->indexedDocTitle = "Here the title to display in the indexed_search results";

There is a workaround to use in the TS-Setup but this would be way more convenient.

**Comment by derhansen** [comment]
Feature will be available in the upcoming release
