### ISSUE TITLE
red marker for a mandatory field is always shown

### ISSUE THREAD

**Issue by Hobokens** [derhansen/sf_event_mgt#504]
### Extension version
sf_event_mgt_2.1.0

### Short problem description
Even if a field is not mandatory the small red marker at the end of the label is shown.

### Expected behaviour
The red marker shouldn't be shown if a field is not mandatory.

### Server configuration
**TYPO3 version: 8.7.9.

**PHP version: 7.1.

Regards
Hobokens

**Comment by derhansen** [comment]
I could not find any red markers for field labels in the default templates of the extension. Do you use a custom template for event registration?

**Comment by Hobokens** [comment]
I'm sorry, you're right. The default css doesn't have a red marker. It must be personal css that I have forgotten.
BTW does the extension have a marker by its own to show in the frontend that a field is mandatory?

**Comment by Hobokens** [comment]
I solved it by css so the issue can be closed.
