### ISSUE TITLE
[BUG] ical error on disabled events

### ISSUE THREAD

**Issue by medarob** [derhansen/sf_event_mgt#511]
### Extension version
2.1

### Short problem description
When I disable an event I get this error in the backend protocol:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1297933823: Object of type DERHANSEN\SfEventMgt\Domain\Model\Event with identity "10003" not found. | TYPO3\CMS\Extbase\Property\Exception\TargetNotFoundException thrown in file /var/www/typo3/typo3_src-7.6.23/typo3/sysext/extbase/Classes/Property/TypeConverter/PersistentObjectConverter.php in line 223. Requested URL: [domain]/veranstaltungen/dummy-site/ical/[name_of_the_event]/ 

### Steps to reproduce
1.
2.
3.

### Expected behaviour
No error on disabled events.

### Actual behaviour
error in log protocol

maybe a web crawler is responsible or someone who still has the link for the (disabled event with the) ical file tried to download the file

### Server configuration
**TYPO3 version:**
7.6.23

**PHP version:**
7.1

**Comment by derhansen** [comment]
The bug has been fixed with 749b9a5
