### ISSUE TITLE
[TASK] Use  own category class in event model

### ISSUE THREAD

**Issue by derhansen** [derhansen/sf_event_mgt#517]

**Comment by mediaessenz** [comment]
Maybe exchange the current code inside `Configuration/TCA/Overrides/tx_sfeventmgt_domain_model_event.php` to:
```
<?php
\TYPO3\CMS\Core\Category\CategoryRegistry::getInstance()
    ->add('sf_event_mgt', 'tx_sfeventmgt_domain_model_event', 'category', [
        'label' => 'LLL:EXT:sf_event_mgt/Resources/Private/Language/locallang.xlf:tx_sfeventmgt_domain_model_event.category',
        'exclude' => false
    ]);
```

**Comment by derhansen** [comment]
The main purpose of this ticket was to remind me about replacing the category class in the domain model right after the #512, which is done now.

Are there any advantages about using `\TYPO3\CMS\Core\Category\CategoryRegistry::getInstance()->add`? `\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::makeCategorizable` does the same, but also logs an error, if the key has already been registered.

**Comment by mediaessenz** [comment]
I can't remember where I got this way from and your way seems to be the recommended:
https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Categories/Index.html
Sorry for the confusion, just forget my comment and leave it like it is.

**Comment by derhansen** [comment]
No problem, I'll close the issue :-)
