### ISSUE TITLE
[BUG] Wrong naming of partials - Registrations/Field

### ISSUE THREAD

**Issue by linnearad** [derhansen/sf_event_mgt#532]
### Extension version
3.0.0

### Short problem description
When adding custom field to registration the registration form create error. Reason for error is that partials is named Index.htmt, Check.html ... but {field.type} value in Registration.htm is index, check etc. As defined in FieldType.php (uppercase/lowercase)

Works with changing first letter to lowercase in partials.

### Steps to reproduce
1. Create a custom regostration field on an event.
2. Try to register to that event.

### Expected behaviour
Registration form should open,

### Actual behaviour
Error message. Part of message from log
`Tue, 17 Apr 2018 09:19:25 +0000 [ALERT] request="79baa3721cd17" component="TYPO3.CMS.Frontend.ContentObject.Exception.ProductionExceptionHandler": Oops, an error occurred! Code: 2018041709192522ad2f93 - {"exception":"TYPO3Fluid\\Fluid\\View\\Exception\\InvalidTemplateResourceException: The Fluid template files \"\/www\/efaktor\/sites\/efaktor001.efk-p-enterp01.osl.basefarm.net\/www\/typo3conf\/ext\/lr_mysite\/Resources\/Private\/Event\/Partials\/Registration\/Fields\/input.html\", \"\/www\/efaktor\/sites\/efaktor001.efk-p-enterp01.osl.basefarm.net\/www\/typo3conf\/ext\/lr_mysite\/Resources\/Private\/Event\/Partials\/Registration\/Fields\/input\", \"\/www\/efaktor\/sites\/efaktor001.efk-p-enterp01.osl.basefarm.net\/www\/typo3conf\/ext\/sf_event_mgt\/Resources\/Private\/Partials\/Registration\/Fields\/input.html\", \"\/www\/efaktor\/sites\/efaktor001.efk-p-enterp01.osl.basefarm.net\/www\/typo3conf\/ext\/sf_event_mgt\/Resources\/Private\/Partials\/Registration\/Fields\/input\" could not be loaded.
`
### Server configuration
**TYPO3 8.7**

**PHP 7.0:**

**Comment by derhansen** [comment]
Thanks for your report. The issue will be fixed and released today evening

**Comment by linnearad** [comment]
That was fast!
