### ISSUE TITLE
Call to a member function getRegistrationFields() on null

### ISSUE THREAD

**Issue by blueamerican** [derhansen/sf_event_mgt#533]
### Extension version
3.0

### Short problem description
when submitting a registration form, i geht the error:
Call to a member function getRegistrationFields() on null

```
Error thrown in file
/kunden/typo3conf/ext/sf_event_mgt/Classes/Validation/Validator/RegistrationFieldValidator.php in line 33.

24 DERHANSEN\SfEventMgt\Validation\Validator\RegistrationFieldValidator::isValid(DERHANSEN\SfEventMgt\Domain\Model\Registration)


/kunden/typo3cms/typo3_src-8.7.1/typo3/sysext/extbase/Classes/Validation/Validator/AbstractValidator.php:

00099:         $this->result = new \TYPO3\CMS\Extbase\Error\Result();
00100:         if ($this->acceptsEmptyValues === false || $this->isEmpty($value) === false) {

00101:             $this->isValid($value);

00102:         }
00103:         return $this->result;
```

### Server configuration
**TYPO3 version:** 
8.7.12

**PHP version:**
7.0.28

**Comment by derhansen** [comment]
The issue has been fixed in version 3.0.1 (https://github.com/derhansen/sf_event_mgt/releases/tag/3.0.1), which has been released some minutes ago. 

The new version is available on packagist and on TER (should be visible in max 15 minutes)
