### ISSUE TITLE
Unresolvable composer dependencies version 3.0.1 and TYPO3 7.6

### ISSUE THREAD

**Issue by linnearad** [derhansen/sf_event_mgt#535]
### Extension version
3.0.1

### Short problem description
3.0.1 can't be installed through composer when TYPO3 version is 7.6. The reason are the require of nimut/typo3-complete:^8.7.

Not a big problem - and there are probably few 7.6 installation with composer. But a bit iritating

### Steps to reproduce
1.  Try to install sf_event_mgt with "composer require derhansen/sf_event_mgt:^3.0"

### Expected behaviour
Should have been downloaded and installed as sf_event_mgt is set to work with TYPO3 7.6

### Actual behaviour
 Your requirements could not be resolved to an installable set of packages.

### Server configuration
**7.6.27:**

**7.0.28:**

**Comment by derhansen** [comment]
Agree, this is wrong and should not be part of in the require section at all, since it is only required for test automation. I'lll update it within the next release

**Comment by derhansen** [comment]
Closes with 6f9196bb02de5ae03a6a349a2c75ea2f18920d4d
