### ISSUE TITLE
Registration: crdate remains empty

### ISSUE THREAD

**Issue by Hobokens** [derhansen/sf_event_mgt#537]
Hi Thorben,
### Extension version
Tell me which version of sf_event_mgt you use
I use sf_event_mgt v3.0.1

### Short problem description
When a new fe_user registers for an event the field crdate in table  tx_sfeventmgt_domain_model_registration remains empty
### Steps to reproduce
Just register a new frontend_user

### Expected behaviour
The field should be filled as it was in version 2.1

### Actual behaviour
Tell me what happens instead

### Server configuration
**TYPO3 version:**
TYPO3 8.7.13
**PHP version:**
7.1.9

Regards Hobokens

**Comment by derhansen** [comment]
I tried to reproduce the problem with no success. The field crdate ist usually set by the TYPO3 core datahandler and sf_event_mgt does not modify/set any field value for that field.

Can you reproduce the problem on several TYPO3 websites?

**Comment by Hobokens** [comment]
Thanks for your fast reaction. I will try to reproduce the problem on another TYPO3 website.

**Comment by Hobokens** [comment]
I checked it again and found out that my own extension to extend sf_event_mgt caused the problem. 
Sorry for the false 'alarm' and thanks for the great extension.
