### ISSUE TITLE
Events are not found via indexed_search and crawler extensions

### ISSUE THREAD

**Issue by medarob** [derhansen/sf_event_mgt#538]
Hi Torben

I have a question about the event extension in combination with indexed_search and the crawler extension. Maybe you can help me? :-)

### Extension version
3.0.1

### Short problem description
I use indexed_search with the crawler extension but the event detail pages or registration pages are not found. The indexed_search tags `<!--TYPO3SEARCH_begin--><!--TYPO3SEARCH_end-->` are already included but that does not seems to be enough. So, the question is what could I have missed and should it work out of the box or is this the normal behaviour?

### Steps to reproduce
1.
2.
3.

### Expected behaviour
When I enter the name of an event in the indexed_search form I would like to see it in the search results.

### Actual behaviour
Event is not shown.

### Server configuration
**TYPO3 version: 7.6.27

**PHP version: 7.0

**Comment by derhansen** [comment]
The indexed search indexing (on page request) ist working as it should. Sadly, I'm  never worked with ext:crawler, so I can't help you with the issue. But since "normal" indexing works, you problem may be releated to a configuration issue.

**Comment by derhansen** [comment]
Closing, no feedback
