### ISSUE TITLE
BE error: TYPO3 Exception: #1298012500: Required argument "registration" is not set

### ISSUE THREAD

**Issue by medarob** [derhansen/sf_event_mgt#544]
### Extension version
v3.0.1

### Short problem description

In the BE the following error messages are shown for several courses:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1298012500: Required argument "registration" is not set for DERHANSEN\SfEventMgt\Controller\EventController->saveRegistration. | TYPO3\CMS\Extbase\Mvc\Controller\Exception\RequiredArgumentMissingException thrown in file /var/www/typo3/typo3_src-7.6.27/typo3/sysext/extbase/Classes/Mvc/Controller/AbstractController.php in line 430. Requested URL: ****/kursanmeldung/register-save/result/reguid/hmac/[NameOfTheCourseWebseite]/ 

### Steps to reproduce
Not sure how to reproduce this... this error is shown in the BE after the Update to v3.

### Expected behaviour
No error message in BE

### Actual behaviour
The registration seems to work but this error message is new.. do you have any idea what could cause it?
We also have a customized template, maybe we forgot something to adapt...

### Server configuration
TYPO3 version: 7.6.27

PHP version: 7.0

**Comment by derhansen** [comment]
Strange that the error is shown in the backend, since it for sure is generated in the frontend. 

Please update first to version 3.0.2 and next clear all TYPO3 caches. If the error remains, please try to disable all custom templates and try to use the default one. If the default work, you should try to adjust changes to your own template.

If that does not work, feel free to provide additional feedback

**Comment by derhansen** [comment]
I'll close this issue now. Feed free to re-open the issue, if you still have problems.

**Comment by gautamsinh** [comment]
Hii
I have also faced this issue in the frontend

**Tried version 3.0.2 to 3.0.6**
After Registration, I face this issue!!

https://docs.typo3.org/typo3cms/extensions/sf_event_mgt/Faq/Index.html#how-does-the-payment-process-work

**Comment by derhansen** [comment]
The error occurs, when the registration argument is not set correct in your form. See https://github.com/derhansen/sf_event_mgt/blob/master/Resources/Private/Templates/Event/Registration.html#L92 for details on how the form must be setup.

Please always check first, if the error occurs with the default templates of the extension. If not, you have an error in your custom template.

I just tested the registration on a fresh TYPO3 8.7 website with the default templates and everything works as expected, so I suggest, that you check your template "Registration.html" for the event argument mentioned above.
