### ISSUE TITLE
How can I make "Additional registration fields" work?

### ISSUE THREAD

**Issue by jooler** [derhansen/sf_event_mgt#545]
### Extension version
Tell me which version of sf_event_mgt you use
3.0.2

### Short problem description
`SQL error: 'Field 'settings' doesn't have a default value' (tx_sfeventmgt_domain_model_registration_field:NEW5af0965b62f1d580088084)`

### Steps to reproduce
1.install typo3 8.7.13
2.install sf_event_mgt with zip package and enable it
3.make a new folder in pagetree and and a new event into it
4.under registration fields tab click "create new" and fill it
5.click save and get error -> "tx_sfeventmgt_domain_model_registration_field:NEW5af0965b62f1d580088084"

### Expected behaviour
Tell me what should happen

### Actual behaviour
Tell me what happens instead

### Server configuration
**TYPO3 version:**
8.7.13
**PHP version:**
7.2

**Comment by derhansen** [comment]
Thanks for your feedback. I'm pretty sure the error occurs due to SQL Strict mode.

Can you try to apply the following patch and after that, do a "DB Compare" in the install tool?

```
Index: ext_tables.sql
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- ext_tables.sql	(revision 97c02fecb892481775e684fee276cb20d2700eaa)
+++ ext_tables.sql	(date 1525759350000)
@@ -142,7 +142,7 @@
 	pid int(11) DEFAULT '0' NOT NULL,
 
 	event int(11) unsigned DEFAULT '0' NOT NULL,
-	details text NOT NULL,
+	details text,
 	emails_sent int(11) DEFAULT '0' NOT NULL,
 
 	tstamp int(11) unsigned DEFAULT '0' NOT NULL,
@@ -383,9 +383,9 @@
 	title varchar(255) DEFAULT '' NOT NULL,
 	type varchar(255) DEFAULT '' NOT NULL,
 	required tinyint(4) unsigned DEFAULT '0' NOT NULL,
-	placeholder text NOT NULL,
-	default_value text NOT NULL,
-	settings text NOT NULL,
+	placeholder text,
+	default_value text,
+	settings text,
 	event int(11) unsigned DEFAULT '0' NOT NULL,
 
 	tstamp int(11) unsigned DEFAULT '0' NOT NULL,
@@ -428,7 +428,7 @@
 	uid int(11) NOT NULL auto_increment,
 	pid int(11) DEFAULT '0' NOT NULL,
 
-	value text NOT NULL,
+	value text,
 	value_type int(11) unsigned DEFAULT '0' NOT NULL,
 	field int(11) unsigned DEFAULT '0' NOT NULL,
 	registration int(11) unsigned DEFAULT '0' NOT NULL,
```

Generally, the patch removes the `NOT NULL` definitions for `text` fields in the database. 

It would be great, if you could provide feedback, if the patch resolves your problem, so I can publish a new version soon.

**Comment by jooler** [comment]
@derhansen 
thanks for your reply,
but I'm not a developer, so I send an email , please check it, maybe you can do it .
