### ISSUE TITLE
[FEATURE] Add detail view for user registrations

### ISSUE THREAD

**Issue by derhansen** [derhansen/sf_event_mgt#555]
Add a detail view for user registrations and make sure, only logged in user can view own registrations

**Comment by ckaz** [comment]
Hello, many thanks for your extension. I wondered if my question was related to this feature request: Would it be possible to include information as to whether a user is on the waitlist or on the "normal" registration list in the FE user registration view? 
My best! Claas

**Comment by derhansen** [comment]
Yes, this would automatically be possible, since the registration object already holds this information (`{registration.waitlist}`).

If you require this information already now (e.g. show it in list view for user registrations), just use `{registration.waitlist}` in your Fluid templates.

**Comment by ckaz** [comment]
Wow, that's great. Many thanks for the hint!
