### ISSUE TITLE
Missing namespace header in /Partials/Registration/Fields/Radio.html

### ISSUE THREAD

**Issue by ulidoh** [derhansen/sf_event_mgt#556]
### Extension version
3.0.4

### Short problem description
In Partials/Registration/Fields/Radio.html there the namespace header is missing. This results into a namespace exception if you open a registration page with custom registration fields of type "Radiobutton" added.

### Steps to reproduce
1. Create registration for event
2. add registration field of type "Radiobutton"
3. open the registration page

### Expected behaviour
The page should open with no errors displaying the registration form with added radiobutton(s)

### Actual behaviour
Uncaught Typo3 exception displayed: Namespace could not be resolved. This exception should never be thrown

### Server configuration
**TYPO3 version:**
7.6.26

**PHP version:**
5.5.38

### Solution: 
Just add the following namespace header to the top of the file Radio.html

`<html xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers"
      xmlns:e="http://typo3.org/ns/DERHANSEN/SfEventMgt/ViewHelpers"
      data-namespace-typo3-fluid="true">`

**Comment by derhansen** [comment]
Thanks for your feedback. The issue is already fixed in the dev development version (8a17e5906266e80fda731a0451a707f02cc3e4e1). The public release may still take some time, since I want to include #524 in the new release.

**Comment by ulidoh** [comment]
Thanks for your quick response (and your great plugin).
I didn't check the dev version before posting. Next time ;-)
