### ISSUE TITLE
[FEATURE] Add slot in cancellation of registration

### ISSUE THREAD

**Issue by derhansen** [derhansen/sf_event_mgt#560]
If a user cancels a registration, a developer should be able to connect to a slot in order to move registrations on the waitlist up in the list of confirmed registrations.

**Comment by WebsiteDeveloper** [comment]
@derhansen Are you currently working on this?
Because otherwise i would add this and put up a pull request.

On the other hand have you thought about making the waitlist move up behavior a default feature?

**Comment by derhansen** [comment]
Will also add this feature to the next version.

The move-up feature will not be a default, because requirements may be different depending on the current scope (e.g. move-up by registration date, by self defined priority or something completely different).
