### ISSUE TITLE
[FEATURE] Add singleEvent flexform setting for detail page

### ISSUE THREAD

**Issue by derhansen** [derhansen/sf_event_mgt#568]
Enable the possibility to show a configurable (through flexform) event on the detail page

**Comment by PeaceSfiSh** [comment]
Should be possible for the registration form too. Thanks a lot.

**Comment by derhansen** [comment]
@PeaceSfiSh Could you explain why this should be possible or what your use case is for this feature?

**Comment by derhansen** [comment]
Added in a02e064
