### ISSUE TITLE
[FEATURE] Add JSON-LD output for events

### ISSUE THREAD

**Issue by derhansen** [derhansen/sf_event_mgt#572]
See https://developers.google.com/search/docs/data-types/event

Can directly be added to detail view using a partial.

**Comment by christophlehmann** [comment]
Great. exactly what we need 👍 Can we merge it? :-)

**Comment by derhansen** [comment]
Feed free to use the PR and modify output to your needs (e.g. date does not include time - may be required in many cases). 

I'll need some more time to evaluate the topic and to decide, if the partial from the PR will be included by default or if it will be added as part of the documentation.
