### ISSUE TITLE
[FEATURE] Allow different sorting of Events in Backend View

### ISSUE THREAD

**Issue by WebsiteDeveloper** [derhansen/sf_event_mgt#578]
### Extension version
3.0.5

### Short problem description
One client of ours would like the Sorting changed so that the most recent events are sorted to the top

### Expected behaviour
Some ability to change the sorting behavior

### Actual behaviour
Sorting Behavior only changable via Class Modification:
```
sf_event_mgt/Classes/Domain/Repository/EventRepository.php
    protected $defaultOrderings = [
        'startdate' => \TYPO3\CMS\Extbase\Persistence\QueryInterface::ORDER_DESCENDING,
    ];
```

### Server configuration
**TYPO3 version:**
8.7.x

**PHP version:**
7.2

**Comment by derhansen** [comment]
What do you think of, if I add a "Sort by" and "Sort order" field to the admin module?

**Comment by WebsiteDeveloper** [comment]
@derhansen I would say that would be even better if it's possible to then change the default sorting / sort order
