### ISSUE TITLE
[TASK] Add TYPO3 v9 compatibility

### ISSUE THREAD

**Issue by derhansen** [derhansen/sf_event_mgt#584]
**Note:** I will work on this issue in december 2018, so you can expect a v9 compatible version in either december 2018 or january 2019

* Make extension compatible with TYPO3 9.5
* Drop support for TYPO3 7.6
* TYPO3 7.6 deprecations #493

**Comment by stephangrass** [comment]
Hi, any idea when you can provide a v9 compatible version?

**Comment by derhansen** [comment]
Development branch already has some v9 compatibility and I try to get as much time as possible for the needed changes. Sadly this is currently not really easy during to heavy customer workload, so a release can not be expected before march 2019

**Comment by stephangrass** [comment]
Ok, thanks!
