### ISSUE TITLE
[BUG] copying records fail with mysql strict mode

### ISSUE THREAD

**Issue by colorcube** [derhansen/sf_event_mgt#588]
### Extension version

3.0.6

TYPO3 version: 8.7

### Short problem description

When (newer) mysql or mariadb is running in strict mode, copying a record in the backend fail with:

SQL error: 'Incorrect integer value: '' for column 'l10n_parent' at row 1' (tx_sfeventmgt_domain_model_event:NEW5bd6f2e75c009955287075)

### Solution

Add to TCA for field 'l10n_parent' a default value on all tables like so:

        'l10n_parent' => [
            'displayCond' => 'FIELD:sys_language_uid:>:0',
            'exclude' => 1,
            'label' => 'LLL:EXT:lang/locallang_general.xlf:LGL.l18n_parent',
            'config' => [
                'type' => 'select',
                'renderType' => 'selectSingle',
                'items' => [
                    ['', 0],
                ],
                'default' => 0, # FIX

**Comment by derhansen** [comment]
Thanks for the report. Will fix the problem in the next version.
