### ISSUE TITLE
Using metaseo sitemap some links (e.g. cancelRegistration) must be excluded

### ISSUE THREAD

**Issue by mmunz** [derhansen/sf_event_mgt#597]
### Extension version
3.0.5 (extended with own extension)

### Short problem description
When using the third party extension EXT:metaseo (other sitemap generators too probably) a rather funny problem is created: personalized links like for the cancelRegistration action are written to the sitemap including all params and hmac. You probably already guessed what happens next: A website crawler comes it's way, indexes the URL and the user registration is cancelled.

### Steps to reproduce
1. install EXT:metaseo and make sure sitemap works (especially don't disable cache)
2. create an event which has "Cancel registration" enabled
3. Register your user for the event
4. See how the cancelRegistration-Link is added to the sitemap

### Expected behaviour
Personalized Links should never be written to any sitemap.

### Actual behaviour
see above

Additionaly this problem might also arise if a clever email provider (which might happen to also run a search engine) decides to read users emails and crawl all contained URLs.

### Options for fixes

1. Extend documentation to make integrators aware of this problem and provide solutions like blacklist config for metaseo
2. Find another way to prevent these links from being written to the sitemap.
    Ideas:
    - might adding nofollow on the link already be enough?
    - don't execute actions directly by clicking the link but require a second step, e.g.  provide a button/form 

### Server configuration
**TYPO3 version:** 8.7

**PHP version:** 7.1

**Comment by derhansen** [comment]
In customer projects I had some "funny" effects with the extension `metaseo` too. Obviously, it also added various URLs to the index, that were generated by crawlers/website scanners (e.g. potential SQL Injection attempts).

You could try to disable "Include in Search" on the registration page. Maybe the extension respects this setting and will not include the site in the sitemap any more. But I did not dig deeper into the problem.

I will extend the documentation to make users aware of the problem.
