### ISSUE TITLE
Question regarding multi-domain-setup

### ISSUE THREAD

**Issue by derralf** [derhansen/sf_event_mgt#598]
In a multi-domain-setup would it be possible to have on both domains/sites:
- "global events" that will be be shown on all domains/sites
- "site events" that will be shown on only selected domains/sites only

thanks,
Ralf

**Comment by derhansen** [comment]
You could work with different sys-folders or different categories für either "global events" and "site events". In the event plugin, you can select, which events from which sys-folder or category will be shown.
