### ISSUE TITLE
[BUG] Error on non selected additional registration radio buttons

### ISSUE THREAD

**Issue by kimchristiansen** [derhansen/sf_event_mgt#635]
### Extension version
4.0.0

### Short problem description
If you add additional radio buttons to your registration, don't select one radio and try to send the registration form, you get an exception: 
PHP Warning: Invalid argument supplied for foreach() in typo3conf/ext/sf_event_mgt/Classes/ViewHelpers/Registration/Field/PrefillMultiValueFieldViewHelper.php line 84

### Steps to reproduce
1. create Event with additional Registration radio button form
2. submit form without filling the form

**Comment by derhansen** [comment]
The error occurs only [SYS][exceptionalErrors] is greater than 4096

Solution: Ensure `$submittedValues['registration']['fieldValues']` is set
