### ISSUE TITLE
[BUG] User made line break in textarea of registration is passed into the CSV

### ISSUE THREAD

**Issue by GeraSchneider** [derhansen/sf_event_mgt#639]
### Extension version
4.0.1

### Short problem description

User registration: If a user enters a message with a line break in the field "notes" (is a textarea), this line break will also be in the csv export and thus properties of this entry will be in the following line in wrong columns

### Steps to reproduce
1. Make a registration form with a notes field
2. Register in this form and enter in the notes field something with a line break
3. Export this registration as CSV

### Expected behaviour
Delete the line break

### Actual behaviour
Line break is not deleted

### Server configuration
9.5.5

**PHP version:**
7.2

**Comment by derhansen** [comment]
Fixed with db00ade
