### ISSUE TITLE
[BUG] Back to listview setting (settings.listPid) doesn't work

### ISSUE THREAD

**Issue by pulzzar030** [derhansen/sf_event_mgt#645]
### Extension version
3.0.8

### Short problem description
Button "Zurück zur Listenansicht" @ Detail Template: The Eventplugin was used on 2 different Subpages, the Button only redirects to one Page with the Listview, regardless of the settings in the Plugin-Settings ("Listen Seite") or in the template/setup (plugin.tx_sfeventmgt.settings.listPid = xxxx).

### Expected behaviour
The Button should redirect to the (different) Listview-pages given in the pluginsettings/setup.

### Actual behaviour
The Button redirect to the same listview-page instead to 2 different listview-pages.

### Server configuration
**Typo3 Version:**
8.7.24 

**PHP version:**
7.2.15

**Comment by derhansen** [comment]
I tested both scenarios and am unable to reproduce the problem. Also, merging extension settings (TypoScript/Flexform) happens on TYPO3 core side and I'm not aware of any problems in this area.

Please check your sites configuration and setup for any errors or mistakes.
