### ISSUE TITLE
[BUG] Checkbox Error Validation stopped working

### ISSUE THREAD

**Issue by WiesBen** [derhansen/sf_event_mgt#646]
### Extension version
4.0.1

### Short problem description
In the registration page I have some custom checkbox fields which are mandatory for the user. Somehow the validation stopped working, because the user can now submit the form leaving the required checkbox unchecked. In the backend I see empty array in the registration list EVEN the field is a required field. THIS ONLY AFFECTS CHECKBOXES in custom fields.

### Steps to reproduce
Can't reproduce.

### Expected behaviour
The FrontEnd Partial should show an error and block submitting the form.

### Actual behaviour
The form is successfully submitted and does not show an error message when leaving required field unchecked.

### Server configuration
**TYPO3 version:**
9.5.4

**PHP version:**
7.2.16

What can I do to debug this problem?

**Comment by derhansen** [comment]
This scenario can be reproduced, when there is only one additional registration field of type Radio or Checkbox.

**Comment by WiesBen** [comment]
Just confirmed that, yes you are absolutely right.

**Comment by derhansen** [comment]
Fixed in cc9a5d8.
