### ISSUE TITLE
[TASK] Add required attribute to input fields

### ISSUE THREAD

**Issue by derhansen** [derhansen/sf_event_mgt#649]
**Example:**

`required="{e:registration.isRequiredField(settings: settings, fieldname: 'firstname', then: 'required')}"`

**Comment by derhansen** [comment]
Closing, users can implement this in their custom templates

**Comment by ste101** [comment]
Please add this inline viewhelper to the docu.
This would be very helpfull

**Comment by derhansen** [comment]
It is there https://docs.typo3.org/p/derhansen/sf_event_mgt/7.2/en-us/ForAdministrators/Templates/Viewhelpers/Index.html#registration-isrequiredfield

Not the inline annotation, but feel free to create a PR for that. I will personally not change the docs here myself.
