### ISSUE TITLE
[TASK] Add endsSameDay getter

### ISSUE THREAD

**Issue by derhansen** [derhansen/sf_event_mgt#652]
Add a getter which returns true, if the event ends the same day.

**Comment by WiesBen** [comment]
Isn't that possible by using fluid itself:

`{f:format.date(date: event.startdate, format: 'Y-m-d')} == {f:format.date(date: event.enddate, format: 'Y-m-d')}`

**Comment by derhansen** [comment]
Of course, but `{event.endsSameDay}` might be easier to use e.g. in complex fluid conditions
