### ISSUE TITLE
[TASK] storagePage is prevented from editing for normal users

### ISSUE THREAD

**Issue by ducrot** [derhansen/sf_event_mgt#667]
### Extension version
4.1.1

### Problem description
Users without administrator rights are not allowed to edit settings.storagePage via the plugin. On the other hand, the field "recursive" can be edited.

Is it possible to remove the <exclude> parameter in Flexform_plugin.xml?

**Comment by derhansen** [comment]
Yes, I will make some more fields in flexform as `excludeField`

**Comment by derhansen** [comment]
I removed exclude field for all options of both plugins. Will be available in the upcoming version
