### ISSUE TITLE
[BUG] the encoding of the ical file is not correct - "character reference" is used on some characters

### ISSUE THREAD

**Issue by medarob** [derhansen/sf_event_mgt#678]
### Extension version
sf_event_mgt 4.1.2

### Short problem description

When I save the ical file  (and open the file in Outlook) some characters are not properly shown.
For example: `"`, `&` and `'`

In the ical file those characters are shown as `&quote`, `&amp;` and `&#039;`.

This also happens if I use those characters inside the location.

On the website all is fine, only the ical file is not correct.

### Expected behaviour
I would expect that those characters are not shown as "character reference".

### Server configuration
**TYPO3 version:**
TYPO3 8.7.27

**PHP version:**
7.2.22

**Comment by derhansen** [comment]
Thanks for your report. I pushed a fix to the development branch.
