### ISSUE TITLE
New event creation results in FE error because slug field is empty

### ISSUE THREAD

**Issue by medarob** [derhansen/sf_event_mgt#686]
### Extension version
4.1.2

### Short problem description
An editor created a new event and if a user wants to display the listview the following error appeared:

![grafik](https://user-images.githubusercontent.com/33951787/67546988-17a00580-f6fe-11e9-9c51-890ca1bf627a.png)

As admin I saw that the event slug field was empty for this new event. The editor does not see the slug field in the backend so he can't manually update the field.
Is it mandatory that the editor sees the slug field so that the slug field generation works?

As admin I was able to manually update the slug field and then the frontend worked correct.

As workaround I had to activate the field `URL-Segment (slug) [tx_sfeventmgt_domain_model_event:slug]` for the editor and then it worked.

### Expected behaviour
The slug field generation should work even if the backend user has no access to the slug field.

### Actual behaviour
The FE shows an error message that the slug generation didn't work.

### Server configuration
**TYPO3 version:** 9.5.10

**PHP version:** 7.2.23

**Comment by derhansen** [comment]
Thanks for your report. I checked the described problem and as far as I know / could find out, this is intended behavior. In other extension (e.g. `ext:news`) the same situation occurs when an editor does not have access to the `slug` field.

I also checked code in TYPO3 core. TYPO3 generates the slug field either using an AJAX request when manually generated in edit mode of a backend form or using the `DataHandler` when data is saved. Both will require the `slug` field to be visible to work.
