### ISSUE TITLE
Filter with more than 1 category

### ISSUE THREAD

**Issue by Tonyt8** [derhansen/sf_event_mgt#692]
### Extension version
Tell me which version of sf_event_mgt you use
4.1.3

### Short problem description
I would like to filter by catA AND catB
and also perhaps on a different to filter catA AND locationX
I have looked at #392 and tried the example, but the filter menu stays the same/default. I'm not really sure what to add and where to add it.
 
Please can you help further?

### Steps to reproduce
1.
2.
3.

### Expected behaviour
To list events that have 2 or more categories in the list view after selecting 2 categories from the filter menu.

### Actual behaviour
I cannot make any changes 

### Server configuration
Standard Jweiland.net configuration
**TYPO3 version:**
9.5.11

**PHP version:**
7.3.10

Thanks in advance.
Regards,
Tony

**Comment by derhansen** [comment]
If the filter menu stays the same, you must ensure to uncheck the "Disable overwrite demand" setting in the plugin (checked by default)

![image](https://user-images.githubusercontent.com/2629896/69752578-d3b37c80-1151-11ea-9c93-d430065b6576.png)

When the "Disable overwrite demand" is unchecked, you can use the GET parameter `overwriteDemand` to set constraints for the filtering. The category menu uses this as an example. You can also combine e.g. categories and add a category conjunction like in the plugin. Please see the example fluid code below:

```
<f:link.action action="list" controller="Event" arguments="{overwriteDemand:{category: '1,2', categoryConjunction: 'and'}}">Filter by category UID 1 and 2 (combined with AND)</f:link.action>
```

Hope this helps.

**Comment by Tonyt8** [comment]
Thanks for your help. I think I am understanding this a little better now, but still struggling.
Is it only possible to hard code the categorise? My categories are 7 and 8.
Is it possible to let the FE-user select different combinations of categories? Perhaps 2 categories together.
Could this be done with a Select multi option element or a list of check-box categories?

I have “Disable overwrtite demand” to 0
I added the line of luid code to: Templates/Event/List.html as below
```
<f:for each="{categories}" as="category">
		<f:if condition="{overwriteDemand.category} == {category.uid}">
			<f:then>
                 <f:link.action action="list" controller="Event" arguments="{overwriteDemand:{category: category}}" class="button button-outline">{category.title}</f:link.action>
			</f:then>
			<f:else>
				<f:link.action action="list" controller="Event" arguments="{overwriteDemand:{category: '7,8', categoryConjunction: 'and'}}">Filter by category UID 1 and 2 (combined with AND)</f:link.action>
            </f:else> 
		</f:if>        
    </f:for>
```
The way I have added the fluid code the fliter button appeared many times one for each event category. I assume I'm doing thing very wrong. How should I be using the code/

Thanks.

Regards,
Tony

**Comment by Tonyt8** [comment]
Is it possible to do something similar to news as in this simple example?

**Comment by derhansen** [comment]
As soon as you require dynamic selection of query constraints by the user, you must use the "search" feature of the extension. This way you can create a form and let the user select query constraints by checkboxes or select fields.

I do not know, why the filter button appear many times. If you modified the default HTML code from `Templates/Event/List.html`, this should not happen.

**Comment by derhansen** [comment]
No feedback, closing issue.

**Comment by HenryAveMedi** [comment]
> Thanks for your help. I think I am understanding this a little better now, but still struggling.
> Is it only possible to hard code the categorise? My categories are 7 and 8.
> Is it possible to let the FE-user select different combinations of categories? Perhaps 2 categories together.
> Could this be done with a Select multi option element or a list of check-box categories?
> 
> I have “Disable overwrtite demand” to 0
> I added the line of luid code to: Templates/Event/List.html as below
> 
> ```
> <f:for each="{categories}" as="category">
> 		<f:if condition="{overwriteDemand.category} == {category.uid}">
> 			<f:then>
>                  <f:link.action action="list" controller="Event" arguments="{overwriteDemand:{category: category}}" class="button button-outline">{category.title}</f:link.action>
> 			</f:then>
> 			<f:else>
> 				<f:link.action action="list" controller="Event" arguments="{overwriteDemand:{category: '7,8', categoryConjunction: 'and'}}">Filter by category UID 1 and 2 (combined with AND)</f:link.action>
>             </f:else> 
> 		</f:if>        
>     </f:for>
> ```
> 
> The way I have added the fluid code the fliter button appeared many times one for each event category. I assume I'm doing thing very wrong. How should I be using the code/
> 
> Thanks.
> 
> Regards,
> Tony

I'm terrible at typo3 coding, but i've made a great bootstrap template for this extension (which i would actually love to share to developer but don't know how).

Anyways i made this for category filtering:
`<div class="btn-group">
  <button class="btn btn-sm btn-outline-primary dropdown-toggle" type="button" id="categoriesMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i class="fas fa-fw fa-tag"></i>&nbsp;
    <f:if condition="{overwriteDemand.category}">
      <f:then>
        <f:for each="{categories}" as="category">
          <f:if condition="{overwriteDemand.category} == {category.uid}">
            {category.title}
          </f:if>
        </f:for>
      </f:then>
      <f:else>
        <f:translate key="event.allCategories" />
      </f:else>
    </f:if>
  </button>
  <div class="dropdown-menu" aria-labelledby="categoriesMenu">
    <f:link.action action="list" controller="Event" class="dropdown-item{f:if(condition: overwriteDemand.category,then: '', else: ' active')}">
      <f:translate key="event.allCategories" />
    </f:link.action>
    <f:for each="{categories->v:iterator.sort(order: 'ASC', sortBy: 'title')}" as="category">
      <f:link.action
        action="list" controller="Event" arguments="{overwriteDemand:{category: category}}"
        class="dropdown-item{f:if(condition: '{overwriteDemand.category} == {category.uid}',then: ' active')}"
      >
        {category.title}
      </f:link.action>
    </f:for>
  </div>
</div>`

but i have a problem when overwritedemand happens, plugin is set to: "Do NOT show events with selected categories (OR)"
but when the filter happens, it shows all events including those which it is not supposed to be shown.

Somehow i think it could be easily fixed with putting a conditional similar to yours
`{overwriteDemand:{category: '7,8', categoryConjunction: 'and'}}`

but i dunno how the code should be… any ideas??
<img width="1106" alt="Screen Shot 2020-02-14 at 14 59 14" src="https://user-images.githubusercontent.com/51093175/74537590-b0bb8c00-4f3a-11ea-9a20-165d701a5b5c.png">
