### ISSUE TITLE
Registration configuration

### ISSUE THREAD

**Issue by UNI49** [derhansen/sf_event_mgt#697]
### Extension version
4.1.3

### Short problem description
I try to configure registration process, but when process switch to "ConfirmRegistration" I always have "EventNotFound.html" template (and I can overwrite this template in my own package).

### Expected behaviour
- Don't have the "event not found" message on this "confirmation" page, if we add "detail" and "registration".
- Being able to overwrite "EventNotFound.html" template

### Server configuration
**TYPO3 version:** 9.5.13

**PHP version:** 7.2.20

**Comment by derhansen** [comment]
This sounds like a configuration issue. Did you overwrite the default templates? If yes, please use the default templates to make sure, the process works as expected and if so, adapt templates step by step to your own.

The error message may occur, when you forgot to add the `arguments="{event: event}"` to your Registration.html template - see https://github.com/derhansen/sf_event_mgt/blob/master/Resources/Private/Templates/Event/Registration.html#L92

In case you missed it, the EventNotFound.html Template can be overwritten by TypoScript - see: https://github.com/derhansen/sf_event_mgt/blob/master/Configuration/TypoScript/setup.txt#L71

**Comment by UNI49** [comment]
Thanks for answering.

It's clearer for EventNotFound overwriting. 

For the other question, it's more about our configuration (detail and registration on same page). Thanks for your help.
