### ISSUE TITLE
overwriteDemand not behaving properly when Plugin in page has categories setup

### ISSUE THREAD

**Issue by HenryAveMedi** [derhansen/sf_event_mgt#705]
### Extension version
**sf_event_mgt**  4.2

### Short problem description
- plugin is set to: "Do NOT show events with selected categories (OR)" loading view is correct
- when using category filter to filter by category, it shows all events except the chosen in filter

### Steps to reproduce
1. insert a list plugin in your page and set plugin to: "Do NOT show events with selected categories (OR)" and click 2 categories that are not supposed to be shown
2. go to frontend and observe if list is filtered properly (it should at this point)
3. click a category in your filter menu and observe that now all events except chosen category are shown

### Expected behaviour
After filter click, the list should only show events which belong to the category you clicked, but not to the ones u clicked in plugin for "Do NOT show events with selected categories (OR)"

### Actual behaviour
All events except chosen category are shown, I do understand why the filter works that way when  "Do NOT show events with selected categories (OR)" is set in the plugin, yet the behaviour (in my opinion) should be as described above

### Server configuration
**TYPO3 version:** 9.5.11

**PHP version:** 7.3

------------------------------------------------------
I'm terrible at typo3 coding, but i've made a great bootstrap template for this extension (which i would actually love to share to developer but don't know how).

Anyways i made this for category filtering:
```
<div class="btn-group">
  <button class="btn btn-sm btn-outline-primary dropdown-toggle" type="button" id="categoriesMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i class="fas fa-fw fa-tag"></i>&nbsp;
    <f:if condition="{overwriteDemand.category}">
      <f:then>
        <f:for each="{categories}" as="category">
          <f:if condition="{overwriteDemand.category} == {category.uid}">
            {category.title}
          </f:if>
        </f:for>
      </f:then>
      <f:else>
        <f:translate key="event.allCategories" />
      </f:else>
    </f:if>
  </button>
  <div class="dropdown-menu" aria-labelledby="categoriesMenu">
    <f:link.action action="list" controller="Event" class="dropdown-item{f:if(condition: overwriteDemand.category,then: '', else: ' active')}">
      <f:translate key="event.allCategories" />
    </f:link.action>
    <f:for each="{categories->v:iterator.sort(order: 'ASC', sortBy: 'title')}" as="category">
      <f:link.action
        action="list" controller="Event" arguments="{overwriteDemand:{category: category}}"
        class="dropdown-item{f:if(condition: '{overwriteDemand.category} == {category.uid}',then: ' active')}"
      >
        {category.title}
      </f:link.action>
    </f:for>
  </div>
</div>
```
Somehow i think the problem could be easily fixed with putting a conditional similar to what @Tonyt8 wrote in a different post for multiple categories
`{overwriteDemand:{category: '7,8', categoryConjunction: 'and'}}`

but i dunno how the code should be… any ideas??
(Here a screenshot, after chosing "meditation" it just shows all but meditation)
<img width="1106" alt="Screen Shot 2020-02-14 at 14 59 14" src="https://user-images.githubusercontent.com/51093175/74537590-b0bb8c00-4f3a-11ea-9a20-165d701a5b5c.png">

**Comment by derhansen** [comment]
To make it simple: `overwriteDemand` does completely overwrite **all** settings made in the plugin, so your selected categories in the plugin will be overwritten by the categories you provide in `overwriteDemand`

So when you configure the plugin as described "Do NOT show events with selected categories (OR)" and overwrite the category using `overwriteDemand`, it will show all events, that do **not** match the given category and will not keep the category you set in the plugin.

Sadly not much I can do about this, since adding more logic here to keep categories selected will make the extension more hard to maintain. 

Depending on the amount of Events to show, I would recommend to implement the whole filtering using JavaScript. Much easier to archive ans possibly also faster than re-rending the whole page for filtering purposes

**Comment by HenryAveMedi** [comment]
yeh, thought so……… i hoped for a solution somwhere near to:
`{overwriteDemand:{category: '7,8', categoryConjunction: 'and'}}` but i guess is much to ask

**Comment by HenryAveMedi** [comment]
so, it took me some hours because i'm actually no programmer, but a graphic designer html css enthusiast with a bit of understanding of JS…… but i managed to fiddle a solution based on ur idea of javascript filtering…… i would still need to extend it because i actually made an empty item partial for ur extension, but it gets render if no {events} are available
`
<div class="event-list">
          <f:if condition="{events}">
            <f:then>
              <f:for each="{events}" as="event">
                <f:render partial="Event/ListItem" arguments="{_all}"/>
              </f:for>
            </f:then>
            <f:else>
              <f:render partial="Event/NoItem" arguments="{_all}"/>
            </f:else>
          </f:if>
        </div>
`

-------------------------------
my javascript solution for my dropdown filter is the following, in case someone needs a kinda fast solution to the same problem

`
<div class="btn-group">
  <button class="btn btn-sm btn-outline-primary dropdown-toggle" type="button" id="categories-menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i class="fas fa-fw fa-tag"></i>&nbsp;
        <span class="event-filter filter-all-events active"><f:translate key="event.allCategories" /></span>
        <f:for each="{categories}" as="category">
            <span class="event-filter">{category.title}</span>
        </f:for>
  </button>
  <div id="categoryFilters" class="dropdown-menu" aria-labelledby="categories-menu">
    <button onclick="filterSelection('all')" class="dropdown-item active">
      <f:translate key="event.allCategories" />
    </button>
    <f:for each="{categories->v:iterator.sort(order: 'ASC', sortBy: 'title')}" as="category">
      <button onclick="filterSelection('{category.title}')" class="dropdown-item">
        {category.title}
      </button>
    </f:for>
  </div>
</div>

<script type="text/javascript">
  var selection = 'all'
  filterSelection(selection)
  function filterSelection(c) {
    selection = c;
    var x, i;
    itemsToFilter = document.getElementsByClassName("filterDiv");
    if (selection == 'all') c = '';
    // Add the "show" class (display:block) to the filtered elements, and remove the "show" class from the elements that are not selected
    for (i = 0; i < itemsToFilter.length; i++) {
      w3RemoveClass(itemsToFilter[i], "show");
      if (itemsToFilter[i].className.indexOf(c) > -1) w3AddClass(itemsToFilter[i], "show");
    }
  }
  
  // Show filtered elements
  function w3AddClass(element, name) {
    var i, arr1, arr2;
    arr1 = element.className.split(" ");
    arr2 = name.split(" ");
    for (i = 0; i < arr2.length; i++) {
      if (arr1.indexOf(arr2[i]) == -1) {
        element.className += " " + arr2[i];
      }
    }
  }
  
  // Hide elements that are not selected
  function w3RemoveClass(element, name) {
    var i, arr1, arr2;
    arr1 = element.className.split(" ");
    arr2 = name.split(" ");
    for (i = 0; i < arr2.length; i++) {
      while (arr1.indexOf(arr2[i]) > -1) {
        arr1.splice(arr1.indexOf(arr2[i]), 1);
      }
    }
    element.className = arr1.join(" ");
  }
  
  // Add active class to the current dropdownItem
  var filterDropdown = document.getElementById("categoryFilters");
  var filters = filterDropdown.getElementsByClassName("dropdown-item");
  for (var i = 0; i < filters.length; i++) {
    filters[i].addEventListener("click", function() {
      var current = filterDropdown.getElementsByClassName("active");
      current[0].className = current[0].className.replace(" active", "");
      changeButton(selection)
      this.className += " active";
    });
  }
  // Add active class to the current category in dropdown button
  function changeButton(selection) {
    var filterButton = document.getElementById("categories-menu");
    var buttonFilters = filterButton.getElementsByClassName("event-filter");
    var found;
    // find current selection and remove active class
    var current = filterButton.getElementsByClassName("active");
    current[0].className = current[0].className.replace(" active", "");
    // Add active class to the new filter in dropdown button
    for (var i = 0; i < buttonFilters.length; i++) {
      if (buttonFilters[i].textContent == selection) {
        found = buttonFilters[i];
        break;
      }
    }
    if (found) { 
      found.className += " active";
    } else { 
      if (selection == 'all') {
        var allCategories = filterButton.getElementsByClassName("filter-all-events");
        allCategories[0].className += " active";
      }
    }
  }
</script>
`

that is the whole code for a partial I made named "CategoryNav" u can make section in ur list template or a partial and then render (if you want to use this filter)
cheers

**Comment by derhansen** [comment]
Great you solved the problem with JavaScript and thanks a lot for sharing your code. Can this issue be closed then?

**Comment by HenryAveMedi** [comment]
np, i'm always to share the code…… it might not be the shortest/prettiest solution, i'm sure a pro JS programmer can come up with something better, but i share anyways.

Closed, I don't know, this is more like a workaround, maybe you can move it to feature instead of issue? in case we do want to expand that kind of functionality? Maybe I manage to learn more about creating extensions of my own and could understand more how this works and help out
