### ISSUE TITLE
[TASK] Better waitlist indication 

### ISSUE THREAD

**Issue by derhansen** [derhansen/sf_event_mgt#707]
When the amount of simultaneous registrations is greater than the amount of free places, the Simultaneous Registration select field shows the amount of simultaneous registrations and **all registrations** will be saved on the waitlist. 

In order to make the waitlist handling better, the simultaneous registrations field will only show the amount of remaining free places, as long as there are free places available and the max. amount of   simultaneous registration >= free places.

Also, the detail view of an event now shows an indicator, that an event has a waitlist, when no free places are left.

**Comment by UNI49** [comment]
Hi
I'm not sure about your modifications, I mean [L.176](https://github.com/derhansen/sf_event_mgt/commit/72b663d752c1f970955bc9d8b6b46b0ac006bf50#diff-66e7214847ac12aac6b765e126b7ddf3R176) the condition isn't really useful, and maybe more an anti-productive thing. If someone don't know about a possible waitlist, this person can't be aware about the possibility of a waitlist, before the "free places" are empty. I think the "==0" isn't a good idea for that reason.

Let me know your opinion.

**Comment by derhansen** [comment]
Yes, you're right. I think it is then best to make the condition as following `{event.enableWaitlist}`.  Do you agree with that? 

In your original PR this was `{event.enableWaitlist} && {event.freePlaces}`, which would not have shown the message, when there were zero free places (for for all other positive/negative numbers.

Anyway, I will also need to fix the ViewHelper once again, since it currently contains a bug due to the last change

**Comment by UNI49** [comment]
I agree, it seems to be a good condition.

I originally make this, because, in my own template, I also show the registration form (to have event information and form registration, better UX). But not in the original/released one, sorry for that misunderstanding.
