### ISSUE TITLE
german label for backend form field has typos

### ISSUE THREAD

**Issue by TrueType** [derhansen/sf_event_mgt#758]
### Extension version
v4.2.1

### Short problem description
is
`Komma getrennte liste mit Felnamen,
`
should
`Komma getrennte Liste mit Feldnamen,`

### Steps to reproduce
1. User registration plugin last field on first tab

Question?
- Is it possible to edit the language files oneself?

**Comment by derhansen** [comment]
I updated the translation. 

You can edit Translations using Crowdin - https://crowdin.com/project/typo3-extension-sfeventmgt/de#

Note, those translations are only available, when using the new translation server (needs tobe activated in TYPO3 9.5 using a Feature Toggle in TYPO3 Install Tool)
