### ISSUE TITLE
Extended model with empty values after update from 4.2.2 to 5.0.1

### ISSUE THREAD

**Issue by matcolton** [derhansen/sf_event_mgt#773]
### Extension version
sf_event_mgt 5.0.1
### Server configuration
Typo3 10.4.3
PHP 7.2
### Problem
After updating from Typo3 9.5 to 10.4.3 and sf_event_mgt from 4.2.2 to 5.0.1 my extended model doesn't work anymore.  All fields are empty, not only the fields of the extended model, all fields.
I didn't change anything during the process of upgrading, so I'm a bit flawed and really don't unterstand why it doesn't work anymore.

### ext_typoscript_setup.typoscript
```
config.tx_extbase {
    persistence {
        classes {
            WXS\Extname\Domain\Model\Event {
                mapping.tableName = tx_sfeventmgt_domain_model_event
            }
        }
    }
}
```
### ext_localconf.php
As soon as I remove the **registerImplementation** the original model is used and filled with data. 
```
<?php
defined('TYPO3_MODE') || die();

call_user_func(
    function () {
        // XCLASS event
        $GLOBALS['TYPO3_CONF_VARS']['SYS']['Objects'][\DERHANSEN\SfEventMgt\Domain\Model\Event::class] = [
            'className' => \WXS\Extname\Domain\Model\Event::class
        ];

        // Register extended domain class
        \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Extbase\Object\Container\Container::class)
            ->registerImplementation(
                \DERHANSEN\SfEventMgt\Domain\Model\Event::class,
                \WXS\Extname\Domain\Model\Event::class
            );
    }
);
```
### Classes/Domain/Model/Event.php
```
<?php
namespace WXS\Extname\Domain\Model;

class Event extends \DERHANSEN\SfEventMgt\Domain\Model\Event
{
    /**
     * txExtnameOrganisator
     * 
     * @var string
     */
    protected $txExtnameOrganisator = '';
   
    public function getTxExtnameOrganisator()
    {
        return $this->txExtnameOrganisator;
    }

    public function setTxExtnameOrganisator($txExtnameOrganisator)
    {
        $this->txTxExtnameOrganisator = $txExtnameOrganisator;
    }
}
```
### Configuration/TCA/Overrides/tx_sfeventmgt_domain_model_event.php
```
<?php
defined('TYPO3_MODE') or die();

$extnameEventFields = [
	'tx_extname_organisator' => [
        'exclude' => true,
        'label' => 'LLL:EXT:extname/Resources/Private/Language/locallang_db.xlf:tx_extname_domain_model_event.tx_extname_organisator',
        'config' => [
            'type' => 'input',
            'size' => 30,
            'eval' => 'trim'
        ],
    ],
];
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTCAcolumns(
    'tx_sfeventmgt_domain_model_event', 
    $extnameEventFields
);

\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addToAllTCAtypes(
    'tx_sfeventmgt_domain_model_event', 
    'tx_extname_organisator', 
    '', 
    'after:organisator'
);
```

**Comment by derhansen** [comment]
This is no problem with the extension itself, since your code uses a deprecated TYPO3 core features that has been removed in TYPO3 10.

See: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87623-ReplaceConfigpersistenceclassesTyposcriptConfiguration.html

So you should just migrate the deprecation (see commit is #715) and then your code should work as before.

**Comment by matcolton** [comment]
Oh... Thanks, sorry for bugging you. Works like a charm.
I ran the "Scan Extension Files" before the update, but I guess that file isn't covered by the check.

**Comment by derhansen** [comment]
I'll re-open this issue as a reminder for me to update the Demo Extension how to extend sf_event_mgt

**Comment by derhansen** [comment]
Closing issue - Demo Extension is now compatible with TYPO3 10.4 https://github.com/derhansen/sf_event_mgt_extend_demo/releases/tag/0.4.0
