### ISSUE TITLE
can't change the url-segment of an event if the url-segment already existed in the system

### ISSUE THREAD

**Issue by medarob** [derhansen/sf_event_mgt#775]
### Extension version
4.2.2

### Short problem description
An editor wanted to change the URL-Segment  of an event because a "-1" was added at the end of the url. So, the editor wanted "domain.tld/event/details/my_event" but the url was "domain.tld/event/details/my_event-1"

The problem was that there was already an event with the same url from the last year in the system.
Now I wanted to change the URL Segment of the old event into "domain.tld/event/details/my_event-2019" and change the new event url to "domain.tld/event/details/my_event".

This didn't work as I expected.

I was able to change the url segment from the old event into "my_event-2019" so the url for th old event was now "domain.tld/event/details/my_event-2019" but I couldn't change the url from the new event. The "-1" was added each time I tried to save the event.

I was only able to change the url segment from "my_event-2019" back to "my_event".

So, as a workaround I used the "Weiterleitung" module where I configured a forward url from "domain.tld/event/details/my_event" to "domain.tld/event/details/my_event-1".

My questions are now: Is this a bug and should this theoretically work? What did I wrong?

### Server configuration
**TYPO3 version:**
TYPO3 9.5.19

**PHP version:**
7.2.31

**Comment by derhansen** [comment]
Actually I do not know what went wrong, but I suggest you check the following:

1) Check the database, that there is only one event with `my_event` slug
2) Check, that the slugBehavior is is set as expected (see https://github.com/derhansen/sf_event_mgt/releases/tag/4.2.2)

**Comment by derhansen** [comment]
I'm closing the issue now, since no feedback was provided after 4 weeks. If you still have any problems, feel free provide input on the issue.
