### ISSUE TITLE
[QUESTION] Reuse additional registration fiedls?

### ISSUE THREAD

**Issue by zolthan** [derhansen/sf_event_mgt#777]
### Extension version
4.2.2 on Typo3 8.7.32

### Short problem description
We have several events with identical additional fields. Is it possible to reuse already created additional fields or do we need to create the same two additional fields for every event? So in the end we will have 100 identically named fields for 100 different events. This makes it impossible to create registrations in the backend.

**Comment by derhansen** [comment]
No, this is not possible. I suggest you extend the extension with own fields in this case. I have provided a demo extension which shows how https://github.com/derhansen/sf_event_mgt_extend_demo/

**Comment by zolthan** [comment]
Thanks, I'll try that
