### ISSUE TITLE
[BUG] Input elements with same id result in browser-console-warning "Found elements with non-unique id"

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [derhansen/sf_event_mgt#778]
Hi there,

due to a foreach loop in

https://github.com/derhansen/sf_event_mgt/blob/85652fe27a38c1bcc918ff542725d2345487e115/Resources/Private/Partials/Registration/Fields/Radio.html#L15

same IDs for <input> elements are generated which result in a browser-console warning (Chrome):

[DOM] Found 3 elements with non-unique id #47: (More info: https://goo.gl/9p2vKq)
<input id=​"47" type=​"radio" name=​"tx_sfeventmgt_pievent[registration]​[fields]​[47]​" value=​"Thema 1">​
<input id=​"47" type=​"radio" name=​"tx_sfeventmgt_pievent[registration]​[fields]​[47]​" value=​"Thema 2">​
<input id=​"47" type=​"radio" name=​"tx_sfeventmgt_pievent[registration]​[fields]​[47]​" value=​"Thema 3">​

The same happens with other fields like "check.html" where IDs are generated the same way.

**Comment by derhansen** [comment]
Thanks for your report. This is valid and I will make the IDs unique in next versions of the extension.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Cool, thank you!
