### ISSUE TITLE
[FEATURE] Category images

### ISSUE THREAD

**Issue by psaikoheiko** [derhansen/sf_event_mgt#781]
### Extension version
4.2.2 

### Short problem description
We would like to be able to display the images of categorys in the list view but there is no possibility. Categories in backend can have images but there is no way to display them via arrays, which would be a great solution since our customers dont have a single image for each event. In order to avoid uploading the same image to every single event they would be able to upload it once for their categories which would be great to display at least a hint in the list view.

![Screenshot_1](https://user-images.githubusercontent.com/68227431/87298417-74e91a80-c50a-11ea-999f-2c51b4da5ffa.png)

**Comment by derhansen** [comment]
Categories in TYPO3 backend do not have an image by default. It is `ext:news` that adds additional fields to the category domain model (see: https://github.com/georgringer/news/blob/master/ext_tables.sql#L72)

If you want `ext:sf_event_mgt` to use the category domain model of `ext:news`, the category domain model of `ext:sf_event_mgt` needs to bee overridden as shown below:

Add this to a extension (e.g. your sitepackage) in `ext_localconf.php`:

```
    GeneralUtility::makeInstance(\TYPO3\CMS\Extbase\Object\Container\Container::class)
        ->registerImplementation(
            \DERHANSEN\SfEventMgt\Domain\Model\Category::class,
            \GeorgRinger\News\Domain\Model\Category::class
        );
```

After adding this snippet and cleaning the cache, all categories events are now category objects of ext:news

![image](https://user-images.githubusercontent.com/2629896/87340831-ec3d9f00-c548-11ea-8bca-c2421026f2cb.png)

Please do not close this issue, I will update the FAQ in the docs about this topic.
