### ISSUE TITLE
admin mail is always used as sender

### ISSUE THREAD

**Issue by blackbasket** [derhansen/sf_event_mgt#782]
### Extension version
5.0.1

### Short problem description
all event mails have the admin address as sender, but I configured in plugin and module another address as notification sender

### Steps to reproduce
1. create a registration
2. cancel a registration

### Expected behaviour
the defined notification sender address should be used

### Actual behaviour
admin address is used

### Server configuration
**TYPO3 version:**
10.4.4

**PHP version:**
7.4.8

**Comment by derhansen** [comment]
The admin email (`settings.notification.adminEmail`) is never used anywhere in the code as sender for an email, so what you describe is not possible. 

To make sure I also tested email settings / sent emails manually and everything works as expected. 

Please check you TypoScript setup for misconfiguration. Sender email is primary used from `settings.notification.senderEmail` as long as you override the sender manually using signals/events.

**Comment by blackbasket** [comment]
This are my TS constants - with real values in typo3 application, of course:
module.tx_sfeventmgt.settings.notification.senderName = <Companyname>
module.tx_sfeventmgt.settings.notification.senderEmail = <info-address>
plugin.tx_sfeventmgt.settings.notification.adminEmail = <admin-address>
plugin.tx_sfeventmgt.settings.notification.replyToEmail = <info-address>
plugin.tx_sfeventmgt.settings.notification.senderName = <Companyname>
plugin.tx_sfeventmgt.settings.notification.senderEmail = <info-address>

But every mail has <admin-address> as sender... I know, I configured this for testing the first time... but now, I cannot even find the wrong shown display name using TS Object Browser...

Sorry, but I am helpless :/

**Comment by derhansen** [comment]
When TYPO3 compiles TypoScript settings, plugin settings (from the content element) are merged as one of the last steps into the TypoScript array. Those settings are not visible in the TS Object Browser, since they are stored in FlexForm for the plugin.

Please check page, where the plugin is used for the registration step. 

![image](https://user-images.githubusercontent.com/2629896/87781864-c1e22f00-c831-11ea-8cdb-e1561ed863d2.png)

Those settings are merged by TYPO3 into TypoScript settings.

**Comment by blackbasket** [comment]
DANKE :)

Thank you very much... I have looked for two weeks now, but not in the plugin settings :/
