### ISSUE TITLE
Category-Filtering is not working

### ISSUE THREAD

**Issue by sztop** [derhansen/sf_event_mgt#783]
### Extension version
5.0.1

### Short problem description
In List view the filter links are shown but when clicked, the list entries aren't filtered but shown all although the filter links seem to be OK. Tested on different server environments.

### Steps to reproduce
1. Inserting static extension template
2. Creating the necessary pages (list and detail view)
3. Creating event-entries in a sysfolder
4. Calling the list page and using the shown filters

### Expected behaviour
Filtering should happen

### Actual behaviour
No filtering after clicking the filter links, e.g. for category "Kategorie 1" (with ID=2):
http://XXXXX.de/veranstaltungen?tx_sfeventmgt_pievent%5Baction%5D=list&tx_sfeventmgt_pievent%5Bcontroller%5D=Event&tx_sfeventmgt_pievent%5BoverwriteDemand%5D%5Bcategory%5D=2&cHash=5239cb250c605c213ff8cfb5b78fff37

### Server configuration
**TYPO3 version:**
10.4.6
**PHP version:**
7.2.29

**Comment by derhansen** [comment]
Please make sure to uncheck the "Disable overwrite demand" in the plugin settings and also make sure, that the category mode is not equal to "Ignore category selection".

**Comment by sztop** [comment]
Thanks for the quick reply, Torben.
Your advice solved my problem of course 👍

**Comment by derhansen** [comment]
Thanks for your feedback. I also updated the FAQ about this topic.
