### ISSUE TITLE
dateOfBirth Template

### ISSUE THREAD

**Issue by opaque01** [derhansen/sf_event_mgt#790]
### Extension version
Tell me which version of sf_event_mgt you use

### Short problem description
Templates/Event/Registration.html line 232 fieldname sould be "dateOfBirth" instead of date_of_birth. Otherwise the code block <span class="event-required">*</span> will not be rendered

### Steps to reproduce
1. install plugin
2. add TS: plugin.tx_sfeventmgt.settings.registration.requiredFields = dateOfBirth
3. see registration -> no "*" added after Geburtstag

### Expected behaviour
Tell me what should happen

### Actual behaviour
Tell me what happens instead

### Server configuration
**TYPO3 version:**
9.5.19
**PHP version:**
7.3

**Comment by opaque01** [comment]
Further, in RegistrationConfirmed.html remove the paragraph tag. f:format.html will also add a p tag.
<p><f:format.html>{settings.notification.senderSignature}</f:format.html></p>
<f:format.html>{settings.notification.senderSignature}</f:format.html>

**Comment by derhansen** [comment]
Thanks, both issues have been resolved in current dev-branch.
