### ISSUE TITLE
calendar view | hide non-bookable events

### ISSUE THREAD

**Issue by blofeld-th** [derhansen/sf_event_mgt#791]
### Extension version
3.0.8
### Question
Hello,

I hope this is the right way to ask a question. 

I would like to hide the events in the calendar view that are no longer bookable due to the number of participants. Unfortunately I have not found anything in the documentation.

Thanks for a hint

Thomas

**Comment by derhansen** [comment]
You could customize the Fluid view for the calendar, so events with registration enabled and no free places left are excluded.

Example to be used in `CalendarDayItem.html` partial:

```
<f:for each="{day.events}" as="event">
  <f:if condition="!{event.enableRegistration} || ({event.enableRegistration} && {event.maxParticipants} > 0 && {event.freePlaces} > 0)">
    ...rest of Fluid to show event
  </f:if>
</f:for>
```

Add the condition after the existing for-each loop.

**Comment by blofeld-th** [comment]
Moin Herr Hansen,

besten Dank für den Hinweis. Werde es nachher gleich mal versuchen.



Gruß

Thomas Herrmann

**Comment by derhansen** [comment]
Closing the issue now. Feel free to provide additional feedback if you still have problems
