### ISSUE TITLE
[BUG] Backend Pagination forgets sorting

### ISSUE THREAD

**Issue by nicobayati** [derhansen/sf_event_mgt#793]
### Extension version
sf_event_mgt 4.3.1

### Short problem description
In the backend module 'Events' I set the sort option to 'Startdate' and 'Descending' and click on 'Search'. The list is adjusted according to my sorting. If I now click on 'Next' ( ») in the list, the list "forgets" my sort order defined above and returns to the default sort order.

### Steps to reproduce
1. I have created some sample data with which you can understand the problem very well. 3 years long every month an event, and the event which is oldest also has the highest uid https://gist.github.com/nicobayati/c5e1a849ad03c5bd4ea664316242bfc9#file-gistfile1-txt
2. Now select the above mentioned options: 'Sorting': 'Start Date' and 'Descending', now all events with start date from December 2020 to March 2020 are shown.  (from top to bottom)
3. If you now navigate in the pagination, the previously selected sorting is no longer applied. For example, the second page shows November 2018 to August 2019 (from top to bottom).

### Expected behaviour
When using the pagination, I expect my selected sort order to be applied

It looks like this bug or a very similar bug has been fixes here in the past: #485 

### Server configuration
**TYPO3 version:** 9.5.20

**PHP version:** 7.2.31

**Comment by derhansen** [comment]
Thanks for your report. I already pushed a fix to the development branch and will backport it to version 4.x in the next release.
