### ISSUE TITLE
[TASK] Evaluate possibility to control list/detail page cache

### ISSUE THREAD

**Issue by derhansen** [derhansen/sf_event_mgt#795]
Evaluate possibility to control list/detail page cache, so registration links will not be shown when registration deadline / startdate is reached.

**Comment by christophlehmann** [comment]
That's a very good idea. I digged into it and came to the conclusion, that is does not work at the moment.

The TypoScriptController has a hook which modifies the cache timeout, but it's executed before the extbase controller and the result is cached.

Later in TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::realPageCacheContent() is a hook $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['tslib/class.tslib_fe.php']['usePageCache'], but it can’t modify the cache lifetime variable.

The page cache is instantiated very early so we can not override it's configuration.

I think we need a new hook.

**Comment by derhansen** [comment]
I have already put some wirk into this topic and it seems that there already is a hook for that.

`$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['tslib/class.tslib_fe.php']['get_cache_timeout']`

We can use this hook to calculate the cache lifetime depending on a TypoScript configuration similar to [config.cache](https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/Setup/Config/Index.html#cache). The integrator has to define which PIDs should be taken into account for the page cache lifetime calculation. Then, we use `getFirstTimeValueForRecord()` to calculate the page cache lifetime depending on starttime/stoptime (TYPO3 default) and additionally adjust the page cache lifetime depending on the registration start date and deadline.

**Comment by derhansen** [comment]
The feature has been implemented in the development branch for version 5.x and has also been backported to the 4.x version of the extension.
