### ISSUE TITLE
[TASK] Error when executing TYPO3 cleanup:flexforms console command due to a DataHandler hook

### ISSUE THREAD

**Issue by mkarulin** [derhansen/sf_event_mgt#797]
### Extension version
11.0.3

### Short problem description
The root cause of the error is perhaps not in this extension, but the DataHandlerHook should probably not trigger on all FlexForms. The problem occurs in sf_event_mgt/Classes/Hooks/DataHandlerHooks.php line 122

 [ TypeError ]                                                                                                                                                                                          
  Argument 1 passed to TYPO3\CMS\Core\Utility\GeneralUtility::array2xml() must be of the type array, string given, called in /var/www/html/private/typo3/sysext/core/Classes/Configuration/FlexForm/FlexFormTools.php on line 1001

### Expected behaviour
The hook should check if the list_type is one of sf_event_mgt plugins before doing its thing

### Actual behaviour
The hook triggers on all tt_content element flexforms

### Server configuration
TYPO3 9.5.22

7.2.30

**Comment by derhansen** [comment]
Thanks for your feedback. I checked the issue and could not reproduce the problem. But I understand, that the exception is thrown, when `$flexformData` is not an array. 

I could not find a suiteable solution to check for the `list_type` in the `processDatamap_postProcessFieldArray` hook, so I suggest that I will just harden the code, so `$flexFormTools->flexArray2Xml` is not called, when `$flexformData` is not an array.

**line 105**
```
            if (!is_array($flexformData)) {
                return;
            }
```

Would this resolve your problem?
