### ISSUE TITLE
[BUG] ModifyUserMessageAttachmentsEvent is not dispatched

### ISSUE THREAD

**Issue by FLeudts** [derhansen/sf_event_mgt#808]
### Extension version
5.1.1

### Short problem description
ModifyUserMessageAttachmentsEvent is not dispatched

### Steps to reproduce
Trying to register a ModifyUserAttachmentsEvent Listener reveals that the event is never dispatched

Line 317 in sf_event_mgt/Classes/Service/NotificationService.php the event modifyUserMessageSenderEvent
instead of the correct event modifyUserAttachmentsEvent is dispatched

**Comment by derhansen** [comment]
Thanks for you report. This will be fixed in the upcoming version 5.2.0.
