### ISSUE TITLE
[TASK] New T3Icons Icons Path

### ISSUE THREAD

**Issue by der-phillip** [derhansen/sf_event_mgt#815]
Hi since TYPO3 10.4.10 the path to the file has changed.

Directory svgs ist new.

`/typo3/sysext/core/Resources/Public/Icons/T3Icons/svgs/actions/actions-accessibility.svg`

https://github.com/derhansen/sf_event_mgt/blob/7372de3f26d9263cc5c7e837725ab3831a1b1bac/Resources/Private/Templates/Administration/List.html#L85

**Comment by derhansen** [comment]
Thanks, I'll switch to the core ViewHelper for this icon

**Comment by derhansen** [comment]
Patch is available in develop branch. New version will follow soon.
