### ISSUE TITLE
define route for category selector

### ISSUE THREAD

**Issue by derBoogie** [derhansen/sf_event_mgt#835]
### Extension version: 5.2.0

Is it possible to define a route for the category selector in routeEnhancers (config.yaml)?

Currently the urls looks like this: https://mydomain.tld/events/?tx_sfeventmgt_pievent%5BoverwriteDemand%5D%5Bcategory%5D=8&cHash=84857e153c8d36879e18fda08be59087

### Server configuration
TYPO3 version: 10.4.10
PHP version: 7.4-latest FPM

**Comment by derhansen** [comment]
Yes, this is possible but only if you have installed ext:news

See: https://docs.typo3.org/p/derhansen/sf_event_mgt/5.2/en-us/ForAdministrators/Configuration/RouteEnhancers/Index.html

If ext:news is installed, you can easily modify the example route enhancers to include the slug field of the sys_category record. 

I will check if it is possible to extend `sys_category` with a custom `slug` for the case if ext:news is not installed, so please leave this ticket open as a reminder for me :-)

**Comment by derBoogie** [comment]
Hi Torben,
thanks for your fast reply.
I'm not using news in this website yet and I'm looking forward to hear from you again =)

**Comment by derhansen** [comment]
@derBoogie There seem to be no side effects having a slug field with the same name as ext:news adds, so I added the slug field to sys_category in change 447013ac314a86852edff57407f8b53080d1796c including some documentation how to properly configure routing.

**Comment by derhansen** [comment]
Closing issue, the feature will be available in the upcoming version.
