### ISSUE TITLE
[FEATURE] Add event plausibility check 

### ISSUE THREAD

**Issue by jackd248** [derhansen/sf_event_mgt#841]
Is it possible to build in an event date plausibility check in the backend event editing to prevent setting the end date before the start date?

**Comment by derhansen** [comment]
Yes, this is possible by implementing a dataHandler hook, which checks both start- and end-date and renders a flash message, that the event ins misconfigured.

**Comment by derhansen** [comment]
Feature has been added and will be releases soon. Closing issue.
