### ISSUE TITLE
[FEATURE] FE user as speaker

### ISSUE THREAD

**Issue by rintisch** [derhansen/sf_event_mgt#851]
### User Story
Enable option to add FE user accounts as speaker.

### Short problem description
Speaker shall be able to share files with each other on an event base. This would be possible if editors could add FE user as speaker. 
With this I could implement a special view for an event if the logged in user is a speaker. There they could upload files and download uploaded files.

**Comment by derhansen** [comment]
Although it is possible through TCA to add relations for multiple tables to a DB Group field, Extbase seem to only support to have one table. See https://docs.typo3.org/m/typo3/reference-tca/9.5/en-us/ColumnsConfig/Type/Group.html#foreign-table 

So I suggest that you extend the extension with a custom field, which holds your fe_users on event basis.

**Comment by rintisch** [comment]
That's a solution for this as well. Thanks for the feedback!
