### ISSUE TITLE
[FEATURE] Use FluidEmail in v10

### ISSUE THREAD

**Issue by rintisch** [derhansen/sf_event_mgt#852]
### User story
TYPO3 v10 [introduced FluidEmail](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.3/Feature-90266-Fluid-basedTemplatedEmails.html). So `EmailService.php`, `NotificationService.php` and the  and the email templates could be refactored to use `FluidEmail`.

**Comment by derhansen** [comment]
To be honest, I see no reason to refactor the whole test covered and working code to `FluidEmail`, which basically just uses the same base functionality (Symfony Mailer and Fluid StandaloneView) as the extension currently uses.

Could you please explain the benefit the extension would get from this refactoring.

**Comment by rintisch** [comment]
Sorry, did not think about the impact of it. Just thought that it would be nice to have emails consistenly styled with other mails from the TYPO3

**Comment by derhansen** [comment]
Closing the issue now, since I currently have no plans to refactor the notification sending process.

**Comment by derhansen** [comment]
Version 8.0.0 of the extension (TYPO3 v13 only) will have optional support for FluidEmail - see #1221

**Comment by rintisch** [comment]
Thank you!!! :)
