### ISSUE TITLE
[FEATURE] Referenced fields in CSV export

### ISSUE THREAD

**Issue by jackd248** [derhansen/sf_event_mgt#855]
Hej there,

I want to export some fields of a referenced entity within the default csv export. In the TypoScript settings it is possible to define the required fields, but just fields of the registration data model. 

```
# Throws an error
module.tx_sfeventmg.settings.csvExport.fields = event.title 
```

Could you extend the csv exporter to consider the referenced entities as well?

**Comment by christophlehmann** [comment]
Yeah, that would be a nice feature. Our use case is the reference to fe_users, because we have a separate user registration and thus some fields of the registration entity remains empty.

If accepted i could implement it, because we need it anyway.

**Comment by derhansen** [comment]
I'm already on it ;-)

**Comment by derhansen** [comment]
Feature is has been implemented in dev-branch.

**Comment by christophlehmann** [comment]
Works like a charm ;-) Thank you!
