### ISSUE TITLE
[BUG] Export registrations of "hidden" Events

### ISSUE THREAD

**Issue by madaxel** [derhansen/sf_event_mgt#861]
### Extension version
5.3.0

### Short problem description
CSV Export of registrations is not working on events having hidden =1
### Steps to reproduce
1. hide an event (set hidden = 1)
2. load Event module
3. export registrations of the hidden Event

### Expected behaviour
Export of csv data should be executed

### Actual behaviour
a blank frame is loaded

### Server configuration
**TYPO3 version: 10.4.13**

**PHP version: 7.2**

Problem occurs because the list action ignores enable fields whereas the exportAction does not https://github.com/derhansen/sf_event_mgt/blob/master/Classes/Controller/AdministrationController.php#L363

Possible Solutions
1. Do not display export button on hidden events
2. ignore enable fields for export, too
3. Display a flash message that the event could not be exported

I would like Option 2, but I did not check other parts of the extension, where the enable fields might break functionality, so 1. might be an option too

Regards
Markus

**Comment by derhansen** [comment]
Thanks, I will fix this bug in the upcoming version and implement option 2 as you suggested.

**Comment by madaxel** [comment]
damn fast ;-) thanks torben
