### ISSUE TITLE
[Question] Payment and waitlist combination

### ISSUE THREAD

**Issue by jackd248** [derhansen/sf_event_mgt#864]
### Extension version
**sf_event_mgt:** 4.3.1

### Short problem description
When registering to an event with an activated waitlist, the user gets forwarded to the payment process. So a user has to pay, even if he is only on the waitlist. That could be a bureaucratic nightmare to cancel the already completed payments.

Is this a conceptual problem? Or do I have to catch this special case? Or is waitlist and payment a bad combination? 

### Expected behaviour
The user register to the waitlist. Only when the registration was moved from the waitlist to the "accepted" registrations, the e-mail with the link to redirect view has to be sent and the payment process can be done. 

### Server configuration
**TYPO3 version:** 9.5.22
**PHP version:** 7.2.34

**Comment by derhansen** [comment]
Hm, never thought about this scenario. But yes, this is totally valid and currently not really supported. I could catch the Payment Redirect when the registration is on the waitlist but this would lead to the next problem when the user e.g. moves up automatically, then no payment redirect is processed.

So currently waitlist and payment is a non supported combination, but I will take some time to evaluate possible solutions.

**Comment by jackd248** [comment]
Thanks for the feedback, I will consider this and recommend to avoid this combination.

**Comment by derhansen** [comment]
Waitlist registration will not not redirect to the payment process any more. The new PSR-14 event `ProcessRedirectToPaymentEvent` allows to override this if someone also wants waitlist registrations to be paid.
