### ISSUE TITLE
[FEATURE] Add custom link for Terms&Conditions?

### ISSUE THREAD

**Issue by CMacFly** [derhansen/sf_event_mgt#866]
Hi,

I use your plugin in version 5.3.0 with typo3 10.4.14. Would it be possible to add a field for a URL to the AGB the customer has to accept? Some of them would perhaps like to read them befor checking the field. I hardcoded a line in Registration.html, but an input-field in the backend would be more elegant ...

Registration.html after line 279:
`<span><a href="[URL]">AGB lesen</a></span>`

Best regards, Christoph

**Comment by derhansen** [comment]
The default templates of the extension are very simple and only for demonstration purposes. An integrator will typically change/overwrite the default templates with custom ones (see https://docs.typo3.org/p/derhansen/sf_event_mgt/5.4/en-us/ForAdministrators/Templates/Changing/Index.html) and thereby have the possibility to add the required link to the markup.

However, I will consider to add a new link field to the plugin when configured to "Registration" mode.
