### ISSUE TITLE
[BUG] Exception in cancelRegistration when multipe registrations should be moved up (main_registration value error)

### ISSUE THREAD

**Issue by mmunz** [derhansen/sf_event_mgt#871]
### Extension version
5.4.0

### Short problem description
Clicking on a cancellation Link for in a multi-person registration leads to an exception, when the next registration to move up is also a multi-person registration.
TYPO3 exception thrown: "#1470230767 TYPO3\CMS\Extbase\Persistence\Generic\Storage\Exception\SqlErrorException" "Column 'main_registration' cannot be null"

This might be related to #870, but adding a TCA default value for the main_registration form didn't fix  the problem.

From quick analysis it looks like the registration is fetched from the repository in the checkCancelRegistrationfunction. In the registration object mainRegistration is null, while in the db the value is 0. The exception happens, when the object is persistted afterwards.

### Steps to reproduce
1. Have a registration form that has cancellation, waitlist and auto move up enabled. Allow a maximum of 2 registrations.
2. Register a user and select 2 persons
3. Register two more places with another user, both are on the waitlist
4. Open the cancellation link for the first user, exception is thrown.

### Expected behaviour
Show message, that cancellation was successful

### Actual behaviour
Exception thrown in frontend. Nevertheless the registration is still cancelled and the next two moved up.

### Server configuration
**TYPO3 version:** 10.4.14

**PHP version:**
7.4

**Comment by derhansen** [comment]
Bug see: https://github.com/derhansen/sf_event_mgt/blob/master/Classes/Service/RegistrationService.php#L584

Must find a better way to unset the property when `keepMainRegistrationDependency` is disabled.
