### ISSUE TITLE
Evaluate possibility to enable registration when startdate is reached

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [derhansen/sf_event_mgt#873]
Hi Torben,

as there are no recurring events possible, we "misused" the registration fields for registering to different dates. Means we have an event within f.e. 01.04. and 30.04 and registration field checkboxes with 5 dates within that date range.

Now the problem: Registration is only possible when **startdate of event is not reached**. This doesn't work of course so workaround is to move the startdate of the event further and further, which is of course confusing and not right.

What's the easiest way to bypass that restriction for that particular event in your code?
Much better: Would it be possible to implement an option in the registration settings (of each event) where you can switch off this restriction?

Cheers

**Comment by derhansen** [comment]
Hi, 

most easy solution is to override the the `getRegistrationPossible()` getter in https://github.com/derhansen/sf_event_mgt/blob/master/Classes/Domain/Model/Event.php#L873. This controls the logic if registration is allowed or not. 

I will not implement a setting for such an edge case, since it makes the extension harder to maintain and it is not really useful for the majority of users.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Ok, thanks for the fast reply. This helps and of course maintainability is important.

Another thought: I would have expected that the startdate restriction is bypassed whenever I set the field _registration_deadline_ to a date past _startdate_. If I set _registration_deadline_  then I want exactly that independent of the event startdate, don't you think?

**Comment by derhansen** [comment]
The logic of `getRegistrationPossible()` is documented (see https://docs.typo3.org/p/derhansen/sf_event_mgt/5.4/en-us/Faq/Index.html#when-does-event-registrationpossible-return-true) and this is something that users currently rely on, so I will not change that behavior.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Alright, no problem. Maybe it's an option for 6.0 where breaking changes or different behaviour is expected. ;-)

Thanks again and keep up the good work!

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Just in case someone needs it, too:

`    public function getRegistrationPossible()
    {
        $maxParticipantsNotReached = true;
        if ($this->getMaxParticipants() > 0 && $this->getRegistrations()->count() >= $this->maxParticipants) {
            $maxParticipantsNotReached = false;
        }
        $deadlineNotReached = true;
        if ($this->getRegistrationDeadline() != null && $this->getRegistrationDeadline() <= new \DateTime()) {
            $deadlineNotReached = false;
        }
        $registrationStartReached = true;
        if ($this->getRegistrationStartdate() != null && $this->getRegistrationStartdate() > new \DateTime()) {
            $registrationStartReached = false;
        }
        // Tweak start
        $deadlineAndEnddateNotReached = true;
        if ($this->getRegistrationDeadline() == null || $this->getRegistrationDeadline() <= new \DateTime() || $this->getEnddate() <= new \DateTime()) {
            $deadlineAndEnddateNotReached = false;
        }

        return ($this->getStartdate() > new \DateTime() || $deadlineAndEnddateNotReached) &&
        // Tweak end
            ($maxParticipantsNotReached || !$maxParticipantsNotReached && $this->enableWaitlist) &&
            $this->getEnableRegistration() && $deadlineNotReached && $registrationStartReached;
    }`

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Just in case someone needs it, too. Class: https://github.com/derhansen/sf_event_mgt/blob/master/Classes/Domain/Model/Event.php

    /**
     * Returns if the registration for this event is logically possible
     *
     * Tweak for removing the event startdate restriction if registration deadline (if set) and event enddate are not reached yet.
     * In that case the registration form is shown even if the startdate is reached.
     * https://docs.typo3.org/p/derhansen/sf_event_mgt/master/en-us/Faq/Index.html#when-does-event-registrationpossible-return-true
     *
     * @return bool
     */
    public function getRegistrationPossible()
    {
        $maxParticipantsNotReached = true;
        if ($this->getMaxParticipants() > 0 && $this->getRegistrations()->count() >= $this->maxParticipants) {
            $maxParticipantsNotReached = false;
        }
        $deadlineNotReached = true;
        if ($this->getRegistrationDeadline() != null && $this->getRegistrationDeadline() <= new \DateTime()) {
            $deadlineNotReached = false;
        }
        $registrationStartReached = true;
        if ($this->getRegistrationStartdate() != null && $this->getRegistrationStartdate() > new \DateTime()) {
            $registrationStartReached = false;
        }
        // Tweak start
        $deadlineAndEnddateNotReached = true;
        if ($this->getRegistrationDeadline() == null || $this->getRegistrationDeadline() <= new \DateTime() || $this->getEnddate() <= new \DateTime()) {
            $deadlineAndEnddateNotReached = false;
        }

        return ($this->getStartdate() > new \DateTime() || $deadlineAndEnddateNotReached) &&
        // Tweak end
            ($maxParticipantsNotReached || !$maxParticipantsNotReached && $this->enableWaitlist) &&
            $this->getEnableRegistration() && $deadlineNotReached && $registrationStartReached;
    }
