### ISSUE TITLE
[BUG] Can't remove values of datetime fields

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [derhansen/sf_event_mgt#874]
### Extension version
Latest 5.4

### Short problem description

Can't remove starttime / endtime / registration_startdate / registration_deadline.

Issue: https://forge.typo3.org/issues/82756

Removing the fields starttime / endtime / archive (only EXT:news) works in page / content elements settings and EXT:news. Seems this happens with databases in strict mode and extension developers have to implementent a fix for their own. See https://forge.typo3.org/issues/82756#note-19

### Steps to reproduce
1. Set a datetime field
2. Try to empty that field and save again

### Expected behaviour
Field value will be deleted (empty)

### Actual behaviour
An error occurs on saving an empty value:

2: SQL error: 'Incorrect integer value: '' for column `db_name`.`tx_sfeventmgt_domain_model_event`.`starttime` at row 1' (tx_sfeventmgt_domain_model_event:1234)

### Workaround
Set the field to 0 directly in the database.

### Server configuration
TYPO3 10.4.15
PHP 7.4.15
MySQL 5.5.5-10.3.28-MariaDB

**Comment by derhansen** [comment]
Thanks, this seems to apply to all date-fields in the extension. Will take care ASAP.
