### ISSUE TITLE
[BUG] Type error in "hideInlineRegistrations" class

### ISSUE THREAD

**Issue by tobikummer** [derhansen/sf_event_mgt#875]
### Extension version
 5.4.1

### Steps to reproduce the error
If I set the "hideInlineRegistrations" to 20 and want to create a new event, the error 
`Oops, an error occurred! Argument 1 passed to DERHANSEN\SfEventMgt\Form\FormDataProvider\HideInlineRegistrations::getRegistrationCount() must be of the type int, string given, called in /var/www/vhosts/sfp.ch/httpdocs-typo3-10-20201211/releases/20210504065740/web/typo3conf/ext/sf_event_mgt/Classes/Form/FormDataProvider/HideInlineRegistrations.php on line 37` is thrown. 

The class "HideInlineRegistrations.php" has a type error on line 37. The function getRegistrationCount expects an integer, but a new created event has an uid like "NEW48393958" => a string.

### Fixing proposal
`$amountOfRegistrations = 0;
        if(is_int($result['databaseRow']['uid'])) {
            $amountOfRegistrations = $this->getRegistrationCount($result['databaseRow']['uid']);
        }`

### Server configuration
TYPO3 10.4 LTS
PHP 7.4

**Comment by derhansen** [comment]
Fixed in version 5.4.2 which has just been released on TER and packagist
