### ISSUE TITLE
[TASK] Do not show error message, when startdate equals enddate

### ISSUE THREAD

**Issue by krischanskide** [derhansen/sf_event_mgt#879]
### Extension version
5.4.2

### Short problem description
Dates without duration will show error message

### Steps to reproduce
1. Create event with identical values in startdate and enddate

### Expected behaviour
Identical values should pass the EventPlausabilityService by comparing the values with <= instead of <

### Actual behaviour
Form shows error message because isStartDateBeforeEndDate only allows startdates smaller than enddate

### Server configuration
**TYPO3 version:** 10.4.15

**PHP version:** 7.3.28

**Comment by derhansen** [comment]
Thanks for your report. Although you are logically right about, that the comparation should be with `<=`, I'm asking myself what use case you have for events with the same start and enddate.

**Comment by krischanskide** [comment]
Is there an option to omit the enddate? Often you don't know or don't need the duration of an event, so I really would appreciate it to have the option to omit the enddate or default it to the same value as the startdate.

**Comment by derhansen** [comment]
I digged into the issue and found out, that I by mistake made the `enddate` field required in #849.

I will change this back in #880. For this issue, I will add a check, that the message will not be shown, when the startdate equals the enddate.

**Comment by krischanskide** [comment]
Thank you very much!
