### ISSUE TITLE
multilanguage registrations leads to 404 error when using DOI and route enhancer in localized language

### ISSUE THREAD

**Issue by medarob** [derhansen/sf_event_mgt#889]
### Extension version
5.5.0

In a multilanguage site (1st language German/2nd language English) we have events where you can register.Registration works on the German site but not on the English site if we use route enhancers AND the double opt-in option `[enable_autoconfirm]` = disabled.
Registration works on the English site if we don't use the route enhancer.
Registration works also if we use route enhancer AND activate `[enable_autoconfirm]` so that there is no double opt-in.So, there seems to be a problem with `[enable_autoconfirm]` = disabled and route enhancers in a multi language website.

The error is the following:
After I filled out the registration form and click the send button I usually get a message on the page that I have to check my emails for the verification link. This message does not show and I get a 404-error in the FE.

```
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1544172838:
Error handler could not fetch error page "https://www.domain.de/en/404", reason: Client error: `GET https://www.domain.de/en/404` resulted in a `401 Unauthorized` response:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>401 Unauthorized</title> </head><body> <h1>Unauth (truncated...) |
RuntimeException thrown in file /var/www/test/public/typo3/sysext/core/Classes/Error/PageErrorHandler/PageContentErrorHandler.php in line 93.
Requested URL: https://www.domain.de/en/company/current-topics/events/details/save-registration-result/14165/0/d03ba9dc7792f805e860ee284cc75e104c7fdc2c?cHash=59cb126455ee4f99a403e18cf1998492
```

However, the mail with the link was sent. On the German site this links works and shows the message correctly.

https://www.domain.de/en/company/.../events/details/save-registration-result/12640/0/a6e250f45af7ce8a213087f27a4816c46363541d?cHash=bf437e76660435e1af09cde485b7af9b
=> **works not**

https://www.domain.de/unternehmen/.../veranstaltungen/details/save-registration-result/12640/0/a6e250f45af7ce8a213087f27a4816c46363541d?cHash=bf437e76660435e1af09cde485b7af9b
=> **works**

The path segments seems to be identical after "details". And as I said, without the route enhancer it works on the English website...

### Server configuration
**TYPO3 version:**
TYPO3 10.4.17

**PHP version:**
7.4.21

**Comment by derhansen** [comment]
After 1,5 hours of debugging I finally found the problem. The example in the docs was wrong. Please remove the `eventuid` aspect, since this parameter is not an aspect at all but just a simple UID.

**Comment by Xippo** [comment]
Hiho, i hit this one today in TYPO3 11 and Version 6.3. The docs for 6.3 and above shows again the aspect for `eventuid` for the EventRegistrationPlugin which leads to the same error.

**Comment by derhansen** [comment]
@Xippo Thanks for pointing this out. Will fix this in v6/v7 docs

**Comment by Xippo** [comment]
Thanks to you, for your great work on this extension :)
