### ISSUE TITLE
Problem when activating extension

### ISSUE THREAD

**Issue by departement-maine-et-loire** [derhansen/sf_event_mgt#918]
### Extension version
4.5.0

### Short problem description
We can't install sf_event_mgt, on a fresh install of Typo3. 

### Expected behaviour
Being able to install this extension

### Actual behaviour
There is a message "No extension configuration for extension sf_event_mgt found. Either this extension has no extension configuration or the configuration is not up to date. Execute the install tool to update configuration." and when we remove it from "PackageStates.php" logs tell us "Uncaught TYPO3 Exception: Class 'DERHANSEN\SfEventMgt\Utility\MiscUtility' not found | Error thrown in file /var/www/html/public/typo3conf/ext/sf_event_mgt/ext_localconf.php in line 91"

### Server configuration
**TYPO3 version:** 9.5.28

**PHP version:** 7.3.29

**Comment by derhansen** [comment]
Sorry, but I can not reproduce the problem on a fresh TYPO3 9.5. There seems to be something wrong with your setup. 
`No extension configuration for extension sf_event_mgt` indicates, that the extension is not fully installed and not Extension Settings are created in `LocalConfiguration.php` which usually happens automatically when you install the extension.

**Comment by departement-maine-et-loire** [comment]
After a clean installation again, problem doesn't seem to be here anymore. Very weird problem, only on this specific extension.
