### ISSUE TITLE
Sorting registrations

### ISSUE THREAD

**Issue by blackbasket** [derhansen/sf_event_mgt#937]
Hi @derhansen ,

is it possible to sort registrations by lastname instead of uid in the plugin's backend?

Regards,
Marcel

**Comment by derhansen** [comment]
Not as far as I know, since the registration table is defined to have a manual sorting (see https://docs.typo3.org/m/typo3/reference-tca/10.4/en-us/Ctrl/Index.html#ctrl-reference-sortby) in order to let a backend user make changes to the sorting manually.

**Comment by blackbasket** [comment]
Thanks for the quick response.

How should I be able to sort manually? In the registrations tab I cannot find any table headers.

**Comment by derhansen** [comment]
There are no columns to sort by. It is the TYPO3 core function to apply manual sorting to the inline element.

![image](https://user-images.githubusercontent.com/2629896/133736291-1d5eb8c5-1b33-45fc-9d7c-8b4c43828be6.png)

**Comment by blackbasket** [comment]
Ok, thanks :(
