### ISSUE TITLE
Event list suddenly empty

### ISSUE THREAD

**Issue by erichenn** [derhansen/sf_event_mgt#942]
### Extension version
Tell me which version of sf_event_mgt you use
? as schiedsamt.de

### Short problem description
suddenly the event list on a page is empty; after an update on the page, the list displays correctly
this only appears on a page with 2 event modules that draw the events from diffent locations in the page tree

### Steps to reproduce
1. edit an event
2. wait
3. event list is empty
4. update page
5. event list is filled correctly

### Expected behaviour
event list should appear filled all the time

### Actual behaviour
event list appears suddenly empty

### Server configuration
**TYPO3 version:**
10.4.20
**PHP version:**
?

**Comment by derhansen** [comment]
I can not reproduce the problem, so this is most likely not an issue with the extension but with the setup of your website. Please check if there is custom code in your website that modifies query constraints or caching behaviour.

**Comment by erichenn** [comment]
The problem is indeed difficult to reproduce. Astonishingly I have a page with just one extension on it that never had the problem while the page with two extensions regularly has the problem.

The custom code on the website only modifies the appearnce but not the query or caching - see https://www.schiedsamt.de/fileadmin/assets/seminarverwaltung.js.

Any other ideas?

**Comment by derhansen** [comment]
`$('.event-list-item').remove();` <- this part of your JavaScript looks very strange and can be a reason why events are not shown. 

But as said: this is not an error in the extension but in your website, so there is nothing I can do here.
