### ISSUE TITLE
[FEATURE] AfterRegistrationCanceledEvent

### ISSUE THREAD

**Issue by marvinschroeder** [derhansen/sf_event_mgt#945]
Would be great to also have an event after a registration is canceled, for example an AfterRegistrationCanceledEvent. Or a BeforeRegistrationCanceledEvent, so that the registration model is available and can be used to do things based on that.

I know there is a ModifyCancelRegistrationViewVariablesEvent, but this event does not provide the registration model itself to do things based on the canceled registration.

**Comment by marvinschroeder** [comment]
Wow, that was fast, thanks! Any chances that this will be integrated into the version 5.x on a short term?

**Comment by derhansen** [comment]
Sure, will make a new release today or tomorrow

**Comment by derhansen** [comment]
Released with version 5.6.1
