### ISSUE TITLE
Problem with ke_search and routeEnhancer

### ISSUE THREAD

**Issue by taunusweb** [derhansen/sf_event_mgt#963]
Version:5.6.1
sf_event_mgt_indexer: 2.2.0
TYPO3 10LTS
PHP: 7.4
When I use the routeEnhancer from the documentation, I get the following Error:
`Parameter "tx_sfeventmgt_pievent__event" for route "tx_sfeventmgt_pievent_0" must match ".+" ("" given) to generate a corresponding URL.`
Without the routeEnhancer the Search works as expected. 
Do you have any hints for me?
Thanks Uli

**Comment by derhansen** [comment]
Please check the `records.slugBehavior` extension configuration. If the folder with extension records is _outside_ of your sites root page and `records.slugBehavior` is set to `uniqueInSite`, you may experience this problem. To fix this, either move the folder inside the below the root page of the site or set `records.slugBehavior` to `unique`.

**Comment by taunusweb** [comment]
Thanks a lot for your quick Answer, but that doesn't solve the problem. The folder is in my sites root page and even the change of the slugBehavior does not solve it.

**Comment by derhansen** [comment]
You could also check it the routing configuration is restricted to PIDs of the plugins (see `limitToPages` - https://docs.typo3.org/p/derhansen/sf_event_mgt/5.6/en-us/ForAdministrators/Configuration/RouteEnhancers/Index.html).

It that does not help, please try to add routes step by step and verify after each step, if routing / detail view still works. Also note, that the route enhancer configuration in the documentation is for example purposes and should be adjusted to your sites environment.

**Comment by taunusweb** [comment]
This line causes the problem:
    
` - { routePath: '/{event_title}', _controller: 'Event::detail', _arguments: {'event_title': 'event'} }`
limitToPages is set to the detailview and registration page.

**Comment by derhansen** [comment]
The provided example configuration from the documentation works on my test-system and is AFAIK also used on several other websites without any problems. So there must be a problem with your TYPO3 instance "somewhere". 

My last suggestion is to delete all event record directly in the database (maybe there is one record without a slug) and then create a new event record in the backend and ensure there is a slug present. 

If this does not help, then I sadly have no other ideas to help you other than that I can check your website/setup for any errors. This service will of course not be for free.

**Comment by taunusweb** [comment]
Aaaaah, that's it, we imported the Events from another database and edited them manually....

**Comment by derhansen** [comment]
Glad I could help and thanks a lot for your support. It is highly appreciated.
