### ISSUE TITLE
[FEATURE] Enrich AfterAdminMessageSentEvent with messageType

### ISSUE THREAD

**Issue by christophlehmann** [derhansen/sf_event_mgt#967]
I like to send a mail "Minimum number of attendees is reached". For this i use the AfterAdminMessageSentEvent event. Here i need to know which action is currently in action, because i don't want to send it for cancelRegistration. Adding `$type` in `sendAdminMessage()` to AfterAdminMessageSentEvent would help here. 

This could also be achieved with digging in TYPO3_REQUEST for the query parameter, but extending the event seems to be the better choice for me.

**Comment by derhansen** [comment]
Thanks for the PR. Do you also need the `$type` in version 5 (for TYPO3 10.4) of the extension?

**Comment by christophlehmann** [comment]
Thanks for the merge 👍 No backport needed, I will use a patch until version 6.
