### ISSUE TITLE
[TASK] No value for error missing gender input

### ISSUE THREAD

**Issue by Hogego** [derhansen/sf_event_mgt#973]
For all the required registration that are not filled fields there is an error message like: Der angegebene Wert ist leer.
But for the gender field this is not shown …. Could it be that this is missing?
Thanks a lot
Hoge

**Comment by derhansen** [comment]
I'll moved your issue to the correct tracker.

The default templates are for demonstration purposes only and you usually style/customize them for your project individually. But yes, the partial to render the validation error message of the field `gender` is not included in the template. I added it with 69608e9

**Comment by Hogego** [comment]
Got it. Thank you!
