### ISSUE TITLE
[FEATURE] Week view

### ISSUE THREAD

**Issue by cdaecke** [derhansen/sf_event_mgt#980]
First of all:
Thanks for your nice extension!!!

In a project I need a week view instead of the whole month in the calendar view. Are you interested in this feature in your extension? If so, I would try to create a pull request. If not, I will use the PSR-14 Events ;-)

**Comment by derhansen** [comment]
I this can already be archived without any modifications to the extension. Since the calendar view uses `overrideDemand` as a simple array, you can extend this dynamically with e.g. the  weeknumber.

**Example (hardcoded weeknumber 6 - see `week` parameter)**

```
<f:link.action rel="nofollow" action="calendar" controller="Event" arguments="{overwriteDemand:{month: nextMonthConfig.month, year: nextMonthConfig.year, week: 6}}">
    {f:format.date(date: nextMonthConfig.date, format: '%B %Y')} &rarr;
</f:link.action>
```

The weeknumber is passed as is to the resulting view (previous/next month), so basically you can use this in the template again as shown below (see condition).

```
<f:for each="{weeks}" as="week">
    <f:if condition="{week.0.weekNumber} == {overwriteDemand.week}">
        Show all days of week
    </f:if>
</f:for>
```

This will only show events for the week number 6.

The only "tricky" part will be to dynamically build the week-number parameter for the previous/next links if you want to browse between the single weeks individually. If that is not possible in fluid, a simple ViewHelper should do the job.

**Comment by cdaecke** [comment]
Thanks for your quick reply!

I have implemented you suggestion. The data for the week number is retrieved from the following PSR-14 event:

    <?php
    declare(strict_types=1);

    namespace Vendor\Extension\EventListener;

    use DERHANSEN\SfEventMgt\Event\ModifyCalendarViewVariablesEvent;

    
    final class CalendarViewVariables
    {
        
        public function enrichVariables(ModifyCalendarViewVariablesEvent $obj)
        {
            /** @var ModifyCalendarViewVariablesEvent $vars */
            $vars = $obj->getVariables();
            $vars['feUser'] = $GLOBALS['TSFE']->fe_user->user;
            $vars['today'] = strtotime('00:00:00');

            $week = (int)$vars['overwriteDemand']['week'];
            $year = (int)$vars['overwriteDemand']['year'];
            if (!$week || !$year) {
                $vars['weekdata'] = $this->getWeekData();
            } else {
                $vars['weekdata'] = $this->getWeekData($year, $week);
            }

            $obj->setVariables($vars);
        }

        private function getWeekData(int $year = null, int $week = null): array
        {
            if (empty($year) && empty($week)) {
                $week = (int)date('W');
                $year = (int)date('Y');
            }

            $nextDate = (new \DateTime())->setISODate($year, $week + 1);
            $previousDate = (new \DateTime())->setISODate($year, $week - 1);

            return [
                'year' => $year,
                'month' => (int)date('m'),
                'week' => $week,
                'next' => [
                    'year' => (int)$nextDate->format('Y'),
                    'month' => (int)$nextDate->format('m'),
                    'week' => (int)$nextDate->format('W'),
                ],
                'previous' => [
                    'year' => (int)$previousDate->format('Y'),
                    'month' => (int)$previousDate->format('m'),
                    'week' => (int)$previousDate->format('W'),
                ],
            ];
        }

This is all working perfectly well!
But... ;-)
As far as I can see, there is no restriction for the week in the `EventRepository` and the if condition in the weeks loop in the template hurts in my eyes. That are the reasons, why I suggested to implement a separate week view.

But I totally agree, if you don't want to bloat the extension for a feature, which wouldn't be used often. Your decision ;-)

**Comment by derhansen** [comment]
A separate week view would be too much IMO. But I like to have the possibility to have a week view without any extra ViewHelpers or ugly template magic. Therefore I will add week numbers as index to `$weekdata` variable as shown below in the fluid debug.

![image](https://user-images.githubusercontent.com/2629896/152302535-3126bf5f-c475-4e31-aa23-f4459ddd23d5.png)

I will also try to extend the calendarAction, so it will be possible to browse through a years weeks without the requirement of overwriting the month. Routing config will however be a little bit tricky if a website must support both a month and a week view, but this will just be a matter of proper routing config (january 2022 = `/events/2022/month/1` and week 1 in 2022 = `/events/2022/week/1`).

So I'll take over the ticket and push changes as soon as code, tests and docs are ready.

**Comment by cdaecke** [comment]
Wow, thanks a lot!

**Comment by derhansen** [comment]
Feature has been merged into development branch.

**Comment by derhansen** [comment]
Yes, would be a nice to have, but would also require an additional attribute for the eventDemand (week), which can be passed to the repository. I'll keep it as it is.

**Comment by derhansen** [comment]
I have no plans to backport the feature to v5 of the extension.
