### ISSUE TITLE
[FEATURE] Make hybrid online/offline events possible

### ISSUE THREAD

**Issue by peerlight** [derhansen/sf_event_mgt#982]
sf_event_mgt at the moment is limited to just one location.

There is a need to have hybrid events taking place in a combination of online and offline participation.

Registration should be possible either for online or offline participation.

This could be done in several ways:

a) have an "online" location and allow multiple locations for an event 
- would make location filtering easier
- would also allow different online locations 

b) introduce a location handling for events where editors can set "online", "hybrid" or "offline" with hiding the location selector for "online"

What do you think?

**Comment by derhansen** [comment]
Thanks for your feature request. Although option a) may be a doable task, this feature will raise other demands. If an event can take place on multiple locations, the demand will rise, that participants should also register for a location (e.g. online or offline). And if so, there may be limited places for the offline event and unlimited places for the online event (current max participants feature). Or if online and offline participation will require different pricing or even payment methods/processes. Or if event participants should be notified based on if they participate online or offline. So "no" for option a).

If you with option b) mean an additional attribute for the `Event`, where the editor just selects an event type (undefined, online, offline, hybrid) for display in frontend context, there is a possibility to add this to the extension. But as soon as this new event type also affects event registration (e.g. select fiend in registration view), I see the same problems as for option a).

If you need either option a) or b) for a specific project, where e.g not all features of the extension are used, I suggest to create an extending extension for sf_event_mgt to add the required feature.

**Comment by basmussen** [comment]
Thank you for the request. After evaluating the requirements, this is a special case that we cannot accommodate in the extension. 

It will make sense for you to implement the requirement in a separate extension for event management.

**Comment by peerlight** [comment]
Thanks for your reply. 

Although it is a not so rare special case I totally understand your reservations and go with you in keeping the extension clean.

Intend to move into direction b) with unlimited online participation

**Comment by derhansen** [comment]
Closing the issue, as the described scenario is out of scope of the extension
