### ISSUE TITLE
[BUG] PriceOption model throws PHP "$event must not be accessed before initialization" error

### ISSUE THREAD

**Issue by FLeudts** [derhansen/sf_event_mgt#994]
### Extension version
6.2.1

### Short problem description
Extending DERHANSEN\SfEventMgt\Domain\Model\PriceOption results in a 
"$event must not be accessed before initialization" error if the method is accessed in a fluid template.

### Steps to reproduce
1. Extend the model and access the event from a method
2. Use the method in a template

### Expected behaviour
protected ?Event $event = null; would fix the error.

### Server configuration
**TYPO3 version:**
v11.5.8
**PHP version:**
8.0.16

**Comment by derhansen** [comment]
Thanks for your report. The issue has been fixed in development branch
